/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Verifica que el servidor, Postgres y Redis estén disponibles.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        Error: {
            /**
             * @description Código de error legible por máquina
             * @example validation_failed
             */
            code: string;
            /**
             * @description Descripción en español para mostrar al usuario
             * @example El campo CUIT es inválido
             */
            message: string;
            /** @description Contexto adicional (campos con error, etc.) */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sistema operativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Uno o más componentes degradados */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"] & {
                        postgres?: string;
                        redis?: string;
                    };
                };
            };
        };
    };
}
