// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one

INSERT INTO calendar_events (
    company_id, title, event_type_id, contact_id, assigned_user_id,
    starts_at, ends_at, all_day, status, notes,
    related_task_id, related_opportunity_id, related_project_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, company_id, title, event_type_id, contact_id, assigned_user_id, starts_at, ends_at, all_day, status, notes, related_task_id, related_opportunity_id, related_project_id, created_at, updated_at, deleted_at
`

type CreateCalendarEventParams struct {
	CompanyID            uuid.UUID          `db:"company_id" json:"company_id"`
	Title                string             `db:"title" json:"title"`
	EventTypeID          pgtype.UUID        `db:"event_type_id" json:"event_type_id"`
	ContactID            pgtype.UUID        `db:"contact_id" json:"contact_id"`
	AssignedUserID       uuid.UUID          `db:"assigned_user_id" json:"assigned_user_id"`
	StartsAt             pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt               pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	AllDay               bool               `db:"all_day" json:"all_day"`
	Status               string             `db:"status" json:"status"`
	Notes                *string            `db:"notes" json:"notes"`
	RelatedTaskID        pgtype.UUID        `db:"related_task_id" json:"related_task_id"`
	RelatedOpportunityID pgtype.UUID        `db:"related_opportunity_id" json:"related_opportunity_id"`
	RelatedProjectID     pgtype.UUID        `db:"related_project_id" json:"related_project_id"`
}

// ─── Calendar Events ───────────────────────────────────────────────────────────
func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.CompanyID,
		arg.Title,
		arg.EventTypeID,
		arg.ContactID,
		arg.AssignedUserID,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Status,
		arg.Notes,
		arg.RelatedTaskID,
		arg.RelatedOpportunityID,
		arg.RelatedProjectID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.EventTypeID,
		&i.ContactID,
		&i.AssignedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Status,
		&i.Notes,
		&i.RelatedTaskID,
		&i.RelatedOpportunityID,
		&i.RelatedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCalendarEventType = `-- name: CreateCalendarEventType :one


INSERT INTO calendar_event_types (company_id, name, color, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, name, color, icon, created_at
`

type CreateCalendarEventTypeParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
	Color     string    `db:"color" json:"color"`
	Icon      *string   `db:"icon" json:"icon"`
}

// Calendar queries for sqlc generation.
// ─── Calendar Event Types ──────────────────────────────────────────────────────
func (q *Queries) CreateCalendarEventType(ctx context.Context, arg CreateCalendarEventTypeParams) (CalendarEventType, error) {
	row := q.db.QueryRow(ctx, createCalendarEventType,
		arg.CompanyID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i CalendarEventType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getCalendarEventByID = `-- name: GetCalendarEventByID :one
SELECT id, company_id, title, event_type_id, contact_id, assigned_user_id, starts_at, ends_at, all_day, status, notes, related_task_id, related_opportunity_id, related_project_id, created_at, updated_at, deleted_at FROM calendar_events
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetCalendarEventByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetCalendarEventByID(ctx context.Context, arg GetCalendarEventByIDParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEventByID, arg.ID, arg.CompanyID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.EventTypeID,
		&i.ContactID,
		&i.AssignedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Status,
		&i.Notes,
		&i.RelatedTaskID,
		&i.RelatedOpportunityID,
		&i.RelatedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCalendarEventTypeByID = `-- name: GetCalendarEventTypeByID :one
SELECT id, company_id, name, color, icon, created_at FROM calendar_event_types WHERE id = $1 AND company_id = $2
`

type GetCalendarEventTypeByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetCalendarEventTypeByID(ctx context.Context, arg GetCalendarEventTypeByIDParams) (CalendarEventType, error) {
	row := q.db.QueryRow(ctx, getCalendarEventTypeByID, arg.ID, arg.CompanyID)
	var i CalendarEventType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarEventTypes = `-- name: ListCalendarEventTypes :many
SELECT id, company_id, name, color, icon, created_at FROM calendar_event_types WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListCalendarEventTypes(ctx context.Context, companyID uuid.UUID) ([]CalendarEventType, error) {
	rows, err := q.db.Query(ctx, listCalendarEventTypes, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEventType{}
	for rows.Next() {
		var i CalendarEventType
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, company_id, title, event_type_id, contact_id, assigned_user_id, starts_at, ends_at, all_day, status, notes, related_task_id, related_opportunity_id, related_project_id, created_at, updated_at, deleted_at FROM calendar_events
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($3::timestamptz IS NULL OR starts_at >= $3)
  AND ($4::timestamptz IS NULL OR starts_at <= $4)
  AND ($5::uuid IS NULL OR event_type_id = $5)
  AND ($6::uuid IS NULL OR contact_id = $6)
  AND ($7::uuid IS NULL OR assigned_user_id = $7)
  AND ($2::text = '' OR status = $2)
ORDER BY starts_at ASC
`

type ListCalendarEventsParams struct {
	CompanyID      uuid.UUID          `db:"company_id" json:"company_id"`
	Column2        string             `db:"column_2" json:"column_2"`
	FromTs         pgtype.Timestamptz `db:"from_ts" json:"from_ts"`
	ToTs           pgtype.Timestamptz `db:"to_ts" json:"to_ts"`
	EventTypeID    pgtype.UUID        `db:"event_type_id" json:"event_type_id"`
	ContactID      pgtype.UUID        `db:"contact_id" json:"contact_id"`
	AssignedUserID pgtype.UUID        `db:"assigned_user_id" json:"assigned_user_id"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents,
		arg.CompanyID,
		arg.Column2,
		arg.FromTs,
		arg.ToTs,
		arg.EventTypeID,
		arg.ContactID,
		arg.AssignedUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.EventTypeID,
			&i.ContactID,
			&i.AssignedUserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Status,
			&i.Notes,
			&i.RelatedTaskID,
			&i.RelatedOpportunityID,
			&i.RelatedProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarEventsForContact = `-- name: ListCalendarEventsForContact :many
SELECT id, company_id, title, event_type_id, contact_id, assigned_user_id, starts_at, ends_at, all_day, status, notes, related_task_id, related_opportunity_id, related_project_id, created_at, updated_at, deleted_at FROM calendar_events
WHERE company_id = $1 AND contact_id = $2 AND deleted_at IS NULL
ORDER BY starts_at DESC
`

type ListCalendarEventsForContactParams struct {
	CompanyID uuid.UUID   `db:"company_id" json:"company_id"`
	ContactID pgtype.UUID `db:"contact_id" json:"contact_id"`
}

func (q *Queries) ListCalendarEventsForContact(ctx context.Context, arg ListCalendarEventsForContactParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEventsForContact, arg.CompanyID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.EventTypeID,
			&i.ContactID,
			&i.AssignedUserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Status,
			&i.Notes,
			&i.RelatedTaskID,
			&i.RelatedOpportunityID,
			&i.RelatedProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCalendarEvent = `-- name: SoftDeleteCalendarEvent :exec
UPDATE calendar_events SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteCalendarEventParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteCalendarEvent(ctx context.Context, arg SoftDeleteCalendarEventParams) error {
	_, err := q.db.Exec(ctx, softDeleteCalendarEvent, arg.ID, arg.CompanyID)
	return err
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events SET
    title                  = $3,
    event_type_id          = $4,
    contact_id             = $5,
    assigned_user_id       = $6,
    starts_at              = $7,
    ends_at                = $8,
    all_day                = $9,
    status                 = $10,
    notes                  = $11,
    related_task_id        = $12,
    related_opportunity_id = $13,
    related_project_id     = $14,
    updated_at             = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, title, event_type_id, contact_id, assigned_user_id, starts_at, ends_at, all_day, status, notes, related_task_id, related_opportunity_id, related_project_id, created_at, updated_at, deleted_at
`

type UpdateCalendarEventParams struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	CompanyID            uuid.UUID          `db:"company_id" json:"company_id"`
	Title                string             `db:"title" json:"title"`
	EventTypeID          pgtype.UUID        `db:"event_type_id" json:"event_type_id"`
	ContactID            pgtype.UUID        `db:"contact_id" json:"contact_id"`
	AssignedUserID       uuid.UUID          `db:"assigned_user_id" json:"assigned_user_id"`
	StartsAt             pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt               pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	AllDay               bool               `db:"all_day" json:"all_day"`
	Status               string             `db:"status" json:"status"`
	Notes                *string            `db:"notes" json:"notes"`
	RelatedTaskID        pgtype.UUID        `db:"related_task_id" json:"related_task_id"`
	RelatedOpportunityID pgtype.UUID        `db:"related_opportunity_id" json:"related_opportunity_id"`
	RelatedProjectID     pgtype.UUID        `db:"related_project_id" json:"related_project_id"`
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateCalendarEvent,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.EventTypeID,
		arg.ContactID,
		arg.AssignedUserID,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Status,
		arg.Notes,
		arg.RelatedTaskID,
		arg.RelatedOpportunityID,
		arg.RelatedProjectID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.EventTypeID,
		&i.ContactID,
		&i.AssignedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Status,
		&i.Notes,
		&i.RelatedTaskID,
		&i.RelatedOpportunityID,
		&i.RelatedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
