// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCreateTOTPBackupCodes implements pgx.CopyFromSource.
type iteratorForCreateTOTPBackupCodes struct {
	rows                 []CreateTOTPBackupCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTOTPBackupCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTOTPBackupCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].CodeHash,
	}, nil
}

func (r iteratorForCreateTOTPBackupCodes) Err() error {
	return nil
}

// ─── TOTP Backup Codes ─────────────────────────────────────────────────────────
func (q *Queries) CreateTOTPBackupCodes(ctx context.Context, arg []CreateTOTPBackupCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"totp_backup_codes"}, []string{"user_id", "code_hash"}, &iteratorForCreateTOTPBackupCodes{rows: arg})
}
