// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
    company_id, entity_type, entity_id, file_name, content_type,
    size_bytes, storage_key, uploaded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, entity_type, entity_id, file_name, content_type, size_bytes, storage_key, uploaded_by, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	CompanyID   uuid.UUID `db:"company_id" json:"company_id"`
	EntityType  string    `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID `db:"entity_id" json:"entity_id"`
	FileName    string    `db:"file_name" json:"file_name"`
	ContentType string    `db:"content_type" json:"content_type"`
	SizeBytes   int64     `db:"size_bytes" json:"size_bytes"`
	StorageKey  string    `db:"storage_key" json:"storage_key"`
	UploadedBy  uuid.UUID `db:"uploaded_by" json:"uploaded_by"`
}

// Document (attachment) queries for sqlc generation.
// Metadata only; bytes live on disk under PIXS_STORAGE_DIR at storage_key.
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.CompanyID,
		arg.EntityType,
		arg.EntityID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, company_id, entity_type, entity_id, file_name, content_type, size_bytes, storage_key, uploaded_by, created_at, updated_at, deleted_at FROM documents
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetDocumentByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.CompanyID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, company_id, entity_type, entity_id, file_name, content_type, size_bytes, storage_key, uploaded_by, created_at, updated_at, deleted_at FROM documents
WHERE company_id = $1
  AND entity_type = $2
  AND entity_id = $3
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListDocumentsParams struct {
	CompanyID  uuid.UUID `db:"company_id" json:"company_id"`
	EntityType string    `db:"entity_type" json:"entity_type"`
	EntityID   uuid.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.CompanyID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteDocumentParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.CompanyID)
	return err
}
