// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_receipt.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReceipt = `-- name: CreateReceipt :one

INSERT INTO receipts (
    company_id, idempotency_key, contact_id, date, number, currency,
    exchange_rate, total_amount, on_account_amount, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, company_id, idempotency_key, contact_id, date, number, currency, exchange_rate, total_amount, on_account_amount, notes, pdf_key, created_by, created_at, deleted_at
`

type CreateReceiptParams struct {
	CompanyID       uuid.UUID      `db:"company_id" json:"company_id"`
	IdempotencyKey  uuid.UUID      `db:"idempotency_key" json:"idempotency_key"`
	ContactID       uuid.UUID      `db:"contact_id" json:"contact_id"`
	Date            pgtype.Date    `db:"date" json:"date"`
	Number          int32          `db:"number" json:"number"`
	Currency        string         `db:"currency" json:"currency"`
	ExchangeRate    pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	TotalAmount     pgtype.Numeric `db:"total_amount" json:"total_amount"`
	OnAccountAmount pgtype.Numeric `db:"on_account_amount" json:"on_account_amount"`
	Notes           *string        `db:"notes" json:"notes"`
	CreatedBy       uuid.UUID      `db:"created_by" json:"created_by"`
}

// ─── Receipts ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.CompanyID,
		arg.IdempotencyKey,
		arg.ContactID,
		arg.Date,
		arg.Number,
		arg.Currency,
		arg.ExchangeRate,
		arg.TotalAmount,
		arg.OnAccountAmount,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.ContactID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.OnAccountAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReceiptApplication = `-- name: CreateReceiptApplication :one

INSERT INTO receipt_invoice_applications (receipt_id, invoice_id, amount)
VALUES ($1, $2, $3)
RETURNING id, receipt_id, invoice_id, amount
`

type CreateReceiptApplicationParams struct {
	ReceiptID uuid.UUID      `db:"receipt_id" json:"receipt_id"`
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
}

// ─── Receipt applications ──────────────────────────────────────────────────────
func (q *Queries) CreateReceiptApplication(ctx context.Context, arg CreateReceiptApplicationParams) (ReceiptInvoiceApplication, error) {
	row := q.db.QueryRow(ctx, createReceiptApplication, arg.ReceiptID, arg.InvoiceID, arg.Amount)
	var i ReceiptInvoiceApplication
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.InvoiceID,
		&i.Amount,
	)
	return i, err
}

const createReceiptPaymentMethod = `-- name: CreateReceiptPaymentMethod :one

INSERT INTO receipt_payment_methods (
    receipt_id, method_type, cash_register_id, bank_account_id,
    amount, currency, check_number, check_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, receipt_id, method_type, cash_register_id, bank_account_id, amount, currency, check_number, check_date
`

type CreateReceiptPaymentMethodParams struct {
	ReceiptID      uuid.UUID      `db:"receipt_id" json:"receipt_id"`
	MethodType     string         `db:"method_type" json:"method_type"`
	CashRegisterID pgtype.UUID    `db:"cash_register_id" json:"cash_register_id"`
	BankAccountID  pgtype.UUID    `db:"bank_account_id" json:"bank_account_id"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	Currency       *string        `db:"currency" json:"currency"`
	CheckNumber    *string        `db:"check_number" json:"check_number"`
	CheckDate      pgtype.Date    `db:"check_date" json:"check_date"`
}

// ─── Receipt payment methods ───────────────────────────────────────────────────
func (q *Queries) CreateReceiptPaymentMethod(ctx context.Context, arg CreateReceiptPaymentMethodParams) (ReceiptPaymentMethod, error) {
	row := q.db.QueryRow(ctx, createReceiptPaymentMethod,
		arg.ReceiptID,
		arg.MethodType,
		arg.CashRegisterID,
		arg.BankAccountID,
		arg.Amount,
		arg.Currency,
		arg.CheckNumber,
		arg.CheckDate,
	)
	var i ReceiptPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.MethodType,
		&i.CashRegisterID,
		&i.BankAccountID,
		&i.Amount,
		&i.Currency,
		&i.CheckNumber,
		&i.CheckDate,
	)
	return i, err
}

const getInvoiceApplicationSum = `-- name: GetInvoiceApplicationSum :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM receipt_invoice_applications
WHERE invoice_id = $1
`

func (q *Queries) GetInvoiceApplicationSum(ctx context.Context, invoiceID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getInvoiceApplicationSum, invoiceID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getReceiptByID = `-- name: GetReceiptByID :one
SELECT r.id, r.company_id, r.idempotency_key, r.contact_id, r.date, r.number, r.currency, r.exchange_rate, r.total_amount, r.on_account_amount, r.notes, r.pdf_key, r.created_by, r.created_at, r.deleted_at, c.fantasy_name AS contact_name
FROM receipts r
JOIN contacts c ON c.id = r.contact_id
WHERE r.id = $1 AND r.company_id = $2 AND r.deleted_at IS NULL
`

type GetReceiptByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

type GetReceiptByIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CompanyID       uuid.UUID          `db:"company_id" json:"company_id"`
	IdempotencyKey  uuid.UUID          `db:"idempotency_key" json:"idempotency_key"`
	ContactID       uuid.UUID          `db:"contact_id" json:"contact_id"`
	Date            pgtype.Date        `db:"date" json:"date"`
	Number          int32              `db:"number" json:"number"`
	Currency        string             `db:"currency" json:"currency"`
	ExchangeRate    pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	OnAccountAmount pgtype.Numeric     `db:"on_account_amount" json:"on_account_amount"`
	Notes           *string            `db:"notes" json:"notes"`
	PdfKey          *string            `db:"pdf_key" json:"pdf_key"`
	CreatedBy       uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	ContactName     string             `db:"contact_name" json:"contact_name"`
}

func (q *Queries) GetReceiptByID(ctx context.Context, arg GetReceiptByIDParams) (GetReceiptByIDRow, error) {
	row := q.db.QueryRow(ctx, getReceiptByID, arg.ID, arg.CompanyID)
	var i GetReceiptByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.ContactID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.OnAccountAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ContactName,
	)
	return i, err
}

const getReceiptByIdempotencyKey = `-- name: GetReceiptByIdempotencyKey :one
SELECT id, company_id, idempotency_key, contact_id, date, number, currency, exchange_rate, total_amount, on_account_amount, notes, pdf_key, created_by, created_at, deleted_at FROM receipts
WHERE company_id = $1 AND idempotency_key = $2 AND deleted_at IS NULL
`

type GetReceiptByIdempotencyKeyParams struct {
	CompanyID      uuid.UUID `db:"company_id" json:"company_id"`
	IdempotencyKey uuid.UUID `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetReceiptByIdempotencyKey(ctx context.Context, arg GetReceiptByIdempotencyKeyParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByIdempotencyKey, arg.CompanyID, arg.IdempotencyKey)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.ContactID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.OnAccountAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReceiptApplications = `-- name: ListReceiptApplications :many
SELECT id, receipt_id, invoice_id, amount FROM receipt_invoice_applications WHERE receipt_id = $1
`

func (q *Queries) ListReceiptApplications(ctx context.Context, receiptID uuid.UUID) ([]ReceiptInvoiceApplication, error) {
	rows, err := q.db.Query(ctx, listReceiptApplications, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptInvoiceApplication{}
	for rows.Next() {
		var i ReceiptInvoiceApplication
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.InvoiceID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptPaymentMethods = `-- name: ListReceiptPaymentMethods :many
SELECT id, receipt_id, method_type, cash_register_id, bank_account_id, amount, currency, check_number, check_date FROM receipt_payment_methods WHERE receipt_id = $1
`

func (q *Queries) ListReceiptPaymentMethods(ctx context.Context, receiptID uuid.UUID) ([]ReceiptPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listReceiptPaymentMethods, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptPaymentMethod{}
	for rows.Next() {
		var i ReceiptPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.MethodType,
			&i.CashRegisterID,
			&i.BankAccountID,
			&i.Amount,
			&i.Currency,
			&i.CheckNumber,
			&i.CheckDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, company_id, idempotency_key, contact_id, date, number, currency, exchange_rate, total_amount, on_account_amount, notes, pdf_key, created_by, created_at, deleted_at FROM receipts
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR contact_id = $2)
  AND ($3::date IS NULL OR date >= $3)
  AND ($4::date IS NULL OR date <= $4)
ORDER BY date DESC, created_at DESC
`

type ListReceiptsParams struct {
	CompanyID uuid.UUID   `db:"company_id" json:"company_id"`
	ContactID pgtype.UUID `db:"contact_id" json:"contact_id"`
	FromDate  pgtype.Date `db:"from_date" json:"from_date"`
	ToDate    pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListReceipts(ctx context.Context, arg ListReceiptsParams) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listReceipts,
		arg.CompanyID,
		arg.ContactID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.IdempotencyKey,
			&i.ContactID,
			&i.Date,
			&i.Number,
			&i.Currency,
			&i.ExchangeRate,
			&i.TotalAmount,
			&i.OnAccountAmount,
			&i.Notes,
			&i.PdfKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReceipt = `-- name: SoftDeleteReceipt :exec
UPDATE receipts SET deleted_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteReceiptParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteReceipt(ctx context.Context, arg SoftDeleteReceiptParams) error {
	_, err := q.db.Exec(ctx, softDeleteReceipt, arg.ID, arg.CompanyID)
	return err
}
