// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_reporting.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getArPayables = `-- name: GetArPayables :many
SELECT
    ir.id, ir.supplier_id, c.fantasy_name AS supplier_name,
    ir.invoice_type, ir.number, ir.issue_date, ir.due_date, ir.currency,
    ir.total_amount, ir.paid_amount,
    (ir.total_amount - ir.paid_amount)::numeric AS remaining,
    ir.status
FROM invoices_received ir
JOIN contacts c ON c.id = ir.supplier_id
WHERE ir.company_id = $1
  AND ir.deleted_at IS NULL
  AND ir.status IN ('pending','partially_paid')
  AND ($2::text IS NULL OR ir.currency = $2)
ORDER BY ir.due_date NULLS LAST
`

type GetArPayablesParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Currency  *string   `db:"currency" json:"currency"`
}

type GetArPayablesRow struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	SupplierID   uuid.UUID      `db:"supplier_id" json:"supplier_id"`
	SupplierName string         `db:"supplier_name" json:"supplier_name"`
	InvoiceType  *string        `db:"invoice_type" json:"invoice_type"`
	Number       *int32         `db:"number" json:"number"`
	IssueDate    pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate      pgtype.Date    `db:"due_date" json:"due_date"`
	Currency     *string        `db:"currency" json:"currency"`
	TotalAmount  pgtype.Numeric `db:"total_amount" json:"total_amount"`
	PaidAmount   pgtype.Numeric `db:"paid_amount" json:"paid_amount"`
	Remaining    pgtype.Numeric `db:"remaining" json:"remaining"`
	Status       string         `db:"status" json:"status"`
}

func (q *Queries) GetArPayables(ctx context.Context, arg GetArPayablesParams) ([]GetArPayablesRow, error) {
	rows, err := q.db.Query(ctx, getArPayables, arg.CompanyID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArPayablesRow{}
	for rows.Next() {
		var i GetArPayablesRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.SupplierName,
			&i.InvoiceType,
			&i.Number,
			&i.IssueDate,
			&i.DueDate,
			&i.Currency,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Remaining,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArReceivables = `-- name: GetArReceivables :many

SELECT
    i.id, i.contact_id, c.fantasy_name AS contact_name,
    i.invoice_type, i.number, i.issue_date, i.due_date, i.currency,
    i.total_amount, i.paid_amount,
    (i.total_amount - i.paid_amount)::numeric AS remaining,
    i.status
FROM invoices_issued i
JOIN contacts c ON c.id = i.contact_id
WHERE i.company_id = $1
  AND i.deleted_at IS NULL
  AND i.status IN ('issued','partially_paid','overdue')
  AND ($2::text IS NULL OR i.currency = $2)
ORDER BY i.due_date NULLS LAST
`

type GetArReceivablesParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Currency  *string   `db:"currency" json:"currency"`
}

type GetArReceivablesRow struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	ContactID   uuid.UUID      `db:"contact_id" json:"contact_id"`
	ContactName string         `db:"contact_name" json:"contact_name"`
	InvoiceType string         `db:"invoice_type" json:"invoice_type"`
	Number      *int32         `db:"number" json:"number"`
	IssueDate   pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate     pgtype.Date    `db:"due_date" json:"due_date"`
	Currency    string         `db:"currency" json:"currency"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
	PaidAmount  pgtype.Numeric `db:"paid_amount" json:"paid_amount"`
	Remaining   pgtype.Numeric `db:"remaining" json:"remaining"`
	Status      string         `db:"status" json:"status"`
}

// ─── Accounts receivable (CtaCte / cash flow) ──────────────────────────────────
func (q *Queries) GetArReceivables(ctx context.Context, arg GetArReceivablesParams) ([]GetArReceivablesRow, error) {
	rows, err := q.db.Query(ctx, getArReceivables, arg.CompanyID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetArReceivablesRow{}
	for rows.Next() {
		var i GetArReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.ContactName,
			&i.InvoiceType,
			&i.Number,
			&i.IssueDate,
			&i.DueDate,
			&i.Currency,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Remaining,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashFlowProjection = `-- name: GetCashFlowProjection :many
SELECT due_date, currency, direction, SUM(amount)::numeric AS amount
FROM (
    SELECT i.due_date AS due_date, i.currency AS currency, 'in' AS direction,
           (i.total_amount - i.paid_amount) AS amount
    FROM invoices_issued i
    WHERE i.company_id = $1 AND i.deleted_at IS NULL
      AND i.status IN ('issued','partially_paid','overdue')
      AND i.due_date IS NOT NULL
    UNION ALL
    SELECT o.due_date AS due_date, o.currency AS currency, 'out' AS direction,
           o.amount AS amount
    FROM payment_obligations o
    WHERE o.company_id = $1 AND o.deleted_at IS NULL AND o.status = 'pending'
) flows
WHERE ($2::text IS NULL OR currency = $2)
GROUP BY due_date, currency, direction
ORDER BY due_date
`

type GetCashFlowProjectionParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Currency  *string   `db:"currency" json:"currency"`
}

type GetCashFlowProjectionRow struct {
	DueDate   pgtype.Date    `db:"due_date" json:"due_date"`
	Currency  string         `db:"currency" json:"currency"`
	Direction string         `db:"direction" json:"direction"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
}

func (q *Queries) GetCashFlowProjection(ctx context.Context, arg GetCashFlowProjectionParams) ([]GetCashFlowProjectionRow, error) {
	rows, err := q.db.Query(ctx, getCashFlowProjection, arg.CompanyID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashFlowProjectionRow{}
	for rows.Next() {
		var i GetCashFlowProjectionRow
		if err := rows.Scan(
			&i.DueDate,
			&i.Currency,
			&i.Direction,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsolidatedBalance = `-- name: GetConsolidatedBalance :many
SELECT currency, SUM(balance)::numeric AS balance
FROM (
    SELECT cr.currency,
           COALESCE(SUM(CASE WHEN cm.type IN ('income','transfer_in') THEN cm.amount ELSE -cm.amount END), 0) AS balance
    FROM cash_registers cr
    LEFT JOIN cash_movements cm ON cm.cash_register_id = cr.id AND cm.deleted_at IS NULL
    WHERE cr.company_id = $1 AND cr.deleted_at IS NULL
    GROUP BY cr.currency
    UNION ALL
    SELECT ba.currency, COALESCE(SUM(ba.book_balance), 0) AS balance
    FROM bank_accounts_finance ba
    WHERE ba.company_id = $1 AND ba.deleted_at IS NULL
    GROUP BY ba.currency
) sources
GROUP BY currency
ORDER BY currency
`

type GetConsolidatedBalanceRow struct {
	Currency string         `db:"currency" json:"currency"`
	Balance  pgtype.Numeric `db:"balance" json:"balance"`
}

func (q *Queries) GetConsolidatedBalance(ctx context.Context, companyID uuid.UUID) ([]GetConsolidatedBalanceRow, error) {
	rows, err := q.db.Query(ctx, getConsolidatedBalance, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConsolidatedBalanceRow{}
	for rows.Next() {
		var i GetConsolidatedBalanceRow
		if err := rows.Scan(&i.Currency, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactInvoicesIssued = `-- name: GetContactInvoicesIssued :many

SELECT i.id, i.invoice_type, i.number, i.issue_date, i.due_date, i.currency,
       i.total_amount, i.paid_amount, i.status
FROM invoices_issued i
WHERE i.company_id = $1 AND i.contact_id = $2 AND i.deleted_at IS NULL
  AND i.status <> 'draft'
  AND ($3::text IS NULL OR i.currency = $3)
ORDER BY i.issue_date
`

type GetContactInvoicesIssuedParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
	Currency  *string   `db:"currency" json:"currency"`
}

type GetContactInvoicesIssuedRow struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	InvoiceType string         `db:"invoice_type" json:"invoice_type"`
	Number      *int32         `db:"number" json:"number"`
	IssueDate   pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate     pgtype.Date    `db:"due_date" json:"due_date"`
	Currency    string         `db:"currency" json:"currency"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
	PaidAmount  pgtype.Numeric `db:"paid_amount" json:"paid_amount"`
	Status      string         `db:"status" json:"status"`
}

// ─── Account statement (CtaCte for a single contact) ───────────────────────────
func (q *Queries) GetContactInvoicesIssued(ctx context.Context, arg GetContactInvoicesIssuedParams) ([]GetContactInvoicesIssuedRow, error) {
	rows, err := q.db.Query(ctx, getContactInvoicesIssued, arg.CompanyID, arg.ContactID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactInvoicesIssuedRow{}
	for rows.Next() {
		var i GetContactInvoicesIssuedRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceType,
			&i.Number,
			&i.IssueDate,
			&i.DueDate,
			&i.Currency,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactReceipts = `-- name: GetContactReceipts :many
SELECT r.id, r.date, r.number, r.currency, r.total_amount
FROM receipts r
WHERE r.company_id = $1 AND r.contact_id = $2 AND r.deleted_at IS NULL
  AND ($3::text IS NULL OR r.currency = $3)
ORDER BY r.date
`

type GetContactReceiptsParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
	Currency  *string   `db:"currency" json:"currency"`
}

type GetContactReceiptsRow struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Date        pgtype.Date    `db:"date" json:"date"`
	Number      int32          `db:"number" json:"number"`
	Currency    string         `db:"currency" json:"currency"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetContactReceipts(ctx context.Context, arg GetContactReceiptsParams) ([]GetContactReceiptsRow, error) {
	rows, err := q.db.Query(ctx, getContactReceipts, arg.CompanyID, arg.ContactID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactReceiptsRow{}
	for rows.Next() {
		var i GetContactReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Number,
			&i.Currency,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
