// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_misc.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRecurringNextDue = `-- name: AdvanceRecurringNextDue :one
UPDATE recurring_payments SET next_due_date = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at
`

type AdvanceRecurringNextDueParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	NextDueDate pgtype.Date `db:"next_due_date" json:"next_due_date"`
}

func (q *Queries) AdvanceRecurringNextDue(ctx context.Context, arg AdvanceRecurringNextDueParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, advanceRecurringNextDue, arg.ID, arg.CompanyID, arg.NextDueDate)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Frequency,
		&i.DueDay,
		&i.NextDueDate,
		&i.PaymentMethod,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (company_id, from_currency, to_currency, rate, date, source)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (company_id, from_currency, to_currency, date)
DO UPDATE SET rate = EXCLUDED.rate, source = EXCLUDED.source
RETURNING id, company_id, from_currency, to_currency, rate, date, source, created_at
`

type CreateExchangeRateParams struct {
	CompanyID    uuid.UUID      `db:"company_id" json:"company_id"`
	FromCurrency string         `db:"from_currency" json:"from_currency"`
	ToCurrency   string         `db:"to_currency" json:"to_currency"`
	Rate         pgtype.Numeric `db:"rate" json:"rate"`
	Date         pgtype.Date    `db:"date" json:"date"`
	Source       *string        `db:"source" json:"source"`
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, createExchangeRate,
		arg.CompanyID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Rate,
		arg.Date,
		arg.Source,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Date,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (
    company_id, date, category_id, description, amount, currency,
    paid_by_user_id, paid_by_cash_id, paid_by_bank_id, file_key, project_id,
    status, reimbursement_status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, company_id, date, category_id, description, amount, currency, paid_by_user_id, paid_by_cash_id, paid_by_bank_id, file_key, project_id, status, approver_id, approved_at, reimbursement_status, created_at, updated_at, deleted_at
`

type CreateExpenseParams struct {
	CompanyID           uuid.UUID      `db:"company_id" json:"company_id"`
	Date                pgtype.Date    `db:"date" json:"date"`
	CategoryID          uuid.UUID      `db:"category_id" json:"category_id"`
	Description         string         `db:"description" json:"description"`
	Amount              pgtype.Numeric `db:"amount" json:"amount"`
	Currency            *string        `db:"currency" json:"currency"`
	PaidByUserID        pgtype.UUID    `db:"paid_by_user_id" json:"paid_by_user_id"`
	PaidByCashID        pgtype.UUID    `db:"paid_by_cash_id" json:"paid_by_cash_id"`
	PaidByBankID        pgtype.UUID    `db:"paid_by_bank_id" json:"paid_by_bank_id"`
	FileKey             *string        `db:"file_key" json:"file_key"`
	ProjectID           pgtype.UUID    `db:"project_id" json:"project_id"`
	Status              string         `db:"status" json:"status"`
	ReimbursementStatus string         `db:"reimbursement_status" json:"reimbursement_status"`
}

// ─── Expenses ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.CompanyID,
		arg.Date,
		arg.CategoryID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.PaidByUserID,
		arg.PaidByCashID,
		arg.PaidByBankID,
		arg.FileKey,
		arg.ProjectID,
		arg.Status,
		arg.ReimbursementStatus,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Date,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.PaidByUserID,
		&i.PaidByCashID,
		&i.PaidByBankID,
		&i.FileKey,
		&i.ProjectID,
		&i.Status,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ReimbursementStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (company_id, name)
VALUES ($1, $2)
RETURNING id, company_id, name, is_active, created_at
`

type CreateExpenseCategoryParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.CompanyID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentObligation = `-- name: CreatePaymentObligation :one

INSERT INTO payment_obligations (
    company_id, source_type, source_id, description, amount, currency, due_date, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
RETURNING id, company_id, source_type, source_id, description, amount, currency, due_date, status, paid_at, payment_order_id, created_at, updated_at, deleted_at
`

type CreatePaymentObligationParams struct {
	CompanyID   uuid.UUID      `db:"company_id" json:"company_id"`
	SourceType  string         `db:"source_type" json:"source_type"`
	SourceID    pgtype.UUID    `db:"source_id" json:"source_id"`
	Description string         `db:"description" json:"description"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	Currency    *string        `db:"currency" json:"currency"`
	DueDate     pgtype.Date    `db:"due_date" json:"due_date"`
}

// ─── Payment obligations ───────────────────────────────────────────────────────
func (q *Queries) CreatePaymentObligation(ctx context.Context, arg CreatePaymentObligationParams) (PaymentObligation, error) {
	row := q.db.QueryRow(ctx, createPaymentObligation,
		arg.CompanyID,
		arg.SourceType,
		arg.SourceID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.DueDate,
	)
	var i PaymentObligation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.PaidAt,
		&i.PaymentOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRecurringPayment = `-- name: CreateRecurringPayment :one

INSERT INTO recurring_payments (
    company_id, supplier_id, description, amount, currency, frequency,
    due_day, next_due_date, payment_method, category_id, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'active')
RETURNING id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at
`

type CreateRecurringPaymentParams struct {
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	SupplierID    pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Description   string         `db:"description" json:"description"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Currency      *string        `db:"currency" json:"currency"`
	Frequency     string         `db:"frequency" json:"frequency"`
	DueDay        *int16         `db:"due_day" json:"due_day"`
	NextDueDate   pgtype.Date    `db:"next_due_date" json:"next_due_date"`
	PaymentMethod *string        `db:"payment_method" json:"payment_method"`
	CategoryID    pgtype.UUID    `db:"category_id" json:"category_id"`
}

// ─── Recurring payments ────────────────────────────────────────────────────────
func (q *Queries) CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createRecurringPayment,
		arg.CompanyID,
		arg.SupplierID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Frequency,
		arg.DueDay,
		arg.NextDueDate,
		arg.PaymentMethod,
		arg.CategoryID,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Frequency,
		&i.DueDay,
		&i.NextDueDate,
		&i.PaymentMethod,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, company_id, date, category_id, description, amount, currency, paid_by_user_id, paid_by_cash_id, paid_by_bank_id, file_key, project_id, status, approver_id, approved_at, reimbursement_status, created_at, updated_at, deleted_at FROM expenses
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetExpenseByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.CompanyID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Date,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.PaidByUserID,
		&i.PaidByCashID,
		&i.PaidByBankID,
		&i.FileKey,
		&i.ProjectID,
		&i.Status,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ReimbursementStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFinanceContactBalance = `-- name: GetFinanceContactBalance :one

SELECT contact_id, currency, balance, updated_at FROM contact_balances WHERE contact_id = $1 AND currency = $2
`

type GetFinanceContactBalanceParams struct {
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
	Currency  string    `db:"currency" json:"currency"`
}

// ─── Contact balances ──────────────────────────────────────────────────────────
func (q *Queries) GetFinanceContactBalance(ctx context.Context, arg GetFinanceContactBalanceParams) (ContactBalance, error) {
	row := q.db.QueryRow(ctx, getFinanceContactBalance, arg.ContactID, arg.Currency)
	var i ContactBalance
	err := row.Scan(
		&i.ContactID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestExchangeRate = `-- name: GetLatestExchangeRate :one
SELECT id, company_id, from_currency, to_currency, rate, date, source, created_at FROM exchange_rates
WHERE company_id = $1 AND from_currency = $2 AND to_currency = $3
ORDER BY date DESC
LIMIT 1
`

type GetLatestExchangeRateParams struct {
	CompanyID    uuid.UUID `db:"company_id" json:"company_id"`
	FromCurrency string    `db:"from_currency" json:"from_currency"`
	ToCurrency   string    `db:"to_currency" json:"to_currency"`
}

func (q *Queries) GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestExchangeRate, arg.CompanyID, arg.FromCurrency, arg.ToCurrency)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Date,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentObligationByID = `-- name: GetPaymentObligationByID :one
SELECT id, company_id, source_type, source_id, description, amount, currency, due_date, status, paid_at, payment_order_id, created_at, updated_at, deleted_at FROM payment_obligations
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetPaymentObligationByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetPaymentObligationByID(ctx context.Context, arg GetPaymentObligationByIDParams) (PaymentObligation, error) {
	row := q.db.QueryRow(ctx, getPaymentObligationByID, arg.ID, arg.CompanyID)
	var i PaymentObligation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.PaidAt,
		&i.PaymentOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecurringPaymentByID = `-- name: GetRecurringPaymentByID :one
SELECT id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at FROM recurring_payments
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetRecurringPaymentByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetRecurringPaymentByID(ctx context.Context, arg GetRecurringPaymentByIDParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getRecurringPaymentByID, arg.ID, arg.CompanyID)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Frequency,
		&i.DueDay,
		&i.NextDueDate,
		&i.PaymentMethod,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVATRateByID = `-- name: GetVATRateByID :one
SELECT id, company_id, name, rate_pct, is_active, created_at FROM vat_rates WHERE id = $1 AND company_id = $2
`

type GetVATRateByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetVATRateByID(ctx context.Context, arg GetVATRateByIDParams) (VatRate, error) {
	row := q.db.QueryRow(ctx, getVATRateByID, arg.ID, arg.CompanyID)
	var i VatRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.RatePct,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRecurringDue = `-- name: ListActiveRecurringDue :many
SELECT id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at FROM recurring_payments
WHERE company_id = $1 AND deleted_at IS NULL AND status = 'active'
  AND next_due_date IS NOT NULL AND next_due_date <= $2
`

type ListActiveRecurringDueParams struct {
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	NextDueDate pgtype.Date `db:"next_due_date" json:"next_due_date"`
}

func (q *Queries) ListActiveRecurringDue(ctx context.Context, arg ListActiveRecurringDueParams) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringDue, arg.CompanyID, arg.NextDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringPayment{}
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Frequency,
			&i.DueDay,
			&i.NextDueDate,
			&i.PaymentMethod,
			&i.CategoryID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, name, symbol FROM currencies ORDER BY code
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.Code, &i.Name, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, company_id, name, is_active, created_at FROM expense_categories WHERE company_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListExpenseCategories(ctx context.Context, companyID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, company_id, date, category_id, description, amount, currency, paid_by_user_id, paid_by_cash_id, paid_by_bank_id, file_key, project_id, status, approver_id, approved_at, reimbursement_status, created_at, updated_at, deleted_at FROM expenses
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR category_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::date IS NULL OR date >= $4)
  AND ($5::date IS NULL OR date <= $5)
ORDER BY date DESC, created_at DESC
`

type ListExpensesParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
	Status     *string     `db:"status" json:"status"`
	FromDate   pgtype.Date `db:"from_date" json:"from_date"`
	ToDate     pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.CompanyID,
		arg.CategoryID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Date,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.PaidByUserID,
			&i.PaidByCashID,
			&i.PaidByBankID,
			&i.FileKey,
			&i.ProjectID,
			&i.Status,
			&i.ApproverID,
			&i.ApprovedAt,
			&i.ReimbursementStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentConditions = `-- name: ListPaymentConditions :many
SELECT id, company_id, name, days, is_active, created_at FROM payment_conditions WHERE company_id = $1 AND is_active = true ORDER BY days
`

func (q *Queries) ListPaymentConditions(ctx context.Context, companyID uuid.UUID) ([]PaymentCondition, error) {
	rows, err := q.db.Query(ctx, listPaymentConditions, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentCondition{}
	for rows.Next() {
		var i PaymentCondition
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Days,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentObligations = `-- name: ListPaymentObligations :many
SELECT id, company_id, source_type, source_id, description, amount, currency, due_date, status, paid_at, payment_order_id, created_at, updated_at, deleted_at FROM payment_obligations
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR source_type = $3)
  AND ($4::date IS NULL OR due_date >= $4)
  AND ($5::date IS NULL OR due_date <= $5)
ORDER BY due_date
`

type ListPaymentObligationsParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	Status     *string     `db:"status" json:"status"`
	SourceType *string     `db:"source_type" json:"source_type"`
	FromDate   pgtype.Date `db:"from_date" json:"from_date"`
	ToDate     pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListPaymentObligations(ctx context.Context, arg ListPaymentObligationsParams) ([]PaymentObligation, error) {
	rows, err := q.db.Query(ctx, listPaymentObligations,
		arg.CompanyID,
		arg.Status,
		arg.SourceType,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentObligation{}
	for rows.Next() {
		var i PaymentObligation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.DueDate,
			&i.Status,
			&i.PaidAt,
			&i.PaymentOrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringPayments = `-- name: ListRecurringPayments :many
SELECT id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at FROM recurring_payments
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY next_due_date NULLS LAST
`

func (q *Queries) ListRecurringPayments(ctx context.Context, companyID uuid.UUID) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listRecurringPayments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringPayment{}
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Frequency,
			&i.DueDay,
			&i.NextDueDate,
			&i.PaymentMethod,
			&i.CategoryID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVATRates = `-- name: ListVATRates :many

SELECT id, company_id, name, rate_pct, is_active, created_at FROM vat_rates WHERE company_id = $1 AND is_active = true ORDER BY rate_pct
`

// ─── Catalogs ──────────────────────────────────────────────────────────────────
func (q *Queries) ListVATRates(ctx context.Context, companyID uuid.UUID) ([]VatRate, error) {
	rows, err := q.db.Query(ctx, listVATRates, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VatRate{}
	for rows.Next() {
		var i VatRate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.RatePct,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObligationPaid = `-- name: MarkObligationPaid :one
UPDATE payment_obligations SET
    status = 'paid', paid_at = now(), payment_order_id = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL AND status = 'pending'
RETURNING id, company_id, source_type, source_id, description, amount, currency, due_date, status, paid_at, payment_order_id, created_at, updated_at, deleted_at
`

type MarkObligationPaidParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	CompanyID      uuid.UUID   `db:"company_id" json:"company_id"`
	PaymentOrderID pgtype.UUID `db:"payment_order_id" json:"payment_order_id"`
}

func (q *Queries) MarkObligationPaid(ctx context.Context, arg MarkObligationPaidParams) (PaymentObligation, error) {
	row := q.db.QueryRow(ctx, markObligationPaid, arg.ID, arg.CompanyID, arg.PaymentOrderID)
	var i PaymentObligation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.PaidAt,
		&i.PaymentOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteExpenseParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, arg.ID, arg.CompanyID)
	return err
}

const softDeleteRecurringPayment = `-- name: SoftDeleteRecurringPayment :exec
UPDATE recurring_payments SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteRecurringPaymentParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteRecurringPayment(ctx context.Context, arg SoftDeleteRecurringPaymentParams) error {
	_, err := q.db.Exec(ctx, softDeleteRecurringPayment, arg.ID, arg.CompanyID)
	return err
}

const updateExpenseStatus = `-- name: UpdateExpenseStatus :one
UPDATE expenses SET
    status = $3, approver_id = $4, approved_at = $5,
    reimbursement_status = $6, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, date, category_id, description, amount, currency, paid_by_user_id, paid_by_cash_id, paid_by_bank_id, file_key, project_id, status, approver_id, approved_at, reimbursement_status, created_at, updated_at, deleted_at
`

type UpdateExpenseStatusParams struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CompanyID           uuid.UUID          `db:"company_id" json:"company_id"`
	Status              string             `db:"status" json:"status"`
	ApproverID          pgtype.UUID        `db:"approver_id" json:"approver_id"`
	ApprovedAt          pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ReimbursementStatus string             `db:"reimbursement_status" json:"reimbursement_status"`
}

func (q *Queries) UpdateExpenseStatus(ctx context.Context, arg UpdateExpenseStatusParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpenseStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.ApproverID,
		arg.ApprovedAt,
		arg.ReimbursementStatus,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Date,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.PaidByUserID,
		&i.PaidByCashID,
		&i.PaidByBankID,
		&i.FileKey,
		&i.ProjectID,
		&i.Status,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ReimbursementStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRecurringPayment = `-- name: UpdateRecurringPayment :one
UPDATE recurring_payments SET
    supplier_id = $3, description = $4, amount = $5, currency = $6,
    frequency = $7, due_day = $8, next_due_date = $9, payment_method = $10,
    category_id = $11, status = $12, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, supplier_id, description, amount, currency, frequency, due_day, next_due_date, payment_method, category_id, status, created_at, updated_at, deleted_at
`

type UpdateRecurringPaymentParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	SupplierID    pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Description   string         `db:"description" json:"description"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Currency      *string        `db:"currency" json:"currency"`
	Frequency     string         `db:"frequency" json:"frequency"`
	DueDay        *int16         `db:"due_day" json:"due_day"`
	NextDueDate   pgtype.Date    `db:"next_due_date" json:"next_due_date"`
	PaymentMethod *string        `db:"payment_method" json:"payment_method"`
	CategoryID    pgtype.UUID    `db:"category_id" json:"category_id"`
	Status        string         `db:"status" json:"status"`
}

func (q *Queries) UpdateRecurringPayment(ctx context.Context, arg UpdateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, updateRecurringPayment,
		arg.ID,
		arg.CompanyID,
		arg.SupplierID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Frequency,
		arg.DueDay,
		arg.NextDueDate,
		arg.PaymentMethod,
		arg.CategoryID,
		arg.Status,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Frequency,
		&i.DueDay,
		&i.NextDueDate,
		&i.PaymentMethod,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertFinanceContactBalance = `-- name: UpsertFinanceContactBalance :exec
INSERT INTO contact_balances (contact_id, currency, balance)
VALUES ($1, $2, $3)
ON CONFLICT (contact_id, currency) DO UPDATE
SET balance = contact_balances.balance + EXCLUDED.balance, updated_at = now()
`

type UpsertFinanceContactBalanceParams struct {
	ContactID uuid.UUID      `db:"contact_id" json:"contact_id"`
	Currency  string         `db:"currency" json:"currency"`
	Balance   pgtype.Numeric `db:"balance" json:"balance"`
}

func (q *Queries) UpsertFinanceContactBalance(ctx context.Context, arg UpsertFinanceContactBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertFinanceContactBalance, arg.ContactID, arg.Currency, arg.Balance)
	return err
}
