// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_cash.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeSession = `-- name: CloseSession :one
UPDATE cash_register_sessions SET
    closed_by = $2, closed_at = now(),
    declared_closing_balance = $3, calculated_closing_balance = $4,
    difference = $5, status = 'closed'
WHERE id = $1 AND status = 'open'
RETURNING id, cash_register_id, opened_by, opened_at, closed_by, closed_at, opening_balance, declared_closing_balance, calculated_closing_balance, difference, status
`

type CloseSessionParams struct {
	ID                       uuid.UUID      `db:"id" json:"id"`
	ClosedBy                 pgtype.UUID    `db:"closed_by" json:"closed_by"`
	DeclaredClosingBalance   pgtype.Numeric `db:"declared_closing_balance" json:"declared_closing_balance"`
	CalculatedClosingBalance pgtype.Numeric `db:"calculated_closing_balance" json:"calculated_closing_balance"`
	Difference               pgtype.Numeric `db:"difference" json:"difference"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (CashRegisterSession, error) {
	row := q.db.QueryRow(ctx, closeSession,
		arg.ID,
		arg.ClosedBy,
		arg.DeclaredClosingBalance,
		arg.CalculatedClosingBalance,
		arg.Difference,
	)
	var i CashRegisterSession
	err := row.Scan(
		&i.ID,
		&i.CashRegisterID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.OpeningBalance,
		&i.DeclaredClosingBalance,
		&i.CalculatedClosingBalance,
		&i.Difference,
		&i.Status,
	)
	return i, err
}

const createBankAccountFinance = `-- name: CreateBankAccountFinance :one

INSERT INTO bank_accounts_finance (
    company_id, bank_name, account_number, cbu, alias, currency,
    account_holder, book_balance, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)
RETURNING id, company_id, bank_name, account_number, cbu, alias, currency, account_holder, book_balance, is_active, created_at, updated_at, deleted_at
`

type CreateBankAccountFinanceParams struct {
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	BankName      string         `db:"bank_name" json:"bank_name"`
	AccountNumber *string        `db:"account_number" json:"account_number"`
	Cbu           *string        `db:"cbu" json:"cbu"`
	Alias         *string        `db:"alias" json:"alias"`
	Currency      string         `db:"currency" json:"currency"`
	AccountHolder *string        `db:"account_holder" json:"account_holder"`
	BookBalance   pgtype.Numeric `db:"book_balance" json:"book_balance"`
}

// ─── Bank accounts ─────────────────────────────────────────────────────────────
func (q *Queries) CreateBankAccountFinance(ctx context.Context, arg CreateBankAccountFinanceParams) (BankAccountsFinance, error) {
	row := q.db.QueryRow(ctx, createBankAccountFinance,
		arg.CompanyID,
		arg.BankName,
		arg.AccountNumber,
		arg.Cbu,
		arg.Alias,
		arg.Currency,
		arg.AccountHolder,
		arg.BookBalance,
	)
	var i BankAccountsFinance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.AccountNumber,
		&i.Cbu,
		&i.Alias,
		&i.Currency,
		&i.AccountHolder,
		&i.BookBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBankMovement = `-- name: CreateBankMovement :one

INSERT INTO bank_movements (
    company_id, bank_account_id, type, amount, currency, description,
    reference_type, reference_id, value_date, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, bank_account_id, type, amount, currency, description, reference_type, reference_id, reconciled, reconciled_at, value_date, created_by, created_at, deleted_at
`

type CreateBankMovementParams struct {
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	BankAccountID uuid.UUID      `db:"bank_account_id" json:"bank_account_id"`
	Type          string         `db:"type" json:"type"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Currency      string         `db:"currency" json:"currency"`
	Description   *string        `db:"description" json:"description"`
	ReferenceType *string        `db:"reference_type" json:"reference_type"`
	ReferenceID   pgtype.UUID    `db:"reference_id" json:"reference_id"`
	ValueDate     pgtype.Date    `db:"value_date" json:"value_date"`
	CreatedBy     uuid.UUID      `db:"created_by" json:"created_by"`
}

// ─── Bank movements ────────────────────────────────────────────────────────────
func (q *Queries) CreateBankMovement(ctx context.Context, arg CreateBankMovementParams) (BankMovement, error) {
	row := q.db.QueryRow(ctx, createBankMovement,
		arg.CompanyID,
		arg.BankAccountID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ValueDate,
		arg.CreatedBy,
	)
	var i BankMovement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankAccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Reconciled,
		&i.ReconciledAt,
		&i.ValueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCashMovement = `-- name: CreateCashMovement :one

INSERT INTO cash_movements (
    company_id, cash_register_id, session_id, type, amount, currency,
    description, reference_type, reference_id, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, cash_register_id, session_id, type, amount, currency, description, reference_type, reference_id, created_by, created_at, deleted_at
`

type CreateCashMovementParams struct {
	CompanyID      uuid.UUID      `db:"company_id" json:"company_id"`
	CashRegisterID uuid.UUID      `db:"cash_register_id" json:"cash_register_id"`
	SessionID      pgtype.UUID    `db:"session_id" json:"session_id"`
	Type           string         `db:"type" json:"type"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	Currency       string         `db:"currency" json:"currency"`
	Description    *string        `db:"description" json:"description"`
	ReferenceType  *string        `db:"reference_type" json:"reference_type"`
	ReferenceID    pgtype.UUID    `db:"reference_id" json:"reference_id"`
	CreatedBy      uuid.UUID      `db:"created_by" json:"created_by"`
}

// ─── Cash movements ────────────────────────────────────────────────────────────
func (q *Queries) CreateCashMovement(ctx context.Context, arg CreateCashMovementParams) (CashMovement, error) {
	row := q.db.QueryRow(ctx, createCashMovement,
		arg.CompanyID,
		arg.CashRegisterID,
		arg.SessionID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.CreatedBy,
	)
	var i CashMovement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CashRegisterID,
		&i.SessionID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCashRegister = `-- name: CreateCashRegister :one

INSERT INTO cash_registers (company_id, name, currency, responsible_id, is_active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, company_id, name, currency, responsible_id, is_active, created_at, updated_at, deleted_at
`

type CreateCashRegisterParams struct {
	CompanyID     uuid.UUID   `db:"company_id" json:"company_id"`
	Name          string      `db:"name" json:"name"`
	Currency      string      `db:"currency" json:"currency"`
	ResponsibleID pgtype.UUID `db:"responsible_id" json:"responsible_id"`
}

// ─── Cash registers ────────────────────────────────────────────────────────────
func (q *Queries) CreateCashRegister(ctx context.Context, arg CreateCashRegisterParams) (CashRegister, error) {
	row := q.db.QueryRow(ctx, createCashRegister,
		arg.CompanyID,
		arg.Name,
		arg.Currency,
		arg.ResponsibleID,
	)
	var i CashRegister
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Currency,
		&i.ResponsibleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBankAccountFinanceByID = `-- name: GetBankAccountFinanceByID :one
SELECT id, company_id, bank_name, account_number, cbu, alias, currency, account_holder, book_balance, is_active, created_at, updated_at, deleted_at FROM bank_accounts_finance
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetBankAccountFinanceByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetBankAccountFinanceByID(ctx context.Context, arg GetBankAccountFinanceByIDParams) (BankAccountsFinance, error) {
	row := q.db.QueryRow(ctx, getBankAccountFinanceByID, arg.ID, arg.CompanyID)
	var i BankAccountsFinance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.AccountNumber,
		&i.Cbu,
		&i.Alias,
		&i.Currency,
		&i.AccountHolder,
		&i.BookBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCashBalance = `-- name: GetCashBalance :one
SELECT COALESCE(SUM(CASE WHEN type IN ('income','transfer_in') THEN amount ELSE -amount END), 0)::numeric AS balance
FROM cash_movements
WHERE cash_register_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCashBalance(ctx context.Context, cashRegisterID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getCashBalance, cashRegisterID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const getCashRegisterByID = `-- name: GetCashRegisterByID :one
SELECT id, company_id, name, currency, responsible_id, is_active, created_at, updated_at, deleted_at FROM cash_registers
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetCashRegisterByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetCashRegisterByID(ctx context.Context, arg GetCashRegisterByIDParams) (CashRegister, error) {
	row := q.db.QueryRow(ctx, getCashRegisterByID, arg.ID, arg.CompanyID)
	var i CashRegister
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Currency,
		&i.ResponsibleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOpenSession = `-- name: GetOpenSession :one
SELECT id, cash_register_id, opened_by, opened_at, closed_by, closed_at, opening_balance, declared_closing_balance, calculated_closing_balance, difference, status FROM cash_register_sessions
WHERE cash_register_id = $1 AND status = 'open'
ORDER BY opened_at DESC
LIMIT 1
`

func (q *Queries) GetOpenSession(ctx context.Context, cashRegisterID uuid.UUID) (CashRegisterSession, error) {
	row := q.db.QueryRow(ctx, getOpenSession, cashRegisterID)
	var i CashRegisterSession
	err := row.Scan(
		&i.ID,
		&i.CashRegisterID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.OpeningBalance,
		&i.DeclaredClosingBalance,
		&i.CalculatedClosingBalance,
		&i.Difference,
		&i.Status,
	)
	return i, err
}

const listBankAccountsFinance = `-- name: ListBankAccountsFinance :many
SELECT id, company_id, bank_name, account_number, cbu, alias, currency, account_holder, book_balance, is_active, created_at, updated_at, deleted_at FROM bank_accounts_finance
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY bank_name
`

func (q *Queries) ListBankAccountsFinance(ctx context.Context, companyID uuid.UUID) ([]BankAccountsFinance, error) {
	rows, err := q.db.Query(ctx, listBankAccountsFinance, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankAccountsFinance{}
	for rows.Next() {
		var i BankAccountsFinance
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BankName,
			&i.AccountNumber,
			&i.Cbu,
			&i.Alias,
			&i.Currency,
			&i.AccountHolder,
			&i.BookBalance,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankMovements = `-- name: ListBankMovements :many
SELECT id, company_id, bank_account_id, type, amount, currency, description, reference_type, reference_id, reconciled, reconciled_at, value_date, created_by, created_at, deleted_at FROM bank_movements
WHERE bank_account_id = $1
  AND deleted_at IS NULL
  AND ($2::date IS NULL OR value_date >= $2)
  AND ($3::date IS NULL OR value_date <= $3)
ORDER BY value_date DESC, created_at DESC
`

type ListBankMovementsParams struct {
	BankAccountID uuid.UUID   `db:"bank_account_id" json:"bank_account_id"`
	FromDate      pgtype.Date `db:"from_date" json:"from_date"`
	ToDate        pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListBankMovements(ctx context.Context, arg ListBankMovementsParams) ([]BankMovement, error) {
	rows, err := q.db.Query(ctx, listBankMovements, arg.BankAccountID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankMovement{}
	for rows.Next() {
		var i BankMovement
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BankAccountID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Reconciled,
			&i.ReconciledAt,
			&i.ValueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashMovements = `-- name: ListCashMovements :many
SELECT id, company_id, cash_register_id, session_id, type, amount, currency, description, reference_type, reference_id, created_by, created_at, deleted_at FROM cash_movements
WHERE cash_register_id = $1
  AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
ORDER BY created_at DESC
`

type ListCashMovementsParams struct {
	CashRegisterID uuid.UUID          `db:"cash_register_id" json:"cash_register_id"`
	FromDate       pgtype.Timestamptz `db:"from_date" json:"from_date"`
	ToDate         pgtype.Timestamptz `db:"to_date" json:"to_date"`
}

func (q *Queries) ListCashMovements(ctx context.Context, arg ListCashMovementsParams) ([]CashMovement, error) {
	rows, err := q.db.Query(ctx, listCashMovements, arg.CashRegisterID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashMovement{}
	for rows.Next() {
		var i CashMovement
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CashRegisterID,
			&i.SessionID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashRegisters = `-- name: ListCashRegisters :many
SELECT id, company_id, name, currency, responsible_id, is_active, created_at, updated_at, deleted_at FROM cash_registers
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListCashRegisters(ctx context.Context, companyID uuid.UUID) ([]CashRegister, error) {
	rows, err := q.db.Query(ctx, listCashRegisters, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashRegister{}
	for rows.Next() {
		var i CashRegister
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Currency,
			&i.ResponsibleID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openCashSession = `-- name: OpenCashSession :one

INSERT INTO cash_register_sessions (cash_register_id, opened_by, opening_balance, status)
VALUES ($1, $2, $3, 'open')
RETURNING id, cash_register_id, opened_by, opened_at, closed_by, closed_at, opening_balance, declared_closing_balance, calculated_closing_balance, difference, status
`

type OpenCashSessionParams struct {
	CashRegisterID uuid.UUID      `db:"cash_register_id" json:"cash_register_id"`
	OpenedBy       uuid.UUID      `db:"opened_by" json:"opened_by"`
	OpeningBalance pgtype.Numeric `db:"opening_balance" json:"opening_balance"`
}

// ─── Cash sessions ─────────────────────────────────────────────────────────────
func (q *Queries) OpenCashSession(ctx context.Context, arg OpenCashSessionParams) (CashRegisterSession, error) {
	row := q.db.QueryRow(ctx, openCashSession, arg.CashRegisterID, arg.OpenedBy, arg.OpeningBalance)
	var i CashRegisterSession
	err := row.Scan(
		&i.ID,
		&i.CashRegisterID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.OpeningBalance,
		&i.DeclaredClosingBalance,
		&i.CalculatedClosingBalance,
		&i.Difference,
		&i.Status,
	)
	return i, err
}

const reconcileBankMovement = `-- name: ReconcileBankMovement :one
UPDATE bank_movements SET reconciled = true, reconciled_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, bank_account_id, type, amount, currency, description, reference_type, reference_id, reconciled, reconciled_at, value_date, created_by, created_at, deleted_at
`

type ReconcileBankMovementParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) ReconcileBankMovement(ctx context.Context, arg ReconcileBankMovementParams) (BankMovement, error) {
	row := q.db.QueryRow(ctx, reconcileBankMovement, arg.ID, arg.CompanyID)
	var i BankMovement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankAccountID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Reconciled,
		&i.ReconciledAt,
		&i.ValueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCashRegister = `-- name: SoftDeleteCashRegister :exec
UPDATE cash_registers SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteCashRegisterParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteCashRegister(ctx context.Context, arg SoftDeleteCashRegisterParams) error {
	_, err := q.db.Exec(ctx, softDeleteCashRegister, arg.ID, arg.CompanyID)
	return err
}

const updateBankAccountBalance = `-- name: UpdateBankAccountBalance :one
UPDATE bank_accounts_finance SET book_balance = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, bank_name, account_number, cbu, alias, currency, account_holder, book_balance, is_active, created_at, updated_at, deleted_at
`

type UpdateBankAccountBalanceParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CompanyID   uuid.UUID      `db:"company_id" json:"company_id"`
	BookBalance pgtype.Numeric `db:"book_balance" json:"book_balance"`
}

func (q *Queries) UpdateBankAccountBalance(ctx context.Context, arg UpdateBankAccountBalanceParams) (BankAccountsFinance, error) {
	row := q.db.QueryRow(ctx, updateBankAccountBalance, arg.ID, arg.CompanyID, arg.BookBalance)
	var i BankAccountsFinance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.AccountNumber,
		&i.Cbu,
		&i.Alias,
		&i.Currency,
		&i.AccountHolder,
		&i.BookBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBankAccountFinance = `-- name: UpdateBankAccountFinance :one
UPDATE bank_accounts_finance SET
    bank_name = $3, account_number = $4, cbu = $5, alias = $6,
    currency = $7, account_holder = $8, is_active = $9, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, bank_name, account_number, cbu, alias, currency, account_holder, book_balance, is_active, created_at, updated_at, deleted_at
`

type UpdateBankAccountFinanceParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	CompanyID     uuid.UUID `db:"company_id" json:"company_id"`
	BankName      string    `db:"bank_name" json:"bank_name"`
	AccountNumber *string   `db:"account_number" json:"account_number"`
	Cbu           *string   `db:"cbu" json:"cbu"`
	Alias         *string   `db:"alias" json:"alias"`
	Currency      string    `db:"currency" json:"currency"`
	AccountHolder *string   `db:"account_holder" json:"account_holder"`
	IsActive      bool      `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateBankAccountFinance(ctx context.Context, arg UpdateBankAccountFinanceParams) (BankAccountsFinance, error) {
	row := q.db.QueryRow(ctx, updateBankAccountFinance,
		arg.ID,
		arg.CompanyID,
		arg.BankName,
		arg.AccountNumber,
		arg.Cbu,
		arg.Alias,
		arg.Currency,
		arg.AccountHolder,
		arg.IsActive,
	)
	var i BankAccountsFinance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BankName,
		&i.AccountNumber,
		&i.Cbu,
		&i.Alias,
		&i.Currency,
		&i.AccountHolder,
		&i.BookBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCashRegister = `-- name: UpdateCashRegister :one
UPDATE cash_registers SET
    name = $3, currency = $4, responsible_id = $5, is_active = $6, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, name, currency, responsible_id, is_active, created_at, updated_at, deleted_at
`

type UpdateCashRegisterParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	CompanyID     uuid.UUID   `db:"company_id" json:"company_id"`
	Name          string      `db:"name" json:"name"`
	Currency      string      `db:"currency" json:"currency"`
	ResponsibleID pgtype.UUID `db:"responsible_id" json:"responsible_id"`
	IsActive      bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateCashRegister(ctx context.Context, arg UpdateCashRegisterParams) (CashRegister, error) {
	row := q.db.QueryRow(ctx, updateCashRegister,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Currency,
		arg.ResponsibleID,
		arg.IsActive,
	)
	var i CashRegister
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Currency,
		&i.ResponsibleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
