// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_invoice.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceDraft = `-- name: CreateInvoiceDraft :one

INSERT INTO invoices_issued (
    company_id, idempotency_key, invoice_type, sale_point, contact_id,
    issue_date, due_date, payment_condition_id, currency, exchange_rate,
    exchange_rate_date, status, net_amount, tax_amount, total_amount,
    project_id, quote_id, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'draft', $12, $13, $14, $15, $16, $17
)
RETURNING id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at
`

type CreateInvoiceDraftParams struct {
	CompanyID          uuid.UUID      `db:"company_id" json:"company_id"`
	IdempotencyKey     uuid.UUID      `db:"idempotency_key" json:"idempotency_key"`
	InvoiceType        string         `db:"invoice_type" json:"invoice_type"`
	SalePoint          int16          `db:"sale_point" json:"sale_point"`
	ContactID          uuid.UUID      `db:"contact_id" json:"contact_id"`
	IssueDate          pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate            pgtype.Date    `db:"due_date" json:"due_date"`
	PaymentConditionID pgtype.UUID    `db:"payment_condition_id" json:"payment_condition_id"`
	Currency           string         `db:"currency" json:"currency"`
	ExchangeRate       pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate   pgtype.Date    `db:"exchange_rate_date" json:"exchange_rate_date"`
	NetAmount          pgtype.Numeric `db:"net_amount" json:"net_amount"`
	TaxAmount          pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
	TotalAmount        pgtype.Numeric `db:"total_amount" json:"total_amount"`
	ProjectID          pgtype.UUID    `db:"project_id" json:"project_id"`
	QuoteID            pgtype.UUID    `db:"quote_id" json:"quote_id"`
	Notes              *string        `db:"notes" json:"notes"`
}

// ─── Invoices issued ───────────────────────────────────────────────────────────
func (q *Queries) CreateInvoiceDraft(ctx context.Context, arg CreateInvoiceDraftParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, createInvoiceDraft,
		arg.CompanyID,
		arg.IdempotencyKey,
		arg.InvoiceType,
		arg.SalePoint,
		arg.ContactID,
		arg.IssueDate,
		arg.DueDate,
		arg.PaymentConditionID,
		arg.Currency,
		arg.ExchangeRate,
		arg.ExchangeRateDate,
		arg.NetAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.ProjectID,
		arg.QuoteID,
		arg.Notes,
	)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one

INSERT INTO invoice_items (
    invoice_id, product_id, description, quantity, unit_price, discount_pct,
    vat_rate_id, line_net, line_tax, line_total, order_pos
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, invoice_id, product_id, description, quantity, unit_price, discount_pct, vat_rate_id, line_net, line_tax, line_total, order_pos
`

type CreateInvoiceItemParams struct {
	InvoiceID   uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	Description string         `db:"description" json:"description"`
	Quantity    pgtype.Numeric `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	DiscountPct pgtype.Numeric `db:"discount_pct" json:"discount_pct"`
	VatRateID   pgtype.UUID    `db:"vat_rate_id" json:"vat_rate_id"`
	LineNet     pgtype.Numeric `db:"line_net" json:"line_net"`
	LineTax     pgtype.Numeric `db:"line_tax" json:"line_tax"`
	LineTotal   pgtype.Numeric `db:"line_total" json:"line_total"`
	OrderPos    *int16         `db:"order_pos" json:"order_pos"`
}

// ─── Invoice items ─────────────────────────────────────────────────────────────
func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountPct,
		arg.VatRateID,
		arg.LineNet,
		arg.LineTax,
		arg.LineTotal,
		arg.OrderPos,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProductID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountPct,
		&i.VatRateID,
		&i.LineNet,
		&i.LineTax,
		&i.LineTotal,
		&i.OrderPos,
	)
	return i, err
}

const createInvoiceTax = `-- name: CreateInvoiceTax :one

INSERT INTO invoice_taxes (invoice_id, tax_type, rate_pct, base_amount, tax_amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, tax_type, rate_pct, base_amount, tax_amount
`

type CreateInvoiceTaxParams struct {
	InvoiceID  uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	TaxType    string         `db:"tax_type" json:"tax_type"`
	RatePct    pgtype.Numeric `db:"rate_pct" json:"rate_pct"`
	BaseAmount pgtype.Numeric `db:"base_amount" json:"base_amount"`
	TaxAmount  pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
}

// ─── Invoice taxes ─────────────────────────────────────────────────────────────
func (q *Queries) CreateInvoiceTax(ctx context.Context, arg CreateInvoiceTaxParams) (InvoiceTax, error) {
	row := q.db.QueryRow(ctx, createInvoiceTax,
		arg.InvoiceID,
		arg.TaxType,
		arg.RatePct,
		arg.BaseAmount,
		arg.TaxAmount,
	)
	var i InvoiceTax
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.TaxType,
		&i.RatePct,
		&i.BaseAmount,
		&i.TaxAmount,
	)
	return i, err
}

const deleteInvoiceItems = `-- name: DeleteInvoiceItems :exec
DELETE FROM invoice_items WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceItems(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItems, invoiceID)
	return err
}

const deleteInvoiceTaxes = `-- name: DeleteInvoiceTaxes :exec
DELETE FROM invoice_taxes WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceTaxes(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceTaxes, invoiceID)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at FROM invoices_issued
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetInvoiceByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.CompanyID)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceByIdempotencyKey = `-- name: GetInvoiceByIdempotencyKey :one
SELECT id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at FROM invoices_issued
WHERE company_id = $1 AND idempotency_key = $2 AND deleted_at IS NULL
`

type GetInvoiceByIdempotencyKeyParams struct {
	CompanyID      uuid.UUID `db:"company_id" json:"company_id"`
	IdempotencyKey uuid.UUID `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetInvoiceByIdempotencyKey(ctx context.Context, arg GetInvoiceByIdempotencyKeyParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIdempotencyKey, arg.CompanyID, arg.IdempotencyKey)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceForUpdate = `-- name: GetInvoiceForUpdate :one
SELECT id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at FROM invoices_issued
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetInvoiceForUpdateParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetInvoiceForUpdate(ctx context.Context, arg GetInvoiceForUpdateParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, getInvoiceForUpdate, arg.ID, arg.CompanyID)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const issueInvoice = `-- name: IssueInvoice :one
UPDATE invoices_issued SET status = 'issued', number = $3, idempotency_key = $4, updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'draft' AND deleted_at IS NULL
RETURNING id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at
`

type IssueInvoiceParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	CompanyID      uuid.UUID `db:"company_id" json:"company_id"`
	Number         *int32    `db:"number" json:"number"`
	IdempotencyKey uuid.UUID `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) IssueInvoice(ctx context.Context, arg IssueInvoiceParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, issueInvoice,
		arg.ID,
		arg.CompanyID,
		arg.Number,
		arg.IdempotencyKey,
	)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, product_id, description, quantity, unit_price, discount_pct, vat_rate_id, line_net, line_tax, line_total, order_pos FROM invoice_items WHERE invoice_id = $1 ORDER BY order_pos
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountPct,
			&i.VatRateID,
			&i.LineNet,
			&i.LineTax,
			&i.LineTotal,
			&i.OrderPos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceTaxes = `-- name: ListInvoiceTaxes :many
SELECT id, invoice_id, tax_type, rate_pct, base_amount, tax_amount FROM invoice_taxes WHERE invoice_id = $1
`

func (q *Queries) ListInvoiceTaxes(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceTax, error) {
	rows, err := q.db.Query(ctx, listInvoiceTaxes, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceTax{}
	for rows.Next() {
		var i InvoiceTax
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.TaxType,
			&i.RatePct,
			&i.BaseAmount,
			&i.TaxAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at FROM invoices_issued
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR contact_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::date IS NULL OR issue_date >= $4)
  AND ($5::date IS NULL OR issue_date <= $5)
ORDER BY issue_date DESC, created_at DESC
`

type ListInvoicesParams struct {
	CompanyID uuid.UUID   `db:"company_id" json:"company_id"`
	ContactID pgtype.UUID `db:"contact_id" json:"contact_id"`
	Status    *string     `db:"status" json:"status"`
	FromDate  pgtype.Date `db:"from_date" json:"from_date"`
	ToDate    pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]InvoicesIssued, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.CompanyID,
		arg.ContactID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicesIssued{}
	for rows.Next() {
		var i InvoicesIssued
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.IdempotencyKey,
			&i.InvoiceType,
			&i.SalePoint,
			&i.Number,
			&i.ContactID,
			&i.IssueDate,
			&i.DueDate,
			&i.PaymentConditionID,
			&i.Currency,
			&i.ExchangeRate,
			&i.ExchangeRateDate,
			&i.Status,
			&i.NetAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.ProjectID,
			&i.QuoteID,
			&i.Notes,
			&i.PdfKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSequenceNumber = `-- name: NextSequenceNumber :one

UPDATE sequence_numbers SET last_number = last_number + 1
WHERE company_id = $1 AND document_type = $2 AND sale_point = $3
RETURNING last_number
`

type NextSequenceNumberParams struct {
	CompanyID    uuid.UUID `db:"company_id" json:"company_id"`
	DocumentType string    `db:"document_type" json:"document_type"`
	SalePoint    int16     `db:"sale_point" json:"sale_point"`
}

// ─── Sequence numbering ────────────────────────────────────────────────────────
// Allocates the next document number atomically. The UPDATE acquires a
// row-level lock on the matching sequence_numbers row, so concurrent
// transactions are serialized and numbers are unique and gap-free.
func (q *Queries) NextSequenceNumber(ctx context.Context, arg NextSequenceNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextSequenceNumber, arg.CompanyID, arg.DocumentType, arg.SalePoint)
	var last_number int32
	err := row.Scan(&last_number)
	return last_number, err
}

const softDeleteInvoice = `-- name: SoftDeleteInvoice :exec
UPDATE invoices_issued SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'draft' AND deleted_at IS NULL
`

type SoftDeleteInvoiceParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteInvoice(ctx context.Context, arg SoftDeleteInvoiceParams) error {
	_, err := q.db.Exec(ctx, softDeleteInvoice, arg.ID, arg.CompanyID)
	return err
}

const updateInvoiceDraft = `-- name: UpdateInvoiceDraft :one
UPDATE invoices_issued SET
    contact_id = $3, issue_date = $4, due_date = $5, payment_condition_id = $6,
    currency = $7, exchange_rate = $8, exchange_rate_date = $9,
    net_amount = $10, tax_amount = $11, total_amount = $12,
    project_id = $13, quote_id = $14, notes = $15, updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'draft' AND deleted_at IS NULL
RETURNING id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at
`

type UpdateInvoiceDraftParams struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	CompanyID          uuid.UUID      `db:"company_id" json:"company_id"`
	ContactID          uuid.UUID      `db:"contact_id" json:"contact_id"`
	IssueDate          pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate            pgtype.Date    `db:"due_date" json:"due_date"`
	PaymentConditionID pgtype.UUID    `db:"payment_condition_id" json:"payment_condition_id"`
	Currency           string         `db:"currency" json:"currency"`
	ExchangeRate       pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate   pgtype.Date    `db:"exchange_rate_date" json:"exchange_rate_date"`
	NetAmount          pgtype.Numeric `db:"net_amount" json:"net_amount"`
	TaxAmount          pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
	TotalAmount        pgtype.Numeric `db:"total_amount" json:"total_amount"`
	ProjectID          pgtype.UUID    `db:"project_id" json:"project_id"`
	QuoteID            pgtype.UUID    `db:"quote_id" json:"quote_id"`
	Notes              *string        `db:"notes" json:"notes"`
}

func (q *Queries) UpdateInvoiceDraft(ctx context.Context, arg UpdateInvoiceDraftParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, updateInvoiceDraft,
		arg.ID,
		arg.CompanyID,
		arg.ContactID,
		arg.IssueDate,
		arg.DueDate,
		arg.PaymentConditionID,
		arg.Currency,
		arg.ExchangeRate,
		arg.ExchangeRateDate,
		arg.NetAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.ProjectID,
		arg.QuoteID,
		arg.Notes,
	)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoicePaidAmount = `-- name: UpdateInvoicePaidAmount :one
UPDATE invoices_issued SET
    paid_amount = $3,
    status = $4,
    updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at
`

type UpdateInvoicePaidAmountParams struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	CompanyID  uuid.UUID      `db:"company_id" json:"company_id"`
	PaidAmount pgtype.Numeric `db:"paid_amount" json:"paid_amount"`
	Status     string         `db:"status" json:"status"`
}

func (q *Queries) UpdateInvoicePaidAmount(ctx context.Context, arg UpdateInvoicePaidAmountParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, updateInvoicePaidAmount,
		arg.ID,
		arg.CompanyID,
		arg.PaidAmount,
		arg.Status,
	)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const voidInvoice = `-- name: VoidInvoice :one
UPDATE invoices_issued SET status = 'void', updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
  AND status NOT IN ('void')
RETURNING id, company_id, idempotency_key, invoice_type, sale_point, number, contact_id, issue_date, due_date, payment_condition_id, currency, exchange_rate, exchange_rate_date, status, net_amount, tax_amount, total_amount, paid_amount, project_id, quote_id, notes, pdf_key, created_at, updated_at, deleted_at
`

type VoidInvoiceParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) VoidInvoice(ctx context.Context, arg VoidInvoiceParams) (InvoicesIssued, error) {
	row := q.db.QueryRow(ctx, voidInvoice, arg.ID, arg.CompanyID)
	var i InvoicesIssued
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.ContactID,
		&i.IssueDate,
		&i.DueDate,
		&i.PaymentConditionID,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.Status,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.ProjectID,
		&i.QuoteID,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
