// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_invoice_received.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceReceived = `-- name: CreateInvoiceReceived :one

INSERT INTO invoices_received (
    company_id, supplier_id, invoice_type, sale_point, number, issue_date,
    due_date, currency, exchange_rate, exchange_rate_date,
    net_amount, tax_amount, total_amount, status, project_id, file_key, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'pending', $14, $15, $16
)
RETURNING id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at
`

type CreateInvoiceReceivedParams struct {
	CompanyID        uuid.UUID      `db:"company_id" json:"company_id"`
	SupplierID       uuid.UUID      `db:"supplier_id" json:"supplier_id"`
	InvoiceType      *string        `db:"invoice_type" json:"invoice_type"`
	SalePoint        *int16         `db:"sale_point" json:"sale_point"`
	Number           *int32         `db:"number" json:"number"`
	IssueDate        pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate          pgtype.Date    `db:"due_date" json:"due_date"`
	Currency         *string        `db:"currency" json:"currency"`
	ExchangeRate     pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate pgtype.Date    `db:"exchange_rate_date" json:"exchange_rate_date"`
	NetAmount        pgtype.Numeric `db:"net_amount" json:"net_amount"`
	TaxAmount        pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
	TotalAmount      pgtype.Numeric `db:"total_amount" json:"total_amount"`
	ProjectID        pgtype.UUID    `db:"project_id" json:"project_id"`
	FileKey          *string        `db:"file_key" json:"file_key"`
	Notes            *string        `db:"notes" json:"notes"`
}

// ─── Invoices received ─────────────────────────────────────────────────────────
func (q *Queries) CreateInvoiceReceived(ctx context.Context, arg CreateInvoiceReceivedParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, createInvoiceReceived,
		arg.CompanyID,
		arg.SupplierID,
		arg.InvoiceType,
		arg.SalePoint,
		arg.Number,
		arg.IssueDate,
		arg.DueDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.ExchangeRateDate,
		arg.NetAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.ProjectID,
		arg.FileKey,
		arg.Notes,
	)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceReceivedByID = `-- name: GetInvoiceReceivedByID :one
SELECT id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at FROM invoices_received
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetInvoiceReceivedByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetInvoiceReceivedByID(ctx context.Context, arg GetInvoiceReceivedByIDParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, getInvoiceReceivedByID, arg.ID, arg.CompanyID)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceReceivedForUpdate = `-- name: GetInvoiceReceivedForUpdate :one
SELECT id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at FROM invoices_received
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetInvoiceReceivedForUpdateParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetInvoiceReceivedForUpdate(ctx context.Context, arg GetInvoiceReceivedForUpdateParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, getInvoiceReceivedForUpdate, arg.ID, arg.CompanyID)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInvoicesReceived = `-- name: ListInvoicesReceived :many
SELECT id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at FROM invoices_received
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR supplier_id = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY issue_date DESC NULLS LAST, created_at DESC
`

type ListInvoicesReceivedParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	Status     *string     `db:"status" json:"status"`
}

func (q *Queries) ListInvoicesReceived(ctx context.Context, arg ListInvoicesReceivedParams) ([]InvoicesReceived, error) {
	rows, err := q.db.Query(ctx, listInvoicesReceived, arg.CompanyID, arg.SupplierID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicesReceived{}
	for rows.Next() {
		var i InvoicesReceived
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.InvoiceType,
			&i.SalePoint,
			&i.Number,
			&i.IssueDate,
			&i.DueDate,
			&i.Currency,
			&i.ExchangeRate,
			&i.ExchangeRateDate,
			&i.NetAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Status,
			&i.ProjectID,
			&i.FileKey,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvoiceReceived = `-- name: SoftDeleteInvoiceReceived :exec
UPDATE invoices_received SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteInvoiceReceivedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteInvoiceReceived(ctx context.Context, arg SoftDeleteInvoiceReceivedParams) error {
	_, err := q.db.Exec(ctx, softDeleteInvoiceReceived, arg.ID, arg.CompanyID)
	return err
}

const updateInvoiceReceived = `-- name: UpdateInvoiceReceived :one
UPDATE invoices_received SET
    supplier_id = $3, invoice_type = $4, sale_point = $5, number = $6,
    issue_date = $7, due_date = $8, currency = $9, exchange_rate = $10,
    exchange_rate_date = $11, net_amount = $12, tax_amount = $13,
    total_amount = $14, project_id = $15, file_key = $16, notes = $17, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at
`

type UpdateInvoiceReceivedParams struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	CompanyID        uuid.UUID      `db:"company_id" json:"company_id"`
	SupplierID       uuid.UUID      `db:"supplier_id" json:"supplier_id"`
	InvoiceType      *string        `db:"invoice_type" json:"invoice_type"`
	SalePoint        *int16         `db:"sale_point" json:"sale_point"`
	Number           *int32         `db:"number" json:"number"`
	IssueDate        pgtype.Date    `db:"issue_date" json:"issue_date"`
	DueDate          pgtype.Date    `db:"due_date" json:"due_date"`
	Currency         *string        `db:"currency" json:"currency"`
	ExchangeRate     pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate pgtype.Date    `db:"exchange_rate_date" json:"exchange_rate_date"`
	NetAmount        pgtype.Numeric `db:"net_amount" json:"net_amount"`
	TaxAmount        pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
	TotalAmount      pgtype.Numeric `db:"total_amount" json:"total_amount"`
	ProjectID        pgtype.UUID    `db:"project_id" json:"project_id"`
	FileKey          *string        `db:"file_key" json:"file_key"`
	Notes            *string        `db:"notes" json:"notes"`
}

func (q *Queries) UpdateInvoiceReceived(ctx context.Context, arg UpdateInvoiceReceivedParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, updateInvoiceReceived,
		arg.ID,
		arg.CompanyID,
		arg.SupplierID,
		arg.InvoiceType,
		arg.SalePoint,
		arg.Number,
		arg.IssueDate,
		arg.DueDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.ExchangeRateDate,
		arg.NetAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.ProjectID,
		arg.FileKey,
		arg.Notes,
	)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceReceivedPaidAmount = `-- name: UpdateInvoiceReceivedPaidAmount :one
UPDATE invoices_received SET paid_amount = $3, status = $4, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at
`

type UpdateInvoiceReceivedPaidAmountParams struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	CompanyID  uuid.UUID      `db:"company_id" json:"company_id"`
	PaidAmount pgtype.Numeric `db:"paid_amount" json:"paid_amount"`
	Status     string         `db:"status" json:"status"`
}

func (q *Queries) UpdateInvoiceReceivedPaidAmount(ctx context.Context, arg UpdateInvoiceReceivedPaidAmountParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, updateInvoiceReceivedPaidAmount,
		arg.ID,
		arg.CompanyID,
		arg.PaidAmount,
		arg.Status,
	)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const voidInvoiceReceived = `-- name: VoidInvoiceReceived :one
UPDATE invoices_received SET status = 'void', updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, supplier_id, invoice_type, sale_point, number, issue_date, due_date, currency, exchange_rate, exchange_rate_date, net_amount, tax_amount, total_amount, paid_amount, status, project_id, file_key, notes, created_at, updated_at, deleted_at
`

type VoidInvoiceReceivedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) VoidInvoiceReceived(ctx context.Context, arg VoidInvoiceReceivedParams) (InvoicesReceived, error) {
	row := q.db.QueryRow(ctx, voidInvoiceReceived, arg.ID, arg.CompanyID)
	var i InvoicesReceived
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.InvoiceType,
		&i.SalePoint,
		&i.Number,
		&i.IssueDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.NetAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.ProjectID,
		&i.FileKey,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
