// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_payment_order.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentOrder = `-- name: CreatePaymentOrder :one

INSERT INTO payment_orders (
    company_id, idempotency_key, supplier_id, date, number, currency,
    exchange_rate, total_amount, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, idempotency_key, supplier_id, date, number, currency, exchange_rate, total_amount, notes, pdf_key, created_by, created_at, deleted_at
`

type CreatePaymentOrderParams struct {
	CompanyID      uuid.UUID      `db:"company_id" json:"company_id"`
	IdempotencyKey uuid.UUID      `db:"idempotency_key" json:"idempotency_key"`
	SupplierID     uuid.UUID      `db:"supplier_id" json:"supplier_id"`
	Date           pgtype.Date    `db:"date" json:"date"`
	Number         int32          `db:"number" json:"number"`
	Currency       string         `db:"currency" json:"currency"`
	ExchangeRate   pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	TotalAmount    pgtype.Numeric `db:"total_amount" json:"total_amount"`
	Notes          *string        `db:"notes" json:"notes"`
	CreatedBy      uuid.UUID      `db:"created_by" json:"created_by"`
}

// ─── Payment orders ────────────────────────────────────────────────────────────
func (q *Queries) CreatePaymentOrder(ctx context.Context, arg CreatePaymentOrderParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, createPaymentOrder,
		arg.CompanyID,
		arg.IdempotencyKey,
		arg.SupplierID,
		arg.Date,
		arg.Number,
		arg.Currency,
		arg.ExchangeRate,
		arg.TotalAmount,
		arg.Notes,
		arg.CreatedBy,
	)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.SupplierID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPaymentOrderApplication = `-- name: CreatePaymentOrderApplication :one

INSERT INTO payment_order_applications (payment_order_id, invoice_received_id, amount)
VALUES ($1, $2, $3)
RETURNING id, payment_order_id, invoice_received_id, amount
`

type CreatePaymentOrderApplicationParams struct {
	PaymentOrderID    uuid.UUID      `db:"payment_order_id" json:"payment_order_id"`
	InvoiceReceivedID uuid.UUID      `db:"invoice_received_id" json:"invoice_received_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
}

// ─── Payment order applications ────────────────────────────────────────────────
func (q *Queries) CreatePaymentOrderApplication(ctx context.Context, arg CreatePaymentOrderApplicationParams) (PaymentOrderApplication, error) {
	row := q.db.QueryRow(ctx, createPaymentOrderApplication, arg.PaymentOrderID, arg.InvoiceReceivedID, arg.Amount)
	var i PaymentOrderApplication
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.InvoiceReceivedID,
		&i.Amount,
	)
	return i, err
}

const createPaymentOrderMethod = `-- name: CreatePaymentOrderMethod :one

INSERT INTO payment_order_methods (
    payment_order_id, method_type, cash_register_id, bank_account_id,
    amount, currency, check_number, check_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_order_id, method_type, cash_register_id, bank_account_id, amount, currency, check_number, check_date
`

type CreatePaymentOrderMethodParams struct {
	PaymentOrderID uuid.UUID      `db:"payment_order_id" json:"payment_order_id"`
	MethodType     string         `db:"method_type" json:"method_type"`
	CashRegisterID pgtype.UUID    `db:"cash_register_id" json:"cash_register_id"`
	BankAccountID  pgtype.UUID    `db:"bank_account_id" json:"bank_account_id"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	Currency       *string        `db:"currency" json:"currency"`
	CheckNumber    *string        `db:"check_number" json:"check_number"`
	CheckDate      pgtype.Date    `db:"check_date" json:"check_date"`
}

// ─── Payment order methods ─────────────────────────────────────────────────────
func (q *Queries) CreatePaymentOrderMethod(ctx context.Context, arg CreatePaymentOrderMethodParams) (PaymentOrderMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentOrderMethod,
		arg.PaymentOrderID,
		arg.MethodType,
		arg.CashRegisterID,
		arg.BankAccountID,
		arg.Amount,
		arg.Currency,
		arg.CheckNumber,
		arg.CheckDate,
	)
	var i PaymentOrderMethod
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.MethodType,
		&i.CashRegisterID,
		&i.BankAccountID,
		&i.Amount,
		&i.Currency,
		&i.CheckNumber,
		&i.CheckDate,
	)
	return i, err
}

const getInvoiceReceivedApplicationSum = `-- name: GetInvoiceReceivedApplicationSum :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM payment_order_applications
WHERE invoice_received_id = $1
`

func (q *Queries) GetInvoiceReceivedApplicationSum(ctx context.Context, invoiceReceivedID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getInvoiceReceivedApplicationSum, invoiceReceivedID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getPaymentOrderByID = `-- name: GetPaymentOrderByID :one
SELECT id, company_id, idempotency_key, supplier_id, date, number, currency, exchange_rate, total_amount, notes, pdf_key, created_by, created_at, deleted_at FROM payment_orders
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetPaymentOrderByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetPaymentOrderByID(ctx context.Context, arg GetPaymentOrderByIDParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getPaymentOrderByID, arg.ID, arg.CompanyID)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.SupplierID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentOrderByIdempotencyKey = `-- name: GetPaymentOrderByIdempotencyKey :one
SELECT id, company_id, idempotency_key, supplier_id, date, number, currency, exchange_rate, total_amount, notes, pdf_key, created_by, created_at, deleted_at FROM payment_orders
WHERE company_id = $1 AND idempotency_key = $2 AND deleted_at IS NULL
`

type GetPaymentOrderByIdempotencyKeyParams struct {
	CompanyID      uuid.UUID `db:"company_id" json:"company_id"`
	IdempotencyKey uuid.UUID `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetPaymentOrderByIdempotencyKey(ctx context.Context, arg GetPaymentOrderByIdempotencyKeyParams) (PaymentOrder, error) {
	row := q.db.QueryRow(ctx, getPaymentOrderByIdempotencyKey, arg.CompanyID, arg.IdempotencyKey)
	var i PaymentOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.IdempotencyKey,
		&i.SupplierID,
		&i.Date,
		&i.Number,
		&i.Currency,
		&i.ExchangeRate,
		&i.TotalAmount,
		&i.Notes,
		&i.PdfKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPaymentOrderApplications = `-- name: ListPaymentOrderApplications :many
SELECT id, payment_order_id, invoice_received_id, amount FROM payment_order_applications WHERE payment_order_id = $1
`

func (q *Queries) ListPaymentOrderApplications(ctx context.Context, paymentOrderID uuid.UUID) ([]PaymentOrderApplication, error) {
	rows, err := q.db.Query(ctx, listPaymentOrderApplications, paymentOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentOrderApplication{}
	for rows.Next() {
		var i PaymentOrderApplication
		if err := rows.Scan(
			&i.ID,
			&i.PaymentOrderID,
			&i.InvoiceReceivedID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentOrderMethods = `-- name: ListPaymentOrderMethods :many
SELECT id, payment_order_id, method_type, cash_register_id, bank_account_id, amount, currency, check_number, check_date FROM payment_order_methods WHERE payment_order_id = $1
`

func (q *Queries) ListPaymentOrderMethods(ctx context.Context, paymentOrderID uuid.UUID) ([]PaymentOrderMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentOrderMethods, paymentOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentOrderMethod{}
	for rows.Next() {
		var i PaymentOrderMethod
		if err := rows.Scan(
			&i.ID,
			&i.PaymentOrderID,
			&i.MethodType,
			&i.CashRegisterID,
			&i.BankAccountID,
			&i.Amount,
			&i.Currency,
			&i.CheckNumber,
			&i.CheckDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentOrders = `-- name: ListPaymentOrders :many
SELECT id, company_id, idempotency_key, supplier_id, date, number, currency, exchange_rate, total_amount, notes, pdf_key, created_by, created_at, deleted_at FROM payment_orders
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR supplier_id = $2)
  AND ($3::date IS NULL OR date >= $3)
  AND ($4::date IS NULL OR date <= $4)
ORDER BY date DESC, created_at DESC
`

type ListPaymentOrdersParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	FromDate   pgtype.Date `db:"from_date" json:"from_date"`
	ToDate     pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListPaymentOrders(ctx context.Context, arg ListPaymentOrdersParams) ([]PaymentOrder, error) {
	rows, err := q.db.Query(ctx, listPaymentOrders,
		arg.CompanyID,
		arg.SupplierID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentOrder{}
	for rows.Next() {
		var i PaymentOrder
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.IdempotencyKey,
			&i.SupplierID,
			&i.Date,
			&i.Number,
			&i.Currency,
			&i.ExchangeRate,
			&i.TotalAmount,
			&i.Notes,
			&i.PdfKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePaymentOrder = `-- name: SoftDeletePaymentOrder :exec
UPDATE payment_orders SET deleted_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeletePaymentOrderParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeletePaymentOrder(ctx context.Context, arg SoftDeletePaymentOrderParams) error {
	_, err := q.db.Exec(ctx, softDeletePaymentOrder, arg.ID, arg.CompanyID)
	return err
}
