// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT COUNT(*)::int FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) CountActiveSessions(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ─── Password Reset Tokens ─────────────────────────────────────────────────────
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (company_id, name, description, is_system)
VALUES ($1, $2, $3, false)
RETURNING id, company_id, name, description, is_system, created_at
`

type CreateRoleParams struct {
	CompanyID   uuid.UUID `db:"company_id" json:"company_id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.CompanyID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, company_id, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, company_id, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	IpAddress *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ─── Sessions ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.CompanyID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

type CreateTOTPBackupCodesParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	CodeHash string    `db:"code_hash" json:"code_hash"`
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (company_id, email, password_hash, full_name, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	CompanyID    uuid.UUID `db:"company_id" json:"company_id"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	FullName     string    `db:"full_name" json:"full_name"`
	IsActive     bool      `db:"is_active" json:"is_active"`
}

// ─── Users ─────────────────────────────────────────────────────────────────────
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CostRate,
		&i.CostRateCurrency,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE expires_at < now() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND company_id = $2 AND is_system = false
`

type DeleteRoleParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.CompanyID)
	return err
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type DeleteRolePermissionParams struct {
	RoleID       uuid.UUID `db:"role_id" json:"role_id"`
	PermissionID uuid.UUID `db:"permission_id" json:"permission_id"`
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const deleteRolePermissionsByRole = `-- name: DeleteRolePermissionsByRole :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissionsByRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionsByRole, roleID)
	return err
}

const deleteUserRolesByRole = `-- name: DeleteUserRolesByRole :exec
DELETE FROM user_roles WHERE role_id = $1
`

func (q *Queries) DeleteUserRolesByRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByRole, roleID)
	return err
}

const deleteUserTOTPBackupCodes = `-- name: DeleteUserTOTPBackupCodes :exec
DELETE FROM totp_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteUserTOTPBackupCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTOTPBackupCodes, userID)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one


SELECT id, legal_name, fantasy_name, cuit, vat_condition, fiscal_address, city, province, postal_code, logo_key, gross_income, activity_start_date, created_at, updated_at, deleted_at FROM companies WHERE id = $1 AND deleted_at IS NULL
`

// Identity queries for sqlc generation.
// All queries filter by company_id to enforce multi-tenancy.
// ─── Companies ─────────────────────────────────────────────────────────────────
func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.FantasyName,
		&i.Cuit,
		&i.VatCondition,
		&i.FiscalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.LogoKey,
		&i.GrossIncome,
		&i.ActivityStartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOldestActiveSession = `-- name: GetOldestActiveSession :one
SELECT id, user_id, company_id, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetOldestActiveSession(ctx context.Context, userID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getOldestActiveSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByModuleAction = `-- name: GetPermissionByModuleAction :one
SELECT id, module, action, description FROM permissions WHERE module = $1 AND action = $2
`

type GetPermissionByModuleActionParams struct {
	Module string `db:"module" json:"module"`
	Action string `db:"action" json:"action"`
}

func (q *Queries) GetPermissionByModuleAction(ctx context.Context, arg GetPermissionByModuleActionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByModuleAction, arg.Module, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Action,
		&i.Description,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one

SELECT id, company_id, name, description, is_system, created_at FROM roles WHERE id = $1 AND company_id = $2
`

type GetRoleByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

// ─── Roles ─────────────────────────────────────────────────────────────────────
func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.ID, arg.CompanyID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, company_id, name, description, is_system, created_at FROM roles WHERE name = $1 AND company_id = $2
`

type GetRoleByNameParams struct {
	Name      string    `db:"name" json:"name"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.Name, arg.CompanyID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many

SELECT p.module, p.action, rp.restricted_to_own
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

type GetRolePermissionsRow struct {
	Module          string `db:"module" json:"module"`
	Action          string `db:"action" json:"action"`
	RestrictedToOwn bool   `db:"restricted_to_own" json:"restricted_to_own"`
}

// ─── Role Permissions ──────────────────────────────────────────────────────────
func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(&i.Module, &i.Action, &i.RestrictedToOwn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, company_id, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM sessions WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUnusedTOTPBackupCodes = `-- name: GetUnusedTOTPBackupCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM totp_backup_codes
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) GetUnusedTOTPBackupCodes(ctx context.Context, userID uuid.UUID) ([]TotpBackupCode, error) {
	rows, err := q.db.Query(ctx, getUnusedTOTPBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotpBackupCode{}
	for rows.Next() {
		var i TotpBackupCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email     string    `db:"email" json:"email"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CostRate,
		&i.CostRateCurrency,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmailAnyCompany = `-- name: GetUserByEmailAnyCompany :one
SELECT id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

// Used during login before company is known (single-company context).
func (q *Queries) GetUserByEmailAnyCompany(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAnyCompany, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CostRate,
		&i.CostRateCurrency,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CostRate,
		&i.CostRateCurrency,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDAnyCompany = `-- name: GetUserByIDAnyCompany :one
SELECT id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// Used when company_id is not available (e.g. TOTP verification mid-login).
func (q *Queries) GetUserByIDAnyCompany(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDAnyCompany, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CostRate,
		&i.CostRateCurrency,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.module, p.action,
    bool_and(rp.restricted_to_own) AS restricted_to_own
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
GROUP BY p.module, p.action
`

type GetUserPermissionsRow struct {
	Module          string `db:"module" json:"module"`
	Action          string `db:"action" json:"action"`
	RestrictedToOwn bool   `db:"restricted_to_own" json:"restricted_to_own"`
}

// Returns all effective permissions for a user across all their roles.
// restricted_to_own is true only when ALL roles that grant this permission restrict it.
func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.Module, &i.Action, &i.RestrictedToOwn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT r.id, r.name, r.description, r.is_system
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

type GetUserRolesRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
}

// ─── User Roles ────────────────────────────────────────────────────────────────
func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (company_id, user_id, ip_address, entity_type, entity_id, action, before_state, after_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr `db:"ip_address" json:"ip_address"`
	EntityType  string      `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID   `db:"entity_id" json:"entity_id"`
	Action      string      `db:"action" json:"action"`
	BeforeState []byte      `db:"before_state" json:"before_state"`
	AfterState  []byte      `db:"after_state" json:"after_state"`
}

// ─── Audit Logs ────────────────────────────────────────────────────────────────
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.CompanyID,
		arg.UserID,
		arg.IpAddress,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, company_id, ip_address, user_agent, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, company_id, user_id, ip_address, timestamp, entity_type, entity_id, action, before_state, after_state FROM audit_logs
WHERE company_id = $1
  AND ($2::text = '' OR entity_type = $2)
  AND ($3::uuid IS NULL OR entity_id = $3)
ORDER BY timestamp DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Column2   string    `db:"column_2" json:"column_2"`
	Column3   uuid.UUID `db:"column_3" json:"column_3"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.IpAddress,
			&i.Timestamp,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeState,
			&i.AfterState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many

SELECT id, module, action, description FROM permissions ORDER BY module, action
`

// ─── Permissions ───────────────────────────────────────────────────────────────
func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Action,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, company_id, name, description, is_system, created_at FROM roles WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, companyID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, company_id, email, password_hash, full_name, is_active, cost_rate, cost_rate_currency, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListUsers(ctx context.Context, companyID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.IsActive,
			&i.CostRate,
			&i.CostRateCurrency,
			&i.TotpSecretEncrypted,
			&i.TotpEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}

const markTOTPBackupCodeUsed = `-- name: MarkTOTPBackupCodeUsed :exec
UPDATE totp_backup_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkTOTPBackupCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTOTPBackupCodeUsed, id)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2
`

type SoftDeleteUserParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.CompanyID)
	return err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET legal_name = $2, fantasy_name = $3, cuit = $4, vat_condition = $5,
    fiscal_address = $6, city = $7, province = $8, postal_code = $9,
    logo_key = $10, gross_income = $11, activity_start_date = $12,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, legal_name, fantasy_name, cuit, vat_condition, fiscal_address, city, province, postal_code, logo_key, gross_income, activity_start_date, created_at, updated_at, deleted_at
`

type UpdateCompanyParams struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	LegalName         string      `db:"legal_name" json:"legal_name"`
	FantasyName       string      `db:"fantasy_name" json:"fantasy_name"`
	Cuit              *string     `db:"cuit" json:"cuit"`
	VatCondition      *string     `db:"vat_condition" json:"vat_condition"`
	FiscalAddress     *string     `db:"fiscal_address" json:"fiscal_address"`
	City              *string     `db:"city" json:"city"`
	Province          *string     `db:"province" json:"province"`
	PostalCode        *string     `db:"postal_code" json:"postal_code"`
	LogoKey           *string     `db:"logo_key" json:"logo_key"`
	GrossIncome       *string     `db:"gross_income" json:"gross_income"`
	ActivityStartDate pgtype.Date `db:"activity_start_date" json:"activity_start_date"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.LegalName,
		arg.FantasyName,
		arg.Cuit,
		arg.VatCondition,
		arg.FiscalAddress,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.LogoKey,
		arg.GrossIncome,
		arg.ActivityStartDate,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.FantasyName,
		&i.Cuit,
		&i.VatCondition,
		&i.FiscalAddress,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.LogoKey,
		&i.GrossIncome,
		&i.ActivityStartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $3, description = $4
WHERE id = $1 AND company_id = $2 AND is_system = false
RETURNING id, company_id, name, description, is_system, created_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	CompanyID   uuid.UUID `db:"company_id" json:"company_id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Description,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}

const updateUserIsActive = `-- name: UpdateUserIsActive :exec
UPDATE users SET is_active = $2, updated_at = now()
WHERE id = $1 AND company_id = $3
`

type UpdateUserIsActiveParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	IsActive  bool      `db:"is_active" json:"is_active"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) error {
	_, err := q.db.Exec(ctx, updateUserIsActive, arg.ID, arg.IsActive, arg.CompanyID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :exec
UPDATE users
SET totp_secret_encrypted = $2, totp_enabled = $3, updated_at = now()
WHERE id = $1
`

type UpdateUserTOTPParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	TotpSecretEncrypted []byte    `db:"totp_secret_encrypted" json:"totp_secret_encrypted"`
	TotpEnabled         bool      `db:"totp_enabled" json:"totp_enabled"`
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTP, arg.ID, arg.TotpSecretEncrypted, arg.TotpEnabled)
	return err
}

const upsertRolePermission = `-- name: UpsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id, restricted_to_own)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, permission_id) DO UPDATE SET restricted_to_own = EXCLUDED.restricted_to_own
`

type UpsertRolePermissionParams struct {
	RoleID          uuid.UUID `db:"role_id" json:"role_id"`
	PermissionID    uuid.UUID `db:"permission_id" json:"permission_id"`
	RestrictedToOwn bool      `db:"restricted_to_own" json:"restricted_to_own"`
}

func (q *Queries) UpsertRolePermission(ctx context.Context, arg UpsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertRolePermission, arg.RoleID, arg.PermissionID, arg.RestrictedToOwn)
	return err
}
