// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: industry.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createIndustry = `-- name: CreateIndustry :one

INSERT INTO industries (company_id, name)
VALUES ($1, $2)
RETURNING id, company_id, name, created_at, updated_at, deleted_at
`

type CreateIndustryParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
}

// Industry (rubro) queries for sqlc generation.
func (q *Queries) CreateIndustry(ctx context.Context, arg CreateIndustryParams) (Industry, error) {
	row := q.db.QueryRow(ctx, createIndustry, arg.CompanyID, arg.Name)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIndustryByID = `-- name: GetIndustryByID :one
SELECT id, company_id, name, created_at, updated_at, deleted_at FROM industries
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetIndustryByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetIndustryByID(ctx context.Context, arg GetIndustryByIDParams) (Industry, error) {
	row := q.db.QueryRow(ctx, getIndustryByID, arg.ID, arg.CompanyID)
	var i Industry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIndustries = `-- name: ListIndustries :many
SELECT id, company_id, name, created_at, updated_at, deleted_at FROM industries
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListIndustries(ctx context.Context, companyID uuid.UUID) ([]Industry, error) {
	rows, err := q.db.Query(ctx, listIndustries, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Industry{}
	for rows.Next() {
		var i Industry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
