// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lead.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignLead = `-- name: AssignLead :one
UPDATE leads SET assigned_to = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at
`

type AssignLeadParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	AssignedTo pgtype.UUID `db:"assigned_to" json:"assigned_to"`
}

func (q *Queries) AssignLead(ctx context.Context, arg AssignLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, assignLead, arg.ID, arg.CompanyID, arg.AssignedTo)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const checkLeadDuplicate = `-- name: CheckLeadDuplicate :one
SELECT id FROM leads
WHERE company_id = $1 AND deleted_at IS NULL
  AND (
    (website IS NOT NULL AND website = $2) OR
    (lower(company_name) = lower($3))
  )
LIMIT 1
`

type CheckLeadDuplicateParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Website   *string   `db:"website" json:"website"`
	Lower     string    `db:"lower" json:"lower"`
}

func (q *Queries) CheckLeadDuplicate(ctx context.Context, arg CheckLeadDuplicateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkLeadDuplicate, arg.CompanyID, arg.Website, arg.Lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const convertLead = `-- name: ConvertLead :one
UPDATE leads SET status = 'converted', converted_contact_id = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at
`

type ConvertLeadParams struct {
	ID                 uuid.UUID   `db:"id" json:"id"`
	CompanyID          uuid.UUID   `db:"company_id" json:"company_id"`
	ConvertedContactID pgtype.UUID `db:"converted_contact_id" json:"converted_contact_id"`
}

func (q *Queries) ConvertLead(ctx context.Context, arg ConvertLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, convertLead, arg.ID, arg.CompanyID, arg.ConvertedContactID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countLeads = `-- name: CountLeads :one
SELECT COUNT(*) FROM leads
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR assigned_to = $3)
`

type CountLeadsParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	Status     *string     `db:"status" json:"status"`
	AssignedTo pgtype.UUID `db:"assigned_to" json:"assigned_to"`
}

func (q *Queries) CountLeads(ctx context.Context, arg CountLeadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads, arg.CompanyID, arg.Status, arg.AssignedTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (company_id, company_name, description, what_they_do, source_url, website,
    industry, approximate_size, city, country, language, assigned_to, status, scraping_job_id,
    follow_up_date, llm_extraction_failed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at
`

type CreateLeadParams struct {
	CompanyID           uuid.UUID   `db:"company_id" json:"company_id"`
	CompanyName         string      `db:"company_name" json:"company_name"`
	Description         *string     `db:"description" json:"description"`
	WhatTheyDo          *string     `db:"what_they_do" json:"what_they_do"`
	SourceUrl           *string     `db:"source_url" json:"source_url"`
	Website             *string     `db:"website" json:"website"`
	Industry            *string     `db:"industry" json:"industry"`
	ApproximateSize     *string     `db:"approximate_size" json:"approximate_size"`
	City                *string     `db:"city" json:"city"`
	Country             *string     `db:"country" json:"country"`
	Language            *string     `db:"language" json:"language"`
	AssignedTo          pgtype.UUID `db:"assigned_to" json:"assigned_to"`
	Status              string      `db:"status" json:"status"`
	ScrapingJobID       pgtype.UUID `db:"scraping_job_id" json:"scraping_job_id"`
	FollowUpDate        pgtype.Date `db:"follow_up_date" json:"follow_up_date"`
	LlmExtractionFailed bool        `db:"llm_extraction_failed" json:"llm_extraction_failed"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.CompanyID,
		arg.CompanyName,
		arg.Description,
		arg.WhatTheyDo,
		arg.SourceUrl,
		arg.Website,
		arg.Industry,
		arg.ApproximateSize,
		arg.City,
		arg.Country,
		arg.Language,
		arg.AssignedTo,
		arg.Status,
		arg.ScrapingJobID,
		arg.FollowUpDate,
		arg.LlmExtractionFailed,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLeadActivity = `-- name: CreateLeadActivity :one
INSERT INTO lead_activities (lead_id, user_id, activity_type, detail) VALUES ($1, $2, $3, $4) RETURNING id, lead_id, user_id, activity_type, detail, created_at
`

type CreateLeadActivityParams struct {
	LeadID       uuid.UUID   `db:"lead_id" json:"lead_id"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	ActivityType string      `db:"activity_type" json:"activity_type"`
	Detail       *string     `db:"detail" json:"detail"`
}

func (q *Queries) CreateLeadActivity(ctx context.Context, arg CreateLeadActivityParams) (LeadActivity, error) {
	row := q.db.QueryRow(ctx, createLeadActivity,
		arg.LeadID,
		arg.UserID,
		arg.ActivityType,
		arg.Detail,
	)
	var i LeadActivity
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.UserID,
		&i.ActivityType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const createLeadEmail = `-- name: CreateLeadEmail :one
INSERT INTO lead_emails (lead_id, email, context) VALUES ($1, $2, $3) RETURNING id, lead_id, email, context, created_at
`

type CreateLeadEmailParams struct {
	LeadID  uuid.UUID `db:"lead_id" json:"lead_id"`
	Email   string    `db:"email" json:"email"`
	Context *string   `db:"context" json:"context"`
}

func (q *Queries) CreateLeadEmail(ctx context.Context, arg CreateLeadEmailParams) (LeadEmail, error) {
	row := q.db.QueryRow(ctx, createLeadEmail, arg.LeadID, arg.Email, arg.Context)
	var i LeadEmail
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Email,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const createLeadOpportunity = `-- name: CreateLeadOpportunity :one
INSERT INTO opportunities (
    company_id, contact_id, stage_id, title, currency, assigned_user_id, source, lead_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type CreateLeadOpportunityParams struct {
	CompanyID      uuid.UUID   `db:"company_id" json:"company_id"`
	ContactID      uuid.UUID   `db:"contact_id" json:"contact_id"`
	StageID        uuid.UUID   `db:"stage_id" json:"stage_id"`
	Title          string      `db:"title" json:"title"`
	Currency       string      `db:"currency" json:"currency"`
	AssignedUserID pgtype.UUID `db:"assigned_user_id" json:"assigned_user_id"`
	Source         *string     `db:"source" json:"source"`
	LeadID         pgtype.UUID `db:"lead_id" json:"lead_id"`
}

func (q *Queries) CreateLeadOpportunity(ctx context.Context, arg CreateLeadOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, createLeadOpportunity,
		arg.CompanyID,
		arg.ContactID,
		arg.StageID,
		arg.Title,
		arg.Currency,
		arg.AssignedUserID,
		arg.Source,
		arg.LeadID,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLeadPhone = `-- name: CreateLeadPhone :one
INSERT INTO lead_phones (lead_id, phone, type, country, context) VALUES ($1, $2, $3, $4, $5) RETURNING id, lead_id, phone, type, country, context, created_at
`

type CreateLeadPhoneParams struct {
	LeadID  uuid.UUID `db:"lead_id" json:"lead_id"`
	Phone   string    `db:"phone" json:"phone"`
	Type    string    `db:"type" json:"type"`
	Country *string   `db:"country" json:"country"`
	Context *string   `db:"context" json:"context"`
}

func (q *Queries) CreateLeadPhone(ctx context.Context, arg CreateLeadPhoneParams) (LeadPhone, error) {
	row := q.db.QueryRow(ctx, createLeadPhone,
		arg.LeadID,
		arg.Phone,
		arg.Type,
		arg.Country,
		arg.Context,
	)
	var i LeadPhone
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Phone,
		&i.Type,
		&i.Country,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const createLeadSocial = `-- name: CreateLeadSocial :one
INSERT INTO lead_socials (lead_id, platform, handle, url) VALUES ($1, $2, $3, $4) RETURNING id, lead_id, platform, handle, url, created_at
`

type CreateLeadSocialParams struct {
	LeadID   uuid.UUID `db:"lead_id" json:"lead_id"`
	Platform string    `db:"platform" json:"platform"`
	Handle   *string   `db:"handle" json:"handle"`
	Url      *string   `db:"url" json:"url"`
}

func (q *Queries) CreateLeadSocial(ctx context.Context, arg CreateLeadSocialParams) (LeadSocial, error) {
	row := q.db.QueryRow(ctx, createLeadSocial,
		arg.LeadID,
		arg.Platform,
		arg.Handle,
		arg.Url,
	)
	var i LeadSocial
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.Platform,
		&i.Handle,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const getLeadByID = `-- name: GetLeadByID :one
SELECT id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at FROM leads WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetLeadByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetLeadByID(ctx context.Context, arg GetLeadByIDParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadByID, arg.ID, arg.CompanyID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLeadConversionByUser = `-- name: GetLeadConversionByUser :many
SELECT
    assigned_to,
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'converted') AS converted
FROM leads
WHERE company_id = $1 AND deleted_at IS NULL AND assigned_to IS NOT NULL
GROUP BY assigned_to
`

type GetLeadConversionByUserRow struct {
	AssignedTo pgtype.UUID `db:"assigned_to" json:"assigned_to"`
	Total      int64       `db:"total" json:"total"`
	Converted  int64       `db:"converted" json:"converted"`
}

func (q *Queries) GetLeadConversionByUser(ctx context.Context, companyID uuid.UUID) ([]GetLeadConversionByUserRow, error) {
	rows, err := q.db.Query(ctx, getLeadConversionByUser, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeadConversionByUserRow{}
	for rows.Next() {
		var i GetLeadConversionByUserRow
		if err := rows.Scan(&i.AssignedTo, &i.Total, &i.Converted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeadForUpdate = `-- name: GetLeadForUpdate :one
SELECT id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at FROM leads WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL FOR UPDATE
`

type GetLeadForUpdateParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetLeadForUpdate(ctx context.Context, arg GetLeadForUpdateParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadForUpdate, arg.ID, arg.CompanyID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLeadMetrics = `-- name: GetLeadMetrics :one
SELECT
    COUNT(*) FILTER (WHERE created_at >= date_trunc('month', now())) AS leads_this_month,
    COUNT(*) FILTER (WHERE status = 'converted') AS total_converted,
    COUNT(*) AS total_leads,
    COUNT(*) FILTER (WHERE status NOT IN ('rejected','converted')) AS active_leads
FROM leads
WHERE company_id = $1 AND deleted_at IS NULL
`

type GetLeadMetricsRow struct {
	LeadsThisMonth int64 `db:"leads_this_month" json:"leads_this_month"`
	TotalConverted int64 `db:"total_converted" json:"total_converted"`
	TotalLeads     int64 `db:"total_leads" json:"total_leads"`
	ActiveLeads    int64 `db:"active_leads" json:"active_leads"`
}

func (q *Queries) GetLeadMetrics(ctx context.Context, companyID uuid.UUID) (GetLeadMetricsRow, error) {
	row := q.db.QueryRow(ctx, getLeadMetrics, companyID)
	var i GetLeadMetricsRow
	err := row.Scan(
		&i.LeadsThisMonth,
		&i.TotalConverted,
		&i.TotalLeads,
		&i.ActiveLeads,
	)
	return i, err
}

const listLeadActivities = `-- name: ListLeadActivities :many
SELECT id, lead_id, user_id, activity_type, detail, created_at FROM lead_activities WHERE lead_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListLeadActivities(ctx context.Context, leadID uuid.UUID) ([]LeadActivity, error) {
	rows, err := q.db.Query(ctx, listLeadActivities, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadActivity{}
	for rows.Next() {
		var i LeadActivity
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.UserID,
			&i.ActivityType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadEmails = `-- name: ListLeadEmails :many
SELECT id, lead_id, email, context, created_at FROM lead_emails WHERE lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListLeadEmails(ctx context.Context, leadID uuid.UUID) ([]LeadEmail, error) {
	rows, err := q.db.Query(ctx, listLeadEmails, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadEmail{}
	for rows.Next() {
		var i LeadEmail
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.Email,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadPhones = `-- name: ListLeadPhones :many
SELECT id, lead_id, phone, type, country, context, created_at FROM lead_phones WHERE lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListLeadPhones(ctx context.Context, leadID uuid.UUID) ([]LeadPhone, error) {
	rows, err := q.db.Query(ctx, listLeadPhones, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadPhone{}
	for rows.Next() {
		var i LeadPhone
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.Phone,
			&i.Type,
			&i.Country,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadSocials = `-- name: ListLeadSocials :many
SELECT id, lead_id, platform, handle, url, created_at FROM lead_socials WHERE lead_id = $1 ORDER BY created_at
`

func (q *Queries) ListLeadSocials(ctx context.Context, leadID uuid.UUID) ([]LeadSocial, error) {
	rows, err := q.db.Query(ctx, listLeadSocials, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadSocial{}
	for rows.Next() {
		var i LeadSocial
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.Platform,
			&i.Handle,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeads = `-- name: ListLeads :many
SELECT id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at FROM leads
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR assigned_to = $5)
  AND ($6::text IS NULL OR industry = $6)
  AND ($7::date IS NULL OR created_at::date >= $7)
  AND ($8::date IS NULL OR created_at::date <= $8)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadsParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
	Status     *string     `db:"status" json:"status"`
	AssignedTo pgtype.UUID `db:"assigned_to" json:"assigned_to"`
	Industry   *string     `db:"industry" json:"industry"`
	FromDate   pgtype.Date `db:"from_date" json:"from_date"`
	ToDate     pgtype.Date `db:"to_date" json:"to_date"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AssignedTo,
		arg.Industry,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyName,
			&i.Description,
			&i.WhatTheyDo,
			&i.SourceUrl,
			&i.Website,
			&i.Industry,
			&i.ApproximateSize,
			&i.City,
			&i.Country,
			&i.Language,
			&i.AssignedTo,
			&i.Status,
			&i.RejectionReason,
			&i.FollowUpDate,
			&i.ScrapingJobID,
			&i.ConvertedContactID,
			&i.LlmExtractionFailed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLeadExtractionFailed = `-- name: MarkLeadExtractionFailed :exec
UPDATE leads SET llm_extraction_failed = true, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type MarkLeadExtractionFailedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) MarkLeadExtractionFailed(ctx context.Context, arg MarkLeadExtractionFailedParams) error {
	_, err := q.db.Exec(ctx, markLeadExtractionFailed, arg.ID, arg.CompanyID)
	return err
}

const softDeleteLead = `-- name: SoftDeleteLead :exec
UPDATE leads SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLeadParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error {
	_, err := q.db.Exec(ctx, softDeleteLead, arg.ID, arg.CompanyID)
	return err
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads SET
    company_name = $3, description = $4, what_they_do = $5, website = $6,
    industry = $7, approximate_size = $8, city = $9, country = $10,
    language = $11, follow_up_date = $12, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at
`

type UpdateLeadParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	CompanyID       uuid.UUID   `db:"company_id" json:"company_id"`
	CompanyName     string      `db:"company_name" json:"company_name"`
	Description     *string     `db:"description" json:"description"`
	WhatTheyDo      *string     `db:"what_they_do" json:"what_they_do"`
	Website         *string     `db:"website" json:"website"`
	Industry        *string     `db:"industry" json:"industry"`
	ApproximateSize *string     `db:"approximate_size" json:"approximate_size"`
	City            *string     `db:"city" json:"city"`
	Country         *string     `db:"country" json:"country"`
	Language        *string     `db:"language" json:"language"`
	FollowUpDate    pgtype.Date `db:"follow_up_date" json:"follow_up_date"`
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.ID,
		arg.CompanyID,
		arg.CompanyName,
		arg.Description,
		arg.WhatTheyDo,
		arg.Website,
		arg.Industry,
		arg.ApproximateSize,
		arg.City,
		arg.Country,
		arg.Language,
		arg.FollowUpDate,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads SET status = $3, rejection_reason = $4, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, company_name, description, what_they_do, source_url, website, industry, approximate_size, city, country, language, assigned_to, status, rejection_reason, follow_up_date, scraping_job_id, converted_contact_id, llm_extraction_failed, created_at, updated_at, deleted_at
`

type UpdateLeadStatusParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	CompanyID       uuid.UUID `db:"company_id" json:"company_id"`
	Status          string    `db:"status" json:"status"`
	RejectionReason *string   `db:"rejection_reason" json:"rejection_reason"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.RejectionReason,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.Description,
		&i.WhatTheyDo,
		&i.SourceUrl,
		&i.Website,
		&i.Industry,
		&i.ApproximateSize,
		&i.City,
		&i.Country,
		&i.Language,
		&i.AssignedTo,
		&i.Status,
		&i.RejectionReason,
		&i.FollowUpDate,
		&i.ScrapingJobID,
		&i.ConvertedContactID,
		&i.LlmExtractionFailed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
