// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	CompanyID  uuid.UUID          `db:"company_id" json:"company_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202606 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202607 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202608 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202609 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type BankAccountsFinance struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	BankName      string             `db:"bank_name" json:"bank_name"`
	AccountNumber *string            `db:"account_number" json:"account_number"`
	Cbu           *string            `db:"cbu" json:"cbu"`
	Alias         *string            `db:"alias" json:"alias"`
	Currency      string             `db:"currency" json:"currency"`
	AccountHolder *string            `db:"account_holder" json:"account_holder"`
	BookBalance   pgtype.Numeric     `db:"book_balance" json:"book_balance"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type BankMovement struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	BankAccountID uuid.UUID          `db:"bank_account_id" json:"bank_account_id"`
	Type          string             `db:"type" json:"type"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      string             `db:"currency" json:"currency"`
	Description   *string            `db:"description" json:"description"`
	ReferenceType *string            `db:"reference_type" json:"reference_type"`
	ReferenceID   pgtype.UUID        `db:"reference_id" json:"reference_id"`
	Reconciled    bool               `db:"reconciled" json:"reconciled"`
	ReconciledAt  pgtype.Timestamptz `db:"reconciled_at" json:"reconciled_at"`
	ValueDate     pgtype.Date        `db:"value_date" json:"value_date"`
	CreatedBy     uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CalendarEvent struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	CompanyID            uuid.UUID          `db:"company_id" json:"company_id"`
	Title                string             `db:"title" json:"title"`
	EventTypeID          pgtype.UUID        `db:"event_type_id" json:"event_type_id"`
	ContactID            pgtype.UUID        `db:"contact_id" json:"contact_id"`
	AssignedUserID       uuid.UUID          `db:"assigned_user_id" json:"assigned_user_id"`
	StartsAt             pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt               pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
	AllDay               bool               `db:"all_day" json:"all_day"`
	Status               string             `db:"status" json:"status"`
	Notes                *string            `db:"notes" json:"notes"`
	RelatedTaskID        pgtype.UUID        `db:"related_task_id" json:"related_task_id"`
	RelatedOpportunityID pgtype.UUID        `db:"related_opportunity_id" json:"related_opportunity_id"`
	RelatedProjectID     pgtype.UUID        `db:"related_project_id" json:"related_project_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CalendarEventType struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	Color     string             `db:"color" json:"color"`
	Icon      *string            `db:"icon" json:"icon"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CashMovement struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	CompanyID      uuid.UUID          `db:"company_id" json:"company_id"`
	CashRegisterID uuid.UUID          `db:"cash_register_id" json:"cash_register_id"`
	SessionID      pgtype.UUID        `db:"session_id" json:"session_id"`
	Type           string             `db:"type" json:"type"`
	Amount         pgtype.Numeric     `db:"amount" json:"amount"`
	Currency       string             `db:"currency" json:"currency"`
	Description    *string            `db:"description" json:"description"`
	ReferenceType  *string            `db:"reference_type" json:"reference_type"`
	ReferenceID    pgtype.UUID        `db:"reference_id" json:"reference_id"`
	CreatedBy      uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CashRegister struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	Name          string             `db:"name" json:"name"`
	Currency      string             `db:"currency" json:"currency"`
	ResponsibleID pgtype.UUID        `db:"responsible_id" json:"responsible_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CashRegisterSession struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	CashRegisterID           uuid.UUID          `db:"cash_register_id" json:"cash_register_id"`
	OpenedBy                 uuid.UUID          `db:"opened_by" json:"opened_by"`
	OpenedAt                 pgtype.Timestamptz `db:"opened_at" json:"opened_at"`
	ClosedBy                 pgtype.UUID        `db:"closed_by" json:"closed_by"`
	ClosedAt                 pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	OpeningBalance           pgtype.Numeric     `db:"opening_balance" json:"opening_balance"`
	DeclaredClosingBalance   pgtype.Numeric     `db:"declared_closing_balance" json:"declared_closing_balance"`
	CalculatedClosingBalance pgtype.Numeric     `db:"calculated_closing_balance" json:"calculated_closing_balance"`
	Difference               pgtype.Numeric     `db:"difference" json:"difference"`
	Status                   string             `db:"status" json:"status"`
}

type Company struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	LegalName         string             `db:"legal_name" json:"legal_name"`
	FantasyName       string             `db:"fantasy_name" json:"fantasy_name"`
	Cuit              *string            `db:"cuit" json:"cuit"`
	VatCondition      *string            `db:"vat_condition" json:"vat_condition"`
	FiscalAddress     *string            `db:"fiscal_address" json:"fiscal_address"`
	City              *string            `db:"city" json:"city"`
	Province          *string            `db:"province" json:"province"`
	PostalCode        *string            `db:"postal_code" json:"postal_code"`
	LogoKey           *string            `db:"logo_key" json:"logo_key"`
	GrossIncome       *string            `db:"gross_income" json:"gross_income"`
	ActivityStartDate pgtype.Date        `db:"activity_start_date" json:"activity_start_date"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Contact struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	CompanyID                 uuid.UUID          `db:"company_id" json:"company_id"`
	Kind                      []string           `db:"kind" json:"kind"`
	FantasyName               string             `db:"fantasy_name" json:"fantasy_name"`
	LegalName                 *string            `db:"legal_name" json:"legal_name"`
	CuitCuil                  *string            `db:"cuit_cuil" json:"cuit_cuil"`
	VatCondition              *string            `db:"vat_condition" json:"vat_condition"`
	FiscalAddress             *string            `db:"fiscal_address" json:"fiscal_address"`
	City                      *string            `db:"city" json:"city"`
	Province                  *string            `db:"province" json:"province"`
	PostalCode                *string            `db:"postal_code" json:"postal_code"`
	Email                     *string            `db:"email" json:"email"`
	Phone                     *string            `db:"phone" json:"phone"`
	Website                   *string            `db:"website" json:"website"`
	Industry                  *string            `db:"industry" json:"industry"`
	Source                    *string            `db:"source" json:"source"`
	DefaultPaymentConditionID pgtype.UUID        `db:"default_payment_condition_id" json:"default_payment_condition_id"`
	CreditLimit               pgtype.Numeric     `db:"credit_limit" json:"credit_limit"`
	UsualDiscountPct          pgtype.Numeric     `db:"usual_discount_pct" json:"usual_discount_pct"`
	AssignedUserID            pgtype.UUID        `db:"assigned_user_id" json:"assigned_user_id"`
	LifecycleStatus           string             `db:"lifecycle_status" json:"lifecycle_status"`
	SearchVector              interface{}        `db:"search_vector" json:"search_vector"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	PaymentConditionID        pgtype.UUID        `db:"payment_condition_id" json:"payment_condition_id"`
}

type ContactBalance struct {
	ContactID uuid.UUID          `db:"contact_id" json:"contact_id"`
	Currency  string             `db:"currency" json:"currency"`
	Balance   pgtype.Numeric     `db:"balance" json:"balance"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContactBankAccount struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ContactID     uuid.UUID          `db:"contact_id" json:"contact_id"`
	CbuCvu        *string            `db:"cbu_cvu" json:"cbu_cvu"`
	Alias         *string            `db:"alias" json:"alias"`
	BankName      *string            `db:"bank_name" json:"bank_name"`
	AccountHolder *string            `db:"account_holder" json:"account_holder"`
	Currency      string             `db:"currency" json:"currency"`
	EncryptedCbu  []byte             `db:"encrypted_cbu" json:"encrypted_cbu"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ContactComment struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ContactID uuid.UUID          `db:"contact_id" json:"contact_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Body      string             `db:"body" json:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ContactNote struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ContactID uuid.UUID          `db:"contact_id" json:"contact_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Body      string             `db:"body" json:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ContactPerson struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ContactID uuid.UUID          `db:"contact_id" json:"contact_id"`
	Name      string             `db:"name" json:"name"`
	Role      *string            `db:"role" json:"role"`
	Email     *string            `db:"email" json:"email"`
	Phone     *string            `db:"phone" json:"phone"`
	Notes     *string            `db:"notes" json:"notes"`
	Birthday  pgtype.Date        `db:"birthday" json:"birthday"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ContactTag struct {
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
	TagID     uuid.UUID `db:"tag_id" json:"tag_id"`
}

type Currency struct {
	Code   string `db:"code" json:"code"`
	Name   string `db:"name" json:"name"`
	Symbol string `db:"symbol" json:"symbol"`
}

type Document struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	FileName    string             `db:"file_name" json:"file_name"`
	ContentType string             `db:"content_type" json:"content_type"`
	SizeBytes   int64              `db:"size_bytes" json:"size_bytes"`
	StorageKey  string             `db:"storage_key" json:"storage_key"`
	UploadedBy  uuid.UUID          `db:"uploaded_by" json:"uploaded_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ExchangeRate struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	CompanyID    uuid.UUID          `db:"company_id" json:"company_id"`
	FromCurrency string             `db:"from_currency" json:"from_currency"`
	ToCurrency   string             `db:"to_currency" json:"to_currency"`
	Rate         pgtype.Numeric     `db:"rate" json:"rate"`
	Date         pgtype.Date        `db:"date" json:"date"`
	Source       *string            `db:"source" json:"source"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Expense struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CompanyID           uuid.UUID          `db:"company_id" json:"company_id"`
	Date                pgtype.Date        `db:"date" json:"date"`
	CategoryID          uuid.UUID          `db:"category_id" json:"category_id"`
	Description         string             `db:"description" json:"description"`
	Amount              pgtype.Numeric     `db:"amount" json:"amount"`
	Currency            *string            `db:"currency" json:"currency"`
	PaidByUserID        pgtype.UUID        `db:"paid_by_user_id" json:"paid_by_user_id"`
	PaidByCashID        pgtype.UUID        `db:"paid_by_cash_id" json:"paid_by_cash_id"`
	PaidByBankID        pgtype.UUID        `db:"paid_by_bank_id" json:"paid_by_bank_id"`
	FileKey             *string            `db:"file_key" json:"file_key"`
	ProjectID           pgtype.UUID        `db:"project_id" json:"project_id"`
	Status              string             `db:"status" json:"status"`
	ApproverID          pgtype.UUID        `db:"approver_id" json:"approver_id"`
	ApprovedAt          pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ReimbursementStatus string             `db:"reimbursement_status" json:"reimbursement_status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ExpenseCategory struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Industry struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type InvoiceItem struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	InvoiceID   uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	Description string         `db:"description" json:"description"`
	Quantity    pgtype.Numeric `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	DiscountPct pgtype.Numeric `db:"discount_pct" json:"discount_pct"`
	VatRateID   pgtype.UUID    `db:"vat_rate_id" json:"vat_rate_id"`
	LineNet     pgtype.Numeric `db:"line_net" json:"line_net"`
	LineTax     pgtype.Numeric `db:"line_tax" json:"line_tax"`
	LineTotal   pgtype.Numeric `db:"line_total" json:"line_total"`
	OrderPos    *int16         `db:"order_pos" json:"order_pos"`
}

type InvoiceTax struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	InvoiceID  uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	TaxType    string         `db:"tax_type" json:"tax_type"`
	RatePct    pgtype.Numeric `db:"rate_pct" json:"rate_pct"`
	BaseAmount pgtype.Numeric `db:"base_amount" json:"base_amount"`
	TaxAmount  pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
}

type InvoicesIssued struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	CompanyID          uuid.UUID          `db:"company_id" json:"company_id"`
	IdempotencyKey     uuid.UUID          `db:"idempotency_key" json:"idempotency_key"`
	InvoiceType        string             `db:"invoice_type" json:"invoice_type"`
	SalePoint          int16              `db:"sale_point" json:"sale_point"`
	Number             *int32             `db:"number" json:"number"`
	ContactID          uuid.UUID          `db:"contact_id" json:"contact_id"`
	IssueDate          pgtype.Date        `db:"issue_date" json:"issue_date"`
	DueDate            pgtype.Date        `db:"due_date" json:"due_date"`
	PaymentConditionID pgtype.UUID        `db:"payment_condition_id" json:"payment_condition_id"`
	Currency           string             `db:"currency" json:"currency"`
	ExchangeRate       pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate   pgtype.Date        `db:"exchange_rate_date" json:"exchange_rate_date"`
	Status             string             `db:"status" json:"status"`
	NetAmount          pgtype.Numeric     `db:"net_amount" json:"net_amount"`
	TaxAmount          pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	TotalAmount        pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	PaidAmount         pgtype.Numeric     `db:"paid_amount" json:"paid_amount"`
	ProjectID          pgtype.UUID        `db:"project_id" json:"project_id"`
	QuoteID            pgtype.UUID        `db:"quote_id" json:"quote_id"`
	Notes              *string            `db:"notes" json:"notes"`
	PdfKey             *string            `db:"pdf_key" json:"pdf_key"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type InvoicesReceived struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	CompanyID        uuid.UUID          `db:"company_id" json:"company_id"`
	SupplierID       uuid.UUID          `db:"supplier_id" json:"supplier_id"`
	InvoiceType      *string            `db:"invoice_type" json:"invoice_type"`
	SalePoint        *int16             `db:"sale_point" json:"sale_point"`
	Number           *int32             `db:"number" json:"number"`
	IssueDate        pgtype.Date        `db:"issue_date" json:"issue_date"`
	DueDate          pgtype.Date        `db:"due_date" json:"due_date"`
	Currency         *string            `db:"currency" json:"currency"`
	ExchangeRate     pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	ExchangeRateDate pgtype.Date        `db:"exchange_rate_date" json:"exchange_rate_date"`
	NetAmount        pgtype.Numeric     `db:"net_amount" json:"net_amount"`
	TaxAmount        pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	TotalAmount      pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	PaidAmount       pgtype.Numeric     `db:"paid_amount" json:"paid_amount"`
	Status           string             `db:"status" json:"status"`
	ProjectID        pgtype.UUID        `db:"project_id" json:"project_id"`
	FileKey          *string            `db:"file_key" json:"file_key"`
	Notes            *string            `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Lead struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CompanyID           uuid.UUID          `db:"company_id" json:"company_id"`
	CompanyName         string             `db:"company_name" json:"company_name"`
	Description         *string            `db:"description" json:"description"`
	WhatTheyDo          *string            `db:"what_they_do" json:"what_they_do"`
	SourceUrl           *string            `db:"source_url" json:"source_url"`
	Website             *string            `db:"website" json:"website"`
	Industry            *string            `db:"industry" json:"industry"`
	ApproximateSize     *string            `db:"approximate_size" json:"approximate_size"`
	City                *string            `db:"city" json:"city"`
	Country             *string            `db:"country" json:"country"`
	Language            *string            `db:"language" json:"language"`
	AssignedTo          pgtype.UUID        `db:"assigned_to" json:"assigned_to"`
	Status              string             `db:"status" json:"status"`
	RejectionReason     *string            `db:"rejection_reason" json:"rejection_reason"`
	FollowUpDate        pgtype.Date        `db:"follow_up_date" json:"follow_up_date"`
	ScrapingJobID       pgtype.UUID        `db:"scraping_job_id" json:"scraping_job_id"`
	ConvertedContactID  pgtype.UUID        `db:"converted_contact_id" json:"converted_contact_id"`
	LlmExtractionFailed bool               `db:"llm_extraction_failed" json:"llm_extraction_failed"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type LeadActivity struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	LeadID       uuid.UUID          `db:"lead_id" json:"lead_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	ActivityType string             `db:"activity_type" json:"activity_type"`
	Detail       *string            `db:"detail" json:"detail"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LeadEmail struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LeadID    uuid.UUID          `db:"lead_id" json:"lead_id"`
	Email     string             `db:"email" json:"email"`
	Context   *string            `db:"context" json:"context"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LeadPhone struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LeadID    uuid.UUID          `db:"lead_id" json:"lead_id"`
	Phone     string             `db:"phone" json:"phone"`
	Type      string             `db:"type" json:"type"`
	Country   *string            `db:"country" json:"country"`
	Context   *string            `db:"context" json:"context"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LeadSocial struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	LeadID    uuid.UUID          `db:"lead_id" json:"lead_id"`
	Platform  string             `db:"platform" json:"platform"`
	Handle    *string            `db:"handle" json:"handle"`
	Url       *string            `db:"url" json:"url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type LostReason struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Opportunity struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	CompanyID         uuid.UUID          `db:"company_id" json:"company_id"`
	ContactID         uuid.UUID          `db:"contact_id" json:"contact_id"`
	StageID           uuid.UUID          `db:"stage_id" json:"stage_id"`
	Title             string             `db:"title" json:"title"`
	Amount            pgtype.Numeric     `db:"amount" json:"amount"`
	Currency          string             `db:"currency" json:"currency"`
	ProbabilityPct    pgtype.Numeric     `db:"probability_pct" json:"probability_pct"`
	ExpectedCloseDate pgtype.Date        `db:"expected_close_date" json:"expected_close_date"`
	AssignedUserID    pgtype.UUID        `db:"assigned_user_id" json:"assigned_user_id"`
	Source            *string            `db:"source" json:"source"`
	LostReasonID      pgtype.UUID        `db:"lost_reason_id" json:"lost_reason_id"`
	LostNotes         *string            `db:"lost_notes" json:"lost_notes"`
	LeadID            pgtype.UUID        `db:"lead_id" json:"lead_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PaymentCondition struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	Days      int32              `db:"days" json:"days"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PaymentObligation struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	CompanyID      uuid.UUID          `db:"company_id" json:"company_id"`
	SourceType     string             `db:"source_type" json:"source_type"`
	SourceID       pgtype.UUID        `db:"source_id" json:"source_id"`
	Description    string             `db:"description" json:"description"`
	Amount         pgtype.Numeric     `db:"amount" json:"amount"`
	Currency       *string            `db:"currency" json:"currency"`
	DueDate        pgtype.Date        `db:"due_date" json:"due_date"`
	Status         string             `db:"status" json:"status"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	PaymentOrderID pgtype.UUID        `db:"payment_order_id" json:"payment_order_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PaymentOrder struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	CompanyID      uuid.UUID          `db:"company_id" json:"company_id"`
	IdempotencyKey uuid.UUID          `db:"idempotency_key" json:"idempotency_key"`
	SupplierID     uuid.UUID          `db:"supplier_id" json:"supplier_id"`
	Date           pgtype.Date        `db:"date" json:"date"`
	Number         int32              `db:"number" json:"number"`
	Currency       string             `db:"currency" json:"currency"`
	ExchangeRate   pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	TotalAmount    pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	Notes          *string            `db:"notes" json:"notes"`
	PdfKey         *string            `db:"pdf_key" json:"pdf_key"`
	CreatedBy      uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PaymentOrderApplication struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	PaymentOrderID    uuid.UUID      `db:"payment_order_id" json:"payment_order_id"`
	InvoiceReceivedID uuid.UUID      `db:"invoice_received_id" json:"invoice_received_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
}

type PaymentOrderMethod struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	PaymentOrderID uuid.UUID      `db:"payment_order_id" json:"payment_order_id"`
	MethodType     string         `db:"method_type" json:"method_type"`
	CashRegisterID pgtype.UUID    `db:"cash_register_id" json:"cash_register_id"`
	BankAccountID  pgtype.UUID    `db:"bank_account_id" json:"bank_account_id"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	Currency       *string        `db:"currency" json:"currency"`
	CheckNumber    *string        `db:"check_number" json:"check_number"`
	CheckDate      pgtype.Date    `db:"check_date" json:"check_date"`
}

type Permission struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Module      string    `db:"module" json:"module"`
	Action      string    `db:"action" json:"action"`
	Description *string   `db:"description" json:"description"`
}

type PipelineStage struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	OrderPos  int16              `db:"order_pos" json:"order_pos"`
	Color     string             `db:"color" json:"color"`
	IsWin     bool               `db:"is_win" json:"is_win"`
	IsLoss    bool               `db:"is_loss" json:"is_loss"`
	IsDefault bool               `db:"is_default" json:"is_default"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PostalCode struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	PostalCode  string             `db:"postal_code" json:"postal_code"`
	Locality    string             `db:"locality" json:"locality"`
	Province    string             `db:"province" json:"province"`
	PhonePrefix *string            `db:"phone_prefix" json:"phone_prefix"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	Code        *string            `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Unit        *string            `db:"unit" json:"unit"`
	UnitPrice   pgtype.Numeric     `db:"unit_price" json:"unit_price"`
	Currency    *string            `db:"currency" json:"currency"`
	Cost        pgtype.Numeric     `db:"cost" json:"cost"`
	VatRatePct  pgtype.Numeric     `db:"vat_rate_pct" json:"vat_rate_pct"`
	Category    *string            `db:"category" json:"category"`
	IsRecurring bool               `db:"is_recurring" json:"is_recurring"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Project struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	CompanyID        uuid.UUID          `db:"company_id" json:"company_id"`
	ClientID         uuid.UUID          `db:"client_id" json:"client_id"`
	Name             string             `db:"name" json:"name"`
	Description      *string            `db:"description" json:"description"`
	StartDate        pgtype.Date        `db:"start_date" json:"start_date"`
	EstimatedEndDate pgtype.Date        `db:"estimated_end_date" json:"estimated_end_date"`
	ActualEndDate    pgtype.Date        `db:"actual_end_date" json:"actual_end_date"`
	Status           string             `db:"status" json:"status"`
	ResponsibleID    pgtype.UUID        `db:"responsible_id" json:"responsible_id"`
	BudgetHours      pgtype.Numeric     `db:"budget_hours" json:"budget_hours"`
	BudgetAmount     pgtype.Numeric     `db:"budget_amount" json:"budget_amount"`
	Currency         string             `db:"currency" json:"currency"`
	OpportunityID    pgtype.UUID        `db:"opportunity_id" json:"opportunity_id"`
	QuoteID          pgtype.UUID        `db:"quote_id" json:"quote_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ProjectMember struct {
	ProjectID     uuid.UUID `db:"project_id" json:"project_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	RoleInProject *string   `db:"role_in_project" json:"role_in_project"`
}

type ProjectMilestone struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ProjectID     uuid.UUID          `db:"project_id" json:"project_id"`
	Name          string             `db:"name" json:"name"`
	Description   *string            `db:"description" json:"description"`
	Deliverables  *string            `db:"deliverables" json:"deliverables"`
	CommittedDate pgtype.Date        `db:"committed_date" json:"committed_date"`
	Status        string             `db:"status" json:"status"`
	OrderPos      *int16             `db:"order_pos" json:"order_pos"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Quote struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	Number        string             `db:"number" json:"number"`
	ContactID     uuid.UUID          `db:"contact_id" json:"contact_id"`
	OpportunityID pgtype.UUID        `db:"opportunity_id" json:"opportunity_id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	Date          pgtype.Date        `db:"date" json:"date"`
	ValidUntil    pgtype.Date        `db:"valid_until" json:"valid_until"`
	Currency      string             `db:"currency" json:"currency"`
	ExchangeRate  pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	Status        string             `db:"status" json:"status"`
	Version       int16              `db:"version" json:"version"`
	ParentID      pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Notes         *string            `db:"notes" json:"notes"`
	Subtotal      pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	TaxTotal      pgtype.Numeric     `db:"tax_total" json:"tax_total"`
	Total         pgtype.Numeric     `db:"total" json:"total"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type QuoteItem struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	QuoteID      uuid.UUID      `db:"quote_id" json:"quote_id"`
	ProductID    pgtype.UUID    `db:"product_id" json:"product_id"`
	Description  string         `db:"description" json:"description"`
	Quantity     pgtype.Numeric `db:"quantity" json:"quantity"`
	UnitPrice    pgtype.Numeric `db:"unit_price" json:"unit_price"`
	DiscountPct  pgtype.Numeric `db:"discount_pct" json:"discount_pct"`
	VatRatePct   pgtype.Numeric `db:"vat_rate_pct" json:"vat_rate_pct"`
	LineSubtotal pgtype.Numeric `db:"line_subtotal" json:"line_subtotal"`
	LineTax      pgtype.Numeric `db:"line_tax" json:"line_tax"`
	LineTotal    pgtype.Numeric `db:"line_total" json:"line_total"`
	OrderPos     *int16         `db:"order_pos" json:"order_pos"`
}

type Receipt struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CompanyID       uuid.UUID          `db:"company_id" json:"company_id"`
	IdempotencyKey  uuid.UUID          `db:"idempotency_key" json:"idempotency_key"`
	ContactID       uuid.UUID          `db:"contact_id" json:"contact_id"`
	Date            pgtype.Date        `db:"date" json:"date"`
	Number          int32              `db:"number" json:"number"`
	Currency        string             `db:"currency" json:"currency"`
	ExchangeRate    pgtype.Numeric     `db:"exchange_rate" json:"exchange_rate"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	OnAccountAmount pgtype.Numeric     `db:"on_account_amount" json:"on_account_amount"`
	Notes           *string            `db:"notes" json:"notes"`
	PdfKey          *string            `db:"pdf_key" json:"pdf_key"`
	CreatedBy       uuid.UUID          `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ReceiptInvoiceApplication struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	ReceiptID uuid.UUID      `db:"receipt_id" json:"receipt_id"`
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
}

type ReceiptPaymentMethod struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	ReceiptID      uuid.UUID      `db:"receipt_id" json:"receipt_id"`
	MethodType     string         `db:"method_type" json:"method_type"`
	CashRegisterID pgtype.UUID    `db:"cash_register_id" json:"cash_register_id"`
	BankAccountID  pgtype.UUID    `db:"bank_account_id" json:"bank_account_id"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	Currency       *string        `db:"currency" json:"currency"`
	CheckNumber    *string        `db:"check_number" json:"check_number"`
	CheckDate      pgtype.Date    `db:"check_date" json:"check_date"`
}

type RecurringPayment struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	SupplierID    pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Description   string             `db:"description" json:"description"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	Currency      *string            `db:"currency" json:"currency"`
	Frequency     string             `db:"frequency" json:"frequency"`
	DueDay        *int16             `db:"due_day" json:"due_day"`
	NextDueDate   pgtype.Date        `db:"next_due_date" json:"next_due_date"`
	PaymentMethod *string            `db:"payment_method" json:"payment_method"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	Status        string             `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	IsSystem    bool               `db:"is_system" json:"is_system"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RolePermission struct {
	RoleID          uuid.UUID `db:"role_id" json:"role_id"`
	PermissionID    uuid.UUID `db:"permission_id" json:"permission_id"`
	RestrictedToOwn bool      `db:"restricted_to_own" json:"restricted_to_own"`
}

type ScrapingJob struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	CompanyID            uuid.UUID          `db:"company_id" json:"company_id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	Query                string             `db:"query" json:"query"`
	ResultCountRequested int32              `db:"result_count_requested" json:"result_count_requested"`
	Country              *string            `db:"country" json:"country"`
	Language             *string            `db:"language" json:"language"`
	Status               string             `db:"status" json:"status"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt           pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	SearchApiCostUsd     pgtype.Numeric     `db:"search_api_cost_usd" json:"search_api_cost_usd"`
	LlmTokensInput       *int32             `db:"llm_tokens_input" json:"llm_tokens_input"`
	LlmTokensOutput      *int32             `db:"llm_tokens_output" json:"llm_tokens_output"`
	LlmCostUsd           pgtype.Numeric     `db:"llm_cost_usd" json:"llm_cost_usd"`
	TotalCostUsd         pgtype.Numeric     `db:"total_cost_usd" json:"total_cost_usd"`
	UrlsProcessed        int32              `db:"urls_processed" json:"urls_processed"`
	LeadsFound           int32              `db:"leads_found" json:"leads_found"`
	ErrorSummary         *string            `db:"error_summary" json:"error_summary"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SequenceNumber struct {
	ID           uuid.UUID `db:"id" json:"id"`
	CompanyID    uuid.UUID `db:"company_id" json:"company_id"`
	DocumentType string    `db:"document_type" json:"document_type"`
	SalePoint    int16     `db:"sale_point" json:"sale_point"`
	LastNumber   int32     `db:"last_number" json:"last_number"`
}

type Session struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	CompanyID  uuid.UUID          `db:"company_id" json:"company_id"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type Tag struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	Color     *string            `db:"color" json:"color"`
	Area      *string            `db:"area" json:"area"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Task struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	CompanyID      uuid.UUID          `db:"company_id" json:"company_id"`
	Type           string             `db:"type" json:"type"`
	Title          string             `db:"title" json:"title"`
	Description    *string            `db:"description" json:"description"`
	ContactID      pgtype.UUID        `db:"contact_id" json:"contact_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	AssigneeID     pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	ReporterID     uuid.UUID          `db:"reporter_id" json:"reporter_id"`
	Origin         *string            `db:"origin" json:"origin"`
	Status         string             `db:"status" json:"status"`
	Priority       string             `db:"priority" json:"priority"`
	DueDate        pgtype.Date        `db:"due_date" json:"due_date"`
	ParentID       pgtype.UUID        `db:"parent_id" json:"parent_id"`
	IsRecurring    bool               `db:"is_recurring" json:"is_recurring"`
	RecurrenceRule *string            `db:"recurrence_rule" json:"recurrence_rule"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ClosedAt       pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type TaskComment struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Body      string             `db:"body" json:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TaskStatusHistory struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TaskID       uuid.UUID          `db:"task_id" json:"task_id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	FromStatus   *string            `db:"from_status" json:"from_status"`
	ToStatus     *string            `db:"to_status" json:"to_status"`
	FromAssignee pgtype.UUID        `db:"from_assignee" json:"from_assignee"`
	ToAssignee   pgtype.UUID        `db:"to_assignee" json:"to_assignee"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TaskTimeEntry struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	TaskID          uuid.UUID          `db:"task_id" json:"task_id"`
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DurationMinutes *int32             `db:"duration_minutes" json:"duration_minutes"`
	Note            *string            `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TimeEntry struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CompanyID       uuid.UUID          `db:"company_id" json:"company_id"`
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	Date            pgtype.Date        `db:"date" json:"date"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DurationMinutes int32              `db:"duration_minutes" json:"duration_minutes"`
	Description     *string            `db:"description" json:"description"`
	TaskID          pgtype.UUID        `db:"task_id" json:"task_id"`
	ProjectID       pgtype.UUID        `db:"project_id" json:"project_id"`
	ContactID       pgtype.UUID        `db:"contact_id" json:"contact_id"`
	IsBillable      bool               `db:"is_billable" json:"is_billable"`
	HourlyRate      pgtype.Numeric     `db:"hourly_rate" json:"hourly_rate"`
	Currency        *string            `db:"currency" json:"currency"`
	InvoiceLineID   pgtype.UUID        `db:"invoice_line_id" json:"invoice_line_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TotpBackupCode struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash  string             `db:"code_hash" json:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CompanyID           uuid.UUID          `db:"company_id" json:"company_id"`
	Email               string             `db:"email" json:"email"`
	PasswordHash        string             `db:"password_hash" json:"password_hash"`
	FullName            string             `db:"full_name" json:"full_name"`
	IsActive            bool               `db:"is_active" json:"is_active"`
	CostRate            pgtype.Numeric     `db:"cost_rate" json:"cost_rate"`
	CostRateCurrency    *string            `db:"cost_rate_currency" json:"cost_rate_currency"`
	TotpSecretEncrypted []byte             `db:"totp_secret_encrypted" json:"totp_secret_encrypted"`
	TotpEnabled         bool               `db:"totp_enabled" json:"totp_enabled"`
	LastLoginAt         pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type UserCostRate struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CostRate      pgtype.Numeric     `db:"cost_rate" json:"cost_rate"`
	Currency      string             `db:"currency" json:"currency"`
	EffectiveFrom pgtype.Date        `db:"effective_from" json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserRole struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

type VatRate struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	Name      string             `db:"name" json:"name"`
	RatePct   pgtype.Numeric     `db:"rate_pct" json:"rate_pct"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VaultEntry struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CompanyID uuid.UUID          `db:"company_id" json:"company_id"`
	CreatedBy uuid.UUID          `db:"created_by" json:"created_by"`
	Category  string             `db:"category" json:"category"`
	Label     string             `db:"label" json:"label"`
	Username  *string            `db:"username" json:"username"`
	Secret    []byte             `db:"secret" json:"secret"`
	Url       *string            `db:"url" json:"url"`
	Notes     *string            `db:"notes" json:"notes"`
	Tags      []string           `db:"tags" json:"tags"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
