// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	CompanyID  uuid.UUID          `db:"company_id" json:"company_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202606 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202607 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202608 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type AuditLogs202609 struct {
	ID          int64              `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	EntityID    uuid.UUID          `db:"entity_id" json:"entity_id"`
	Action      string             `db:"action" json:"action"`
	BeforeState []byte             `db:"before_state" json:"before_state"`
	AfterState  []byte             `db:"after_state" json:"after_state"`
}

type Company struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	LegalName         string             `db:"legal_name" json:"legal_name"`
	FantasyName       string             `db:"fantasy_name" json:"fantasy_name"`
	Cuit              *string            `db:"cuit" json:"cuit"`
	VatCondition      *string            `db:"vat_condition" json:"vat_condition"`
	FiscalAddress     *string            `db:"fiscal_address" json:"fiscal_address"`
	City              *string            `db:"city" json:"city"`
	Province          *string            `db:"province" json:"province"`
	PostalCode        *string            `db:"postal_code" json:"postal_code"`
	LogoKey           *string            `db:"logo_key" json:"logo_key"`
	GrossIncome       *string            `db:"gross_income" json:"gross_income"`
	ActivityStartDate pgtype.Date        `db:"activity_start_date" json:"activity_start_date"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Module      string    `db:"module" json:"module"`
	Action      string    `db:"action" json:"action"`
	Description *string   `db:"description" json:"description"`
}

type Role struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	CompanyID   uuid.UUID          `db:"company_id" json:"company_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	IsSystem    bool               `db:"is_system" json:"is_system"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RolePermission struct {
	RoleID          uuid.UUID `db:"role_id" json:"role_id"`
	PermissionID    uuid.UUID `db:"permission_id" json:"permission_id"`
	RestrictedToOwn bool      `db:"restricted_to_own" json:"restricted_to_own"`
}

type Session struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	CompanyID  uuid.UUID          `db:"company_id" json:"company_id"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type TotpBackupCode struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash  string             `db:"code_hash" json:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CompanyID           uuid.UUID          `db:"company_id" json:"company_id"`
	Email               string             `db:"email" json:"email"`
	PasswordHash        string             `db:"password_hash" json:"password_hash"`
	FullName            string             `db:"full_name" json:"full_name"`
	IsActive            bool               `db:"is_active" json:"is_active"`
	CostRate            pgtype.Numeric     `db:"cost_rate" json:"cost_rate"`
	CostRateCurrency    *string            `db:"cost_rate_currency" json:"cost_rate_currency"`
	TotpSecretEncrypted []byte             `db:"totp_secret_encrypted" json:"totp_secret_encrypted"`
	TotpEnabled         bool               `db:"totp_enabled" json:"totp_enabled"`
	LastLoginAt         pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type UserCostRate struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	CostRate      pgtype.Numeric     `db:"cost_rate" json:"cost_rate"`
	Currency      string             `db:"currency" json:"currency"`
	EffectiveFrom pgtype.Date        `db:"effective_from" json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserRole struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}
