// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opportunity.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLostReason = `-- name: CreateLostReason :one
INSERT INTO lost_reasons (company_id, name) VALUES ($1, $2) RETURNING id, company_id, name, created_at
`

type CreateLostReasonParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
}

func (q *Queries) CreateLostReason(ctx context.Context, arg CreateLostReasonParams) (LostReason, error) {
	row := q.db.QueryRow(ctx, createLostReason, arg.CompanyID, arg.Name)
	var i LostReason
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createOpportunity = `-- name: CreateOpportunity :one
INSERT INTO opportunities (
    company_id, contact_id, stage_id, title, amount, currency,
    probability_pct, expected_close_date, assigned_user_id, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type CreateOpportunityParams struct {
	CompanyID         uuid.UUID      `db:"company_id" json:"company_id"`
	ContactID         uuid.UUID      `db:"contact_id" json:"contact_id"`
	StageID           uuid.UUID      `db:"stage_id" json:"stage_id"`
	Title             string         `db:"title" json:"title"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Currency          string         `db:"currency" json:"currency"`
	ProbabilityPct    pgtype.Numeric `db:"probability_pct" json:"probability_pct"`
	ExpectedCloseDate pgtype.Date    `db:"expected_close_date" json:"expected_close_date"`
	AssignedUserID    pgtype.UUID    `db:"assigned_user_id" json:"assigned_user_id"`
	Source            *string        `db:"source" json:"source"`
}

func (q *Queries) CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, createOpportunity,
		arg.CompanyID,
		arg.ContactID,
		arg.StageID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.ProbabilityPct,
		arg.ExpectedCloseDate,
		arg.AssignedUserID,
		arg.Source,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPipelineStage = `-- name: CreatePipelineStage :one
INSERT INTO pipeline_stages (company_id, name, order_pos, color, is_win, is_loss, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at
`

type CreatePipelineStageParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
	OrderPos  int16     `db:"order_pos" json:"order_pos"`
	Color     string    `db:"color" json:"color"`
	IsWin     bool      `db:"is_win" json:"is_win"`
	IsLoss    bool      `db:"is_loss" json:"is_loss"`
	IsDefault bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, createPipelineStage,
		arg.CompanyID,
		arg.Name,
		arg.OrderPos,
		arg.Color,
		arg.IsWin,
		arg.IsLoss,
		arg.IsDefault,
	)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.OrderPos,
		&i.Color,
		&i.IsWin,
		&i.IsLoss,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getLossStage = `-- name: GetLossStage :one
SELECT id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at FROM pipeline_stages WHERE company_id = $1 AND is_loss = true LIMIT 1
`

func (q *Queries) GetLossStage(ctx context.Context, companyID uuid.UUID) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, getLossStage, companyID)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.OrderPos,
		&i.Color,
		&i.IsWin,
		&i.IsLoss,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getOpportunityByID = `-- name: GetOpportunityByID :one
SELECT id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at FROM opportunities WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetOpportunityByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetOpportunityByID(ctx context.Context, arg GetOpportunityByIDParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, getOpportunityByID, arg.ID, arg.CompanyID)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPipelineStageByID = `-- name: GetPipelineStageByID :one
SELECT id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at FROM pipeline_stages WHERE id = $1 AND company_id = $2
`

type GetPipelineStageByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetPipelineStageByID(ctx context.Context, arg GetPipelineStageByIDParams) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, getPipelineStageByID, arg.ID, arg.CompanyID)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.OrderPos,
		&i.Color,
		&i.IsWin,
		&i.IsLoss,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getWinStage = `-- name: GetWinStage :one
SELECT id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at FROM pipeline_stages WHERE company_id = $1 AND is_win = true LIMIT 1
`

func (q *Queries) GetWinStage(ctx context.Context, companyID uuid.UUID) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, getWinStage, companyID)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.OrderPos,
		&i.Color,
		&i.IsWin,
		&i.IsLoss,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listLostReasons = `-- name: ListLostReasons :many
SELECT id, company_id, name, created_at FROM lost_reasons WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListLostReasons(ctx context.Context, companyID uuid.UUID) ([]LostReason, error) {
	rows, err := q.db.Query(ctx, listLostReasons, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LostReason{}
	for rows.Next() {
		var i LostReason
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at FROM opportunities
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR stage_id = $2)
  AND ($3::uuid IS NULL OR assigned_user_id = $3)
  AND ($4::uuid IS NULL OR contact_id = $4)
ORDER BY created_at DESC
`

type ListOpportunitiesParams struct {
	CompanyID      uuid.UUID   `db:"company_id" json:"company_id"`
	StageID        pgtype.UUID `db:"stage_id" json:"stage_id"`
	AssignedUserID pgtype.UUID `db:"assigned_user_id" json:"assigned_user_id"`
	ContactID      pgtype.UUID `db:"contact_id" json:"contact_id"`
}

func (q *Queries) ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error) {
	rows, err := q.db.Query(ctx, listOpportunities,
		arg.CompanyID,
		arg.StageID,
		arg.AssignedUserID,
		arg.ContactID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opportunity{}
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ContactID,
			&i.StageID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.ProbabilityPct,
			&i.ExpectedCloseDate,
			&i.AssignedUserID,
			&i.Source,
			&i.LostReasonID,
			&i.LostNotes,
			&i.LeadID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunitiesForForecast = `-- name: ListOpportunitiesForForecast :many
SELECT id, amount, probability_pct, currency FROM opportunities
WHERE company_id = $1 AND deleted_at IS NULL
  AND amount IS NOT NULL AND probability_pct IS NOT NULL
`

type ListOpportunitiesForForecastRow struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Amount         pgtype.Numeric `db:"amount" json:"amount"`
	ProbabilityPct pgtype.Numeric `db:"probability_pct" json:"probability_pct"`
	Currency       string         `db:"currency" json:"currency"`
}

func (q *Queries) ListOpportunitiesForForecast(ctx context.Context, companyID uuid.UUID) ([]ListOpportunitiesForForecastRow, error) {
	rows, err := q.db.Query(ctx, listOpportunitiesForForecast, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpportunitiesForForecastRow{}
	for rows.Next() {
		var i ListOpportunitiesForForecastRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.ProbabilityPct,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineStages = `-- name: ListPipelineStages :many
SELECT id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at FROM pipeline_stages WHERE company_id = $1 ORDER BY order_pos
`

func (q *Queries) ListPipelineStages(ctx context.Context, companyID uuid.UUID) ([]PipelineStage, error) {
	rows, err := q.db.Query(ctx, listPipelineStages, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStage{}
	for rows.Next() {
		var i PipelineStage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.OrderPos,
			&i.Color,
			&i.IsWin,
			&i.IsLoss,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loseOpportunity = `-- name: LoseOpportunity :one
UPDATE opportunities SET
    stage_id = $3, lost_reason_id = $4, lost_notes = $5, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type LoseOpportunityParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	CompanyID    uuid.UUID   `db:"company_id" json:"company_id"`
	StageID      uuid.UUID   `db:"stage_id" json:"stage_id"`
	LostReasonID pgtype.UUID `db:"lost_reason_id" json:"lost_reason_id"`
	LostNotes    *string     `db:"lost_notes" json:"lost_notes"`
}

func (q *Queries) LoseOpportunity(ctx context.Context, arg LoseOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, loseOpportunity,
		arg.ID,
		arg.CompanyID,
		arg.StageID,
		arg.LostReasonID,
		arg.LostNotes,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const moveOpportunityStage = `-- name: MoveOpportunityStage :one
UPDATE opportunities SET stage_id = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type MoveOpportunityStageParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	StageID   uuid.UUID `db:"stage_id" json:"stage_id"`
}

func (q *Queries) MoveOpportunityStage(ctx context.Context, arg MoveOpportunityStageParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, moveOpportunityStage, arg.ID, arg.CompanyID, arg.StageID)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOpportunity = `-- name: SoftDeleteOpportunity :exec
UPDATE opportunities SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteOpportunityParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteOpportunity(ctx context.Context, arg SoftDeleteOpportunityParams) error {
	_, err := q.db.Exec(ctx, softDeleteOpportunity, arg.ID, arg.CompanyID)
	return err
}

const updateOpportunity = `-- name: UpdateOpportunity :one
UPDATE opportunities SET
    contact_id = $3, stage_id = $4, title = $5, amount = $6, currency = $7,
    probability_pct = $8, expected_close_date = $9, assigned_user_id = $10,
    source = $11, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type UpdateOpportunityParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	CompanyID         uuid.UUID      `db:"company_id" json:"company_id"`
	ContactID         uuid.UUID      `db:"contact_id" json:"contact_id"`
	StageID           uuid.UUID      `db:"stage_id" json:"stage_id"`
	Title             string         `db:"title" json:"title"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Currency          string         `db:"currency" json:"currency"`
	ProbabilityPct    pgtype.Numeric `db:"probability_pct" json:"probability_pct"`
	ExpectedCloseDate pgtype.Date    `db:"expected_close_date" json:"expected_close_date"`
	AssignedUserID    pgtype.UUID    `db:"assigned_user_id" json:"assigned_user_id"`
	Source            *string        `db:"source" json:"source"`
}

func (q *Queries) UpdateOpportunity(ctx context.Context, arg UpdateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, updateOpportunity,
		arg.ID,
		arg.CompanyID,
		arg.ContactID,
		arg.StageID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.ProbabilityPct,
		arg.ExpectedCloseDate,
		arg.AssignedUserID,
		arg.Source,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePipelineStage = `-- name: UpdatePipelineStage :one
UPDATE pipeline_stages SET name = $3, order_pos = $4, color = $5, is_win = $6, is_loss = $7, is_default = $8
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, order_pos, color, is_win, is_loss, is_default, created_at
`

type UpdatePipelineStageParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Name      string    `db:"name" json:"name"`
	OrderPos  int16     `db:"order_pos" json:"order_pos"`
	Color     string    `db:"color" json:"color"`
	IsWin     bool      `db:"is_win" json:"is_win"`
	IsLoss    bool      `db:"is_loss" json:"is_loss"`
	IsDefault bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) (PipelineStage, error) {
	row := q.db.QueryRow(ctx, updatePipelineStage,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.OrderPos,
		arg.Color,
		arg.IsWin,
		arg.IsLoss,
		arg.IsDefault,
	)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.OrderPos,
		&i.Color,
		&i.IsWin,
		&i.IsLoss,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const winOpportunity = `-- name: WinOpportunity :one
UPDATE opportunities SET stage_id = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, contact_id, stage_id, title, amount, currency, probability_pct, expected_close_date, assigned_user_id, source, lost_reason_id, lost_notes, lead_id, created_at, updated_at, deleted_at
`

type WinOpportunityParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	StageID   uuid.UUID `db:"stage_id" json:"stage_id"`
}

func (q *Queries) WinOpportunity(ctx context.Context, arg WinOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, winOpportunity, arg.ID, arg.CompanyID, arg.StageID)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ContactID,
		&i.StageID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.ProbabilityPct,
		&i.ExpectedCloseDate,
		&i.AssignedUserID,
		&i.Source,
		&i.LostReasonID,
		&i.LostNotes,
		&i.LeadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
