// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postal_code.sql

package sqlcgen

import (
	"context"
)

const countPostalCodes = `-- name: CountPostalCodes :one
SELECT count(*) FROM postal_codes
`

func (q *Queries) CountPostalCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPostalCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lookupPostalCode = `-- name: LookupPostalCode :many

SELECT postal_code, locality, province, phone_prefix
FROM postal_codes
WHERE postal_code = $1
ORDER BY locality
LIMIT 50
`

type LookupPostalCodeRow struct {
	PostalCode  string  `db:"postal_code" json:"postal_code"`
	Locality    string  `db:"locality" json:"locality"`
	Province    string  `db:"province" json:"province"`
	PhonePrefix *string `db:"phone_prefix" json:"phone_prefix"`
}

// Postal code reference lookups for sqlc generation.
func (q *Queries) LookupPostalCode(ctx context.Context, postalCode string) ([]LookupPostalCodeRow, error) {
	rows, err := q.db.Query(ctx, lookupPostalCode, postalCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupPostalCodeRow{}
	for rows.Next() {
		var i LookupPostalCodeRow
		if err := rows.Scan(
			&i.PostalCode,
			&i.Locality,
			&i.Province,
			&i.PhonePrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
