// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (company_id, code, name, description, unit, unit_price, currency, cost, vat_rate_pct, category, is_recurring, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, company_id, code, name, description, unit, unit_price, currency, cost, vat_rate_pct, category, is_recurring, is_active, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CompanyID   uuid.UUID      `db:"company_id" json:"company_id"`
	Code        *string        `db:"code" json:"code"`
	Name        string         `db:"name" json:"name"`
	Description *string        `db:"description" json:"description"`
	Unit        *string        `db:"unit" json:"unit"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	Currency    *string        `db:"currency" json:"currency"`
	Cost        pgtype.Numeric `db:"cost" json:"cost"`
	VatRatePct  pgtype.Numeric `db:"vat_rate_pct" json:"vat_rate_pct"`
	Category    *string        `db:"category" json:"category"`
	IsRecurring bool           `db:"is_recurring" json:"is_recurring"`
	IsActive    bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.UnitPrice,
		arg.Currency,
		arg.Cost,
		arg.VatRatePct,
		arg.Category,
		arg.IsRecurring,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPrice,
		&i.Currency,
		&i.Cost,
		&i.VatRatePct,
		&i.Category,
		&i.IsRecurring,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, company_id, code, name, description, unit, unit_price, currency, cost, vat_rate_pct, category, is_recurring, is_active, created_at, updated_at, deleted_at FROM products WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetProductByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.CompanyID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPrice,
		&i.Currency,
		&i.Cost,
		&i.VatRatePct,
		&i.Category,
		&i.IsRecurring,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, company_id, code, name, description, unit, unit_price, currency, cost, vat_rate_pct, category, is_recurring, is_active, created_at, updated_at, deleted_at FROM products
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2)
  AND ($3::text = '' OR category = $3)
ORDER BY name
`

type ListProductsParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Column2   bool      `db:"column_2" json:"column_2"`
	Column3   string    `db:"column_3" json:"column_3"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.CompanyID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.UnitPrice,
			&i.Currency,
			&i.Cost,
			&i.VatRatePct,
			&i.Category,
			&i.IsRecurring,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProductParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.CompanyID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    code = $3, name = $4, description = $5, unit = $6, unit_price = $7,
    currency = $8, cost = $9, vat_rate_pct = $10, category = $11,
    is_recurring = $12, is_active = $13, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, code, name, description, unit, unit_price, currency, cost, vat_rate_pct, category, is_recurring, is_active, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CompanyID   uuid.UUID      `db:"company_id" json:"company_id"`
	Code        *string        `db:"code" json:"code"`
	Name        string         `db:"name" json:"name"`
	Description *string        `db:"description" json:"description"`
	Unit        *string        `db:"unit" json:"unit"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	Currency    *string        `db:"currency" json:"currency"`
	Cost        pgtype.Numeric `db:"cost" json:"cost"`
	VatRatePct  pgtype.Numeric `db:"vat_rate_pct" json:"vat_rate_pct"`
	Category    *string        `db:"category" json:"category"`
	IsRecurring bool           `db:"is_recurring" json:"is_recurring"`
	IsActive    bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.UnitPrice,
		arg.Currency,
		arg.Cost,
		arg.VatRatePct,
		arg.Category,
		arg.IsRecurring,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.UnitPrice,
		&i.Currency,
		&i.Cost,
		&i.VatRatePct,
		&i.Category,
		&i.IsRecurring,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
