// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role_in_project)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role_in_project = EXCLUDED.role_in_project
`

type AddProjectMemberParams struct {
	ProjectID     uuid.UUID `db:"project_id" json:"project_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	RoleInProject *string   `db:"role_in_project" json:"role_in_project"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.RoleInProject)
	return err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO project_milestones (project_id, name, description, deliverables, committed_date, status, order_pos)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, description, deliverables, committed_date, status, order_pos, created_at, updated_at, deleted_at
`

type CreateMilestoneParams struct {
	ProjectID     uuid.UUID   `db:"project_id" json:"project_id"`
	Name          string      `db:"name" json:"name"`
	Description   *string     `db:"description" json:"description"`
	Deliverables  *string     `db:"deliverables" json:"deliverables"`
	CommittedDate pgtype.Date `db:"committed_date" json:"committed_date"`
	Status        string      `db:"status" json:"status"`
	OrderPos      *int16      `db:"order_pos" json:"order_pos"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Deliverables,
		arg.CommittedDate,
		arg.Status,
		arg.OrderPos,
	)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Deliverables,
		&i.CommittedDate,
		&i.Status,
		&i.OrderPos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    company_id, client_id, name, description, start_date, estimated_end_date,
    status, responsible_id, budget_hours, budget_amount, currency, opportunity_id, quote_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, company_id, client_id, name, description, start_date, estimated_end_date, actual_end_date, status, responsible_id, budget_hours, budget_amount, currency, opportunity_id, quote_id, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	CompanyID        uuid.UUID      `db:"company_id" json:"company_id"`
	ClientID         uuid.UUID      `db:"client_id" json:"client_id"`
	Name             string         `db:"name" json:"name"`
	Description      *string        `db:"description" json:"description"`
	StartDate        pgtype.Date    `db:"start_date" json:"start_date"`
	EstimatedEndDate pgtype.Date    `db:"estimated_end_date" json:"estimated_end_date"`
	Status           string         `db:"status" json:"status"`
	ResponsibleID    pgtype.UUID    `db:"responsible_id" json:"responsible_id"`
	BudgetHours      pgtype.Numeric `db:"budget_hours" json:"budget_hours"`
	BudgetAmount     pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	Currency         string         `db:"currency" json:"currency"`
	OpportunityID    pgtype.UUID    `db:"opportunity_id" json:"opportunity_id"`
	QuoteID          pgtype.UUID    `db:"quote_id" json:"quote_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.CompanyID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EstimatedEndDate,
		arg.Status,
		arg.ResponsibleID,
		arg.BudgetHours,
		arg.BudgetAmount,
		arg.Currency,
		arg.OpportunityID,
		arg.QuoteID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EstimatedEndDate,
		&i.ActualEndDate,
		&i.Status,
		&i.ResponsibleID,
		&i.BudgetHours,
		&i.BudgetAmount,
		&i.Currency,
		&i.OpportunityID,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMilestoneByID = `-- name: GetMilestoneByID :one
SELECT id, project_id, name, description, deliverables, committed_date, status, order_pos, created_at, updated_at, deleted_at FROM project_milestones WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMilestoneByID(ctx context.Context, id uuid.UUID) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, getMilestoneByID, id)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Deliverables,
		&i.CommittedDate,
		&i.Status,
		&i.OrderPos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, company_id, client_id, name, description, start_date, estimated_end_date, actual_end_date, status, responsible_id, budget_hours, budget_amount, currency, opportunity_id, quote_id, created_at, updated_at, deleted_at FROM projects WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetProjectByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.CompanyID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EstimatedEndDate,
		&i.ActualEndDate,
		&i.Status,
		&i.ResponsibleID,
		&i.BudgetHours,
		&i.BudgetAmount,
		&i.Currency,
		&i.OpportunityID,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectTimeStats = `-- name: GetProjectTimeStats :one
SELECT
    COALESCE(SUM(duration_minutes), 0)::bigint AS total_minutes,
    COALESCE(SUM(CASE WHEN is_billable THEN duration_minutes ELSE 0 END), 0)::bigint AS billable_minutes
FROM time_entries
WHERE project_id = $1 AND company_id = $2
`

type GetProjectTimeStatsParams struct {
	ProjectID pgtype.UUID `db:"project_id" json:"project_id"`
	CompanyID uuid.UUID   `db:"company_id" json:"company_id"`
}

type GetProjectTimeStatsRow struct {
	TotalMinutes    int64 `db:"total_minutes" json:"total_minutes"`
	BillableMinutes int64 `db:"billable_minutes" json:"billable_minutes"`
}

func (q *Queries) GetProjectTimeStats(ctx context.Context, arg GetProjectTimeStatsParams) (GetProjectTimeStatsRow, error) {
	row := q.db.QueryRow(ctx, getProjectTimeStats, arg.ProjectID, arg.CompanyID)
	var i GetProjectTimeStatsRow
	err := row.Scan(&i.TotalMinutes, &i.BillableMinutes)
	return i, err
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, project_id, name, description, deliverables, committed_date, status, order_pos, created_at, updated_at, deleted_at FROM project_milestones
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY order_pos NULLS LAST, created_at
`

func (q *Queries) ListMilestones(ctx context.Context, projectID uuid.UUID) ([]ProjectMilestone, error) {
	rows, err := q.db.Query(ctx, listMilestones, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMilestone{}
	for rows.Next() {
		var i ProjectMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Deliverables,
			&i.CommittedDate,
			&i.Status,
			&i.OrderPos,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role_in_project,
       u.full_name, u.email
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
`

type ListProjectMembersRow struct {
	ProjectID     uuid.UUID `db:"project_id" json:"project_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	RoleInProject *string   `db:"role_in_project" json:"role_in_project"`
	FullName      string    `db:"full_name" json:"full_name"`
	Email         string    `db:"email" json:"email"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.RoleInProject,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, company_id, client_id, name, description, start_date, estimated_end_date, actual_end_date, status, responsible_id, budget_hours, budget_amount, currency, opportunity_id, quote_id, created_at, updated_at, deleted_at FROM projects
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($3::uuid IS NULL OR client_id = $3)
  AND ($4::uuid IS NULL OR responsible_id = $4)
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
`

type ListProjectsParams struct {
	CompanyID     uuid.UUID   `db:"company_id" json:"company_id"`
	Column2       string      `db:"column_2" json:"column_2"`
	ClientID      pgtype.UUID `db:"client_id" json:"client_id"`
	ResponsibleID pgtype.UUID `db:"responsible_id" json:"responsible_id"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.CompanyID,
		arg.Column2,
		arg.ClientID,
		arg.ResponsibleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EstimatedEndDate,
			&i.ActualEndDate,
			&i.Status,
			&i.ResponsibleID,
			&i.BudgetHours,
			&i.BudgetAmount,
			&i.Currency,
			&i.OpportunityID,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const softDeleteMilestone = `-- name: SoftDeleteMilestone :exec
UPDATE project_milestones SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type SoftDeleteMilestoneParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	ProjectID uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) SoftDeleteMilestone(ctx context.Context, arg SoftDeleteMilestoneParams) error {
	_, err := q.db.Exec(ctx, softDeleteMilestone, arg.ID, arg.ProjectID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.CompanyID)
	return err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE project_milestones SET
    name = $3, description = $4, deliverables = $5, committed_date = $6,
    status = $7, order_pos = $8, updated_at = now()
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
RETURNING id, project_id, name, description, deliverables, committed_date, status, order_pos, created_at, updated_at, deleted_at
`

type UpdateMilestoneParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	ProjectID     uuid.UUID   `db:"project_id" json:"project_id"`
	Name          string      `db:"name" json:"name"`
	Description   *string     `db:"description" json:"description"`
	Deliverables  *string     `db:"deliverables" json:"deliverables"`
	CommittedDate pgtype.Date `db:"committed_date" json:"committed_date"`
	Status        string      `db:"status" json:"status"`
	OrderPos      *int16      `db:"order_pos" json:"order_pos"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Deliverables,
		arg.CommittedDate,
		arg.Status,
		arg.OrderPos,
	)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Deliverables,
		&i.CommittedDate,
		&i.Status,
		&i.OrderPos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    client_id = $3, name = $4, description = $5, start_date = $6,
    estimated_end_date = $7, actual_end_date = $8, status = $9,
    responsible_id = $10, budget_hours = $11, budget_amount = $12,
    currency = $13, opportunity_id = $14, quote_id = $15, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, client_id, name, description, start_date, estimated_end_date, actual_end_date, status, responsible_id, budget_hours, budget_amount, currency, opportunity_id, quote_id, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	CompanyID        uuid.UUID      `db:"company_id" json:"company_id"`
	ClientID         uuid.UUID      `db:"client_id" json:"client_id"`
	Name             string         `db:"name" json:"name"`
	Description      *string        `db:"description" json:"description"`
	StartDate        pgtype.Date    `db:"start_date" json:"start_date"`
	EstimatedEndDate pgtype.Date    `db:"estimated_end_date" json:"estimated_end_date"`
	ActualEndDate    pgtype.Date    `db:"actual_end_date" json:"actual_end_date"`
	Status           string         `db:"status" json:"status"`
	ResponsibleID    pgtype.UUID    `db:"responsible_id" json:"responsible_id"`
	BudgetHours      pgtype.Numeric `db:"budget_hours" json:"budget_hours"`
	BudgetAmount     pgtype.Numeric `db:"budget_amount" json:"budget_amount"`
	Currency         string         `db:"currency" json:"currency"`
	OpportunityID    pgtype.UUID    `db:"opportunity_id" json:"opportunity_id"`
	QuoteID          pgtype.UUID    `db:"quote_id" json:"quote_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.CompanyID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EstimatedEndDate,
		arg.ActualEndDate,
		arg.Status,
		arg.ResponsibleID,
		arg.BudgetHours,
		arg.BudgetAmount,
		arg.Currency,
		arg.OpportunityID,
		arg.QuoteID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EstimatedEndDate,
		&i.ActualEndDate,
		&i.Status,
		&i.ResponsibleID,
		&i.BudgetHours,
		&i.BudgetAmount,
		&i.Currency,
		&i.OpportunityID,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
