// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quote.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (
    company_id, number, contact_id, opportunity_id, user_id,
    date, valid_until, currency, exchange_rate, status, version, parent_id, notes,
    subtotal, tax_total, total
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at
`

type CreateQuoteParams struct {
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	Number        string         `db:"number" json:"number"`
	ContactID     uuid.UUID      `db:"contact_id" json:"contact_id"`
	OpportunityID pgtype.UUID    `db:"opportunity_id" json:"opportunity_id"`
	UserID        uuid.UUID      `db:"user_id" json:"user_id"`
	Date          pgtype.Date    `db:"date" json:"date"`
	ValidUntil    pgtype.Date    `db:"valid_until" json:"valid_until"`
	Currency      string         `db:"currency" json:"currency"`
	ExchangeRate  pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	Status        string         `db:"status" json:"status"`
	Version       int16          `db:"version" json:"version"`
	ParentID      pgtype.UUID    `db:"parent_id" json:"parent_id"`
	Notes         *string        `db:"notes" json:"notes"`
	Subtotal      pgtype.Numeric `db:"subtotal" json:"subtotal"`
	TaxTotal      pgtype.Numeric `db:"tax_total" json:"tax_total"`
	Total         pgtype.Numeric `db:"total" json:"total"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.CompanyID,
		arg.Number,
		arg.ContactID,
		arg.OpportunityID,
		arg.UserID,
		arg.Date,
		arg.ValidUntil,
		arg.Currency,
		arg.ExchangeRate,
		arg.Status,
		arg.Version,
		arg.ParentID,
		arg.Notes,
		arg.Subtotal,
		arg.TaxTotal,
		arg.Total,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.ContactID,
		&i.OpportunityID,
		&i.UserID,
		&i.Date,
		&i.ValidUntil,
		&i.Currency,
		&i.ExchangeRate,
		&i.Status,
		&i.Version,
		&i.ParentID,
		&i.Notes,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createQuoteItem = `-- name: CreateQuoteItem :one
INSERT INTO quote_items (quote_id, product_id, description, quantity, unit_price, discount_pct, vat_rate_pct, line_subtotal, line_tax, line_total, order_pos)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, quote_id, product_id, description, quantity, unit_price, discount_pct, vat_rate_pct, line_subtotal, line_tax, line_total, order_pos
`

type CreateQuoteItemParams struct {
	QuoteID      uuid.UUID      `db:"quote_id" json:"quote_id"`
	ProductID    pgtype.UUID    `db:"product_id" json:"product_id"`
	Description  string         `db:"description" json:"description"`
	Quantity     pgtype.Numeric `db:"quantity" json:"quantity"`
	UnitPrice    pgtype.Numeric `db:"unit_price" json:"unit_price"`
	DiscountPct  pgtype.Numeric `db:"discount_pct" json:"discount_pct"`
	VatRatePct   pgtype.Numeric `db:"vat_rate_pct" json:"vat_rate_pct"`
	LineSubtotal pgtype.Numeric `db:"line_subtotal" json:"line_subtotal"`
	LineTax      pgtype.Numeric `db:"line_tax" json:"line_tax"`
	LineTotal    pgtype.Numeric `db:"line_total" json:"line_total"`
	OrderPos     *int16         `db:"order_pos" json:"order_pos"`
}

func (q *Queries) CreateQuoteItem(ctx context.Context, arg CreateQuoteItemParams) (QuoteItem, error) {
	row := q.db.QueryRow(ctx, createQuoteItem,
		arg.QuoteID,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountPct,
		arg.VatRatePct,
		arg.LineSubtotal,
		arg.LineTax,
		arg.LineTotal,
		arg.OrderPos,
	)
	var i QuoteItem
	err := row.Scan(
		&i.ID,
		&i.QuoteID,
		&i.ProductID,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountPct,
		&i.VatRatePct,
		&i.LineSubtotal,
		&i.LineTax,
		&i.LineTotal,
		&i.OrderPos,
	)
	return i, err
}

const deleteQuoteItems = `-- name: DeleteQuoteItems :exec
DELETE FROM quote_items WHERE quote_id = $1
`

func (q *Queries) DeleteQuoteItems(ctx context.Context, quoteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuoteItems, quoteID)
	return err
}

const getMaxQuoteNumber = `-- name: GetMaxQuoteNumber :one
SELECT COALESCE(MAX(CAST(SUBSTRING(number FROM '[0-9]+$') AS INTEGER)), 0)::int
FROM quotes WHERE company_id = $1
`

func (q *Queries) GetMaxQuoteNumber(ctx context.Context, companyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxQuoteNumber, companyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getQuoteByID = `-- name: GetQuoteByID :one
SELECT id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at FROM quotes WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetQuoteByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetQuoteByID(ctx context.Context, arg GetQuoteByIDParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByID, arg.ID, arg.CompanyID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.ContactID,
		&i.OpportunityID,
		&i.UserID,
		&i.Date,
		&i.ValidUntil,
		&i.Currency,
		&i.ExchangeRate,
		&i.Status,
		&i.Version,
		&i.ParentID,
		&i.Notes,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuoteByNumber = `-- name: GetQuoteByNumber :one
SELECT id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at FROM quotes WHERE company_id = $1 AND number = $2 AND deleted_at IS NULL
`

type GetQuoteByNumberParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Number    string    `db:"number" json:"number"`
}

func (q *Queries) GetQuoteByNumber(ctx context.Context, arg GetQuoteByNumberParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByNumber, arg.CompanyID, arg.Number)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.ContactID,
		&i.OpportunityID,
		&i.UserID,
		&i.Date,
		&i.ValidUntil,
		&i.Currency,
		&i.ExchangeRate,
		&i.Status,
		&i.Version,
		&i.ParentID,
		&i.Notes,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQuoteVersions = `-- name: GetQuoteVersions :many
SELECT id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at FROM quotes
WHERE company_id = $1
  AND deleted_at IS NULL
  AND (id = $2 OR parent_id = $2)
ORDER BY version ASC
`

type GetQuoteVersionsParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetQuoteVersions(ctx context.Context, arg GetQuoteVersionsParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, getQuoteVersions, arg.CompanyID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.ContactID,
			&i.OpportunityID,
			&i.UserID,
			&i.Date,
			&i.ValidUntil,
			&i.Currency,
			&i.ExchangeRate,
			&i.Status,
			&i.Version,
			&i.ParentID,
			&i.Notes,
			&i.Subtotal,
			&i.TaxTotal,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuoteItems = `-- name: ListQuoteItems :many
SELECT id, quote_id, product_id, description, quantity, unit_price, discount_pct, vat_rate_pct, line_subtotal, line_tax, line_total, order_pos FROM quote_items WHERE quote_id = $1 ORDER BY order_pos NULLS LAST, id
`

func (q *Queries) ListQuoteItems(ctx context.Context, quoteID uuid.UUID) ([]QuoteItem, error) {
	rows, err := q.db.Query(ctx, listQuoteItems, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuoteItem{}
	for rows.Next() {
		var i QuoteItem
		if err := rows.Scan(
			&i.ID,
			&i.QuoteID,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountPct,
			&i.VatRatePct,
			&i.LineSubtotal,
			&i.LineTax,
			&i.LineTotal,
			&i.OrderPos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at FROM quotes
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR contact_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR opportunity_id = $4)
ORDER BY created_at DESC
`

type ListQuotesParams struct {
	CompanyID     uuid.UUID   `db:"company_id" json:"company_id"`
	ContactID     pgtype.UUID `db:"contact_id" json:"contact_id"`
	Status        *string     `db:"status" json:"status"`
	OpportunityID pgtype.UUID `db:"opportunity_id" json:"opportunity_id"`
}

func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes,
		arg.CompanyID,
		arg.ContactID,
		arg.Status,
		arg.OpportunityID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Number,
			&i.ContactID,
			&i.OpportunityID,
			&i.UserID,
			&i.Date,
			&i.ValidUntil,
			&i.Currency,
			&i.ExchangeRate,
			&i.Status,
			&i.Version,
			&i.ParentID,
			&i.Notes,
			&i.Subtotal,
			&i.TaxTotal,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQuote = `-- name: SoftDeleteQuote :exec
UPDATE quotes SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteQuoteParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteQuote(ctx context.Context, arg SoftDeleteQuoteParams) error {
	_, err := q.db.Exec(ctx, softDeleteQuote, arg.ID, arg.CompanyID)
	return err
}

const updateQuote = `-- name: UpdateQuote :one
UPDATE quotes SET
    contact_id = $3, opportunity_id = $4, user_id = $5,
    date = $6, valid_until = $7, currency = $8, exchange_rate = $9,
    notes = $10, subtotal = $11, tax_total = $12, total = $13, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at
`

type UpdateQuoteParams struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	CompanyID     uuid.UUID      `db:"company_id" json:"company_id"`
	ContactID     uuid.UUID      `db:"contact_id" json:"contact_id"`
	OpportunityID pgtype.UUID    `db:"opportunity_id" json:"opportunity_id"`
	UserID        uuid.UUID      `db:"user_id" json:"user_id"`
	Date          pgtype.Date    `db:"date" json:"date"`
	ValidUntil    pgtype.Date    `db:"valid_until" json:"valid_until"`
	Currency      string         `db:"currency" json:"currency"`
	ExchangeRate  pgtype.Numeric `db:"exchange_rate" json:"exchange_rate"`
	Notes         *string        `db:"notes" json:"notes"`
	Subtotal      pgtype.Numeric `db:"subtotal" json:"subtotal"`
	TaxTotal      pgtype.Numeric `db:"tax_total" json:"tax_total"`
	Total         pgtype.Numeric `db:"total" json:"total"`
}

func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, updateQuote,
		arg.ID,
		arg.CompanyID,
		arg.ContactID,
		arg.OpportunityID,
		arg.UserID,
		arg.Date,
		arg.ValidUntil,
		arg.Currency,
		arg.ExchangeRate,
		arg.Notes,
		arg.Subtotal,
		arg.TaxTotal,
		arg.Total,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.ContactID,
		&i.OpportunityID,
		&i.UserID,
		&i.Date,
		&i.ValidUntil,
		&i.Currency,
		&i.ExchangeRate,
		&i.Status,
		&i.Version,
		&i.ParentID,
		&i.Notes,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateQuoteStatus = `-- name: UpdateQuoteStatus :one
UPDATE quotes SET status = $3, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, number, contact_id, opportunity_id, user_id, date, valid_until, currency, exchange_rate, status, version, parent_id, notes, subtotal, tax_total, total, created_at, updated_at, deleted_at
`

type UpdateQuoteStatusParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Status    string    `db:"status" json:"status"`
}

func (q *Queries) UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) (Quote, error) {
	row := q.db.QueryRow(ctx, updateQuoteStatus, arg.ID, arg.CompanyID, arg.Status)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Number,
		&i.ContactID,
		&i.OpportunityID,
		&i.UserID,
		&i.Date,
		&i.ValidUntil,
		&i.Currency,
		&i.ExchangeRate,
		&i.Status,
		&i.Version,
		&i.ParentID,
		&i.Notes,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
