// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scraping_job.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countScrapingJobsToday = `-- name: CountScrapingJobsToday :one
SELECT COALESCE(SUM(result_count_requested), 0)::int
FROM scraping_jobs
WHERE company_id = $1
  AND user_id = $2
  AND created_at >= date_trunc('day', now())
`

type CountScrapingJobsTodayParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CountScrapingJobsToday(ctx context.Context, arg CountScrapingJobsTodayParams) (int32, error) {
	row := q.db.QueryRow(ctx, countScrapingJobsToday, arg.CompanyID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createScrapingJob = `-- name: CreateScrapingJob :one
INSERT INTO scraping_jobs (company_id, user_id, query, result_count_requested, country, language, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, company_id, user_id, query, result_count_requested, country, language, status, started_at, finished_at, search_api_cost_usd, llm_tokens_input, llm_tokens_output, llm_cost_usd, total_cost_usd, urls_processed, leads_found, error_summary, created_at
`

type CreateScrapingJobParams struct {
	CompanyID            uuid.UUID `db:"company_id" json:"company_id"`
	UserID               uuid.UUID `db:"user_id" json:"user_id"`
	Query                string    `db:"query" json:"query"`
	ResultCountRequested int32     `db:"result_count_requested" json:"result_count_requested"`
	Country              *string   `db:"country" json:"country"`
	Language             *string   `db:"language" json:"language"`
}

func (q *Queries) CreateScrapingJob(ctx context.Context, arg CreateScrapingJobParams) (ScrapingJob, error) {
	row := q.db.QueryRow(ctx, createScrapingJob,
		arg.CompanyID,
		arg.UserID,
		arg.Query,
		arg.ResultCountRequested,
		arg.Country,
		arg.Language,
	)
	var i ScrapingJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Query,
		&i.ResultCountRequested,
		&i.Country,
		&i.Language,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchApiCostUsd,
		&i.LlmTokensInput,
		&i.LlmTokensOutput,
		&i.LlmCostUsd,
		&i.TotalCostUsd,
		&i.UrlsProcessed,
		&i.LeadsFound,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getScrapingJobByID = `-- name: GetScrapingJobByID :one
SELECT id, company_id, user_id, query, result_count_requested, country, language, status, started_at, finished_at, search_api_cost_usd, llm_tokens_input, llm_tokens_output, llm_cost_usd, total_cost_usd, urls_processed, leads_found, error_summary, created_at FROM scraping_jobs WHERE id = $1 AND company_id = $2
`

type GetScrapingJobByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetScrapingJobByID(ctx context.Context, arg GetScrapingJobByIDParams) (ScrapingJob, error) {
	row := q.db.QueryRow(ctx, getScrapingJobByID, arg.ID, arg.CompanyID)
	var i ScrapingJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Query,
		&i.ResultCountRequested,
		&i.Country,
		&i.Language,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchApiCostUsd,
		&i.LlmTokensInput,
		&i.LlmTokensOutput,
		&i.LlmCostUsd,
		&i.TotalCostUsd,
		&i.UrlsProcessed,
		&i.LeadsFound,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listScrapingJobs = `-- name: ListScrapingJobs :many
SELECT id, company_id, user_id, query, result_count_requested, country, language, status, started_at, finished_at, search_api_cost_usd, llm_tokens_input, llm_tokens_output, llm_cost_usd, total_cost_usd, urls_processed, leads_found, error_summary, created_at FROM scraping_jobs WHERE company_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListScrapingJobs(ctx context.Context, companyID uuid.UUID) ([]ScrapingJob, error) {
	rows, err := q.db.Query(ctx, listScrapingJobs, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapingJob{}
	for rows.Next() {
		var i ScrapingJob
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Query,
			&i.ResultCountRequested,
			&i.Country,
			&i.Language,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SearchApiCostUsd,
			&i.LlmTokensInput,
			&i.LlmTokensOutput,
			&i.LlmCostUsd,
			&i.TotalCostUsd,
			&i.UrlsProcessed,
			&i.LeadsFound,
			&i.ErrorSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrapingJobCosts = `-- name: UpdateScrapingJobCosts :one
UPDATE scraping_jobs SET
    search_api_cost_usd = $3, llm_tokens_input = $4, llm_tokens_output = $5,
    llm_cost_usd = $6, total_cost_usd = $7
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, user_id, query, result_count_requested, country, language, status, started_at, finished_at, search_api_cost_usd, llm_tokens_input, llm_tokens_output, llm_cost_usd, total_cost_usd, urls_processed, leads_found, error_summary, created_at
`

type UpdateScrapingJobCostsParams struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	CompanyID        uuid.UUID      `db:"company_id" json:"company_id"`
	SearchApiCostUsd pgtype.Numeric `db:"search_api_cost_usd" json:"search_api_cost_usd"`
	LlmTokensInput   *int32         `db:"llm_tokens_input" json:"llm_tokens_input"`
	LlmTokensOutput  *int32         `db:"llm_tokens_output" json:"llm_tokens_output"`
	LlmCostUsd       pgtype.Numeric `db:"llm_cost_usd" json:"llm_cost_usd"`
	TotalCostUsd     pgtype.Numeric `db:"total_cost_usd" json:"total_cost_usd"`
}

func (q *Queries) UpdateScrapingJobCosts(ctx context.Context, arg UpdateScrapingJobCostsParams) (ScrapingJob, error) {
	row := q.db.QueryRow(ctx, updateScrapingJobCosts,
		arg.ID,
		arg.CompanyID,
		arg.SearchApiCostUsd,
		arg.LlmTokensInput,
		arg.LlmTokensOutput,
		arg.LlmCostUsd,
		arg.TotalCostUsd,
	)
	var i ScrapingJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Query,
		&i.ResultCountRequested,
		&i.Country,
		&i.Language,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchApiCostUsd,
		&i.LlmTokensInput,
		&i.LlmTokensOutput,
		&i.LlmCostUsd,
		&i.TotalCostUsd,
		&i.UrlsProcessed,
		&i.LeadsFound,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const updateScrapingJobStatus = `-- name: UpdateScrapingJobStatus :one
UPDATE scraping_jobs SET status = $3, started_at = $4, finished_at = $5,
    urls_processed = $6, leads_found = $7, error_summary = $8
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, user_id, query, result_count_requested, country, language, status, started_at, finished_at, search_api_cost_usd, llm_tokens_input, llm_tokens_output, llm_cost_usd, total_cost_usd, urls_processed, leads_found, error_summary, created_at
`

type UpdateScrapingJobStatusParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CompanyID     uuid.UUID          `db:"company_id" json:"company_id"`
	Status        string             `db:"status" json:"status"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt    pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	UrlsProcessed int32              `db:"urls_processed" json:"urls_processed"`
	LeadsFound    int32              `db:"leads_found" json:"leads_found"`
	ErrorSummary  *string            `db:"error_summary" json:"error_summary"`
}

func (q *Queries) UpdateScrapingJobStatus(ctx context.Context, arg UpdateScrapingJobStatusParams) (ScrapingJob, error) {
	row := q.db.QueryRow(ctx, updateScrapingJobStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UrlsProcessed,
		arg.LeadsFound,
		arg.ErrorSummary,
	)
	var i ScrapingJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Query,
		&i.ResultCountRequested,
		&i.Country,
		&i.Language,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SearchApiCostUsd,
		&i.LlmTokensInput,
		&i.LlmTokensOutput,
		&i.LlmCostUsd,
		&i.TotalCostUsd,
		&i.UrlsProcessed,
		&i.LeadsFound,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}
