// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    company_id, type, title, description, contact_id, project_id,
    assignee_id, reporter_id, origin, status, priority, due_date, parent_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, company_id, type, title, description, contact_id, project_id, assignee_id, reporter_id, origin, status, priority, due_date, parent_id, is_recurring, recurrence_rule, resolved_at, closed_at, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	Type        string      `db:"type" json:"type"`
	Title       string      `db:"title" json:"title"`
	Description *string     `db:"description" json:"description"`
	ContactID   pgtype.UUID `db:"contact_id" json:"contact_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	AssigneeID  pgtype.UUID `db:"assignee_id" json:"assignee_id"`
	ReporterID  uuid.UUID   `db:"reporter_id" json:"reporter_id"`
	Origin      *string     `db:"origin" json:"origin"`
	Status      string      `db:"status" json:"status"`
	Priority    string      `db:"priority" json:"priority"`
	DueDate     pgtype.Date `db:"due_date" json:"due_date"`
	ParentID    pgtype.UUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.CompanyID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.ContactID,
		arg.ProjectID,
		arg.AssigneeID,
		arg.ReporterID,
		arg.Origin,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ContactID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Origin,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.ParentID,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskComment = `-- name: CreateTaskComment :one
INSERT INTO task_comments (task_id, user_id, body) VALUES ($1, $2, $3) RETURNING id, task_id, user_id, body, created_at
`

type CreateTaskCommentParams struct {
	TaskID uuid.UUID `db:"task_id" json:"task_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Body   string    `db:"body" json:"body"`
}

func (q *Queries) CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createTaskComment, arg.TaskID, arg.UserID, arg.Body)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenTimer = `-- name: GetOpenTimer :one
SELECT id, task_id, user_id, started_at, ended_at, duration_minutes, note, created_at FROM task_time_entries
WHERE user_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetOpenTimer(ctx context.Context, userID uuid.UUID) (TaskTimeEntry, error) {
	row := q.db.QueryRow(ctx, getOpenTimer, userID)
	var i TaskTimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenTimerForTask = `-- name: GetOpenTimerForTask :one
SELECT id, task_id, user_id, started_at, ended_at, duration_minutes, note, created_at FROM task_time_entries
WHERE task_id = $1 AND user_id = $2 AND ended_at IS NULL
ORDER BY started_at DESC LIMIT 1
`

type GetOpenTimerForTaskParams struct {
	TaskID uuid.UUID `db:"task_id" json:"task_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOpenTimerForTask(ctx context.Context, arg GetOpenTimerForTaskParams) (TaskTimeEntry, error) {
	row := q.db.QueryRow(ctx, getOpenTimerForTask, arg.TaskID, arg.UserID)
	var i TaskTimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, company_id, type, title, description, contact_id, project_id, assignee_id, reporter_id, origin, status, priority, due_date, parent_id, is_recurring, recurrence_rule, resolved_at, closed_at, created_at, updated_at, deleted_at FROM tasks WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.CompanyID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ContactID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Origin,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.ParentID,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskHistory = `-- name: GetTaskHistory :many
SELECT id, task_id, user_id, from_status, to_status, from_assignee, to_assignee, created_at FROM task_status_history WHERE task_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetTaskHistory(ctx context.Context, taskID uuid.UUID) ([]TaskStatusHistory, error) {
	rows, err := q.db.Query(ctx, getTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStatusHistory{}
	for rows.Next() {
		var i TaskStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.FromStatus,
			&i.ToStatus,
			&i.FromAssignee,
			&i.ToAssignee,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT id, task_id, user_id, body, created_at FROM task_comments WHERE task_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]TaskComment, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, company_id, type, title, description, contact_id, project_id, assignee_id, reporter_id, origin, status, priority, due_date, parent_id, is_recurring, recurrence_rule, resolved_at, closed_at, created_at, updated_at, deleted_at FROM tasks
WHERE company_id = $1
  AND deleted_at IS NULL
  AND ($3::uuid IS NULL OR assignee_id = $3)
  AND ($2::text = '' OR status = $2)
  AND ($4::uuid IS NULL OR project_id = $4)
  AND ($5::uuid IS NULL OR contact_id = $5)
  AND ($6::date IS NULL OR due_date <= $6)
ORDER BY
    CASE priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,
    due_date NULLS LAST,
    created_at DESC
`

type ListTasksParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	Column2    string      `db:"column_2" json:"column_2"`
	AssigneeID pgtype.UUID `db:"assignee_id" json:"assignee_id"`
	ProjectID  pgtype.UUID `db:"project_id" json:"project_id"`
	ContactID  pgtype.UUID `db:"contact_id" json:"contact_id"`
	DueDate    pgtype.Date `db:"due_date" json:"due_date"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.CompanyID,
		arg.Column2,
		arg.AssigneeID,
		arg.ProjectID,
		arg.ContactID,
		arg.DueDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.ContactID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.ReporterID,
			&i.Origin,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.ParentID,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTaskHistory = `-- name: RecordTaskHistory :one
INSERT INTO task_status_history (task_id, user_id, from_status, to_status, from_assignee, to_assignee)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_id, user_id, from_status, to_status, from_assignee, to_assignee, created_at
`

type RecordTaskHistoryParams struct {
	TaskID       uuid.UUID   `db:"task_id" json:"task_id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	FromStatus   *string     `db:"from_status" json:"from_status"`
	ToStatus     *string     `db:"to_status" json:"to_status"`
	FromAssignee pgtype.UUID `db:"from_assignee" json:"from_assignee"`
	ToAssignee   pgtype.UUID `db:"to_assignee" json:"to_assignee"`
}

func (q *Queries) RecordTaskHistory(ctx context.Context, arg RecordTaskHistoryParams) (TaskStatusHistory, error) {
	row := q.db.QueryRow(ctx, recordTaskHistory,
		arg.TaskID,
		arg.UserID,
		arg.FromStatus,
		arg.ToStatus,
		arg.FromAssignee,
		arg.ToAssignee,
	)
	var i TaskStatusHistory
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.FromStatus,
		&i.ToStatus,
		&i.FromAssignee,
		&i.ToAssignee,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.CompanyID)
	return err
}

const startTaskTimer = `-- name: StartTaskTimer :one
INSERT INTO task_time_entries (task_id, user_id, started_at)
VALUES ($1, $2, $3)
RETURNING id, task_id, user_id, started_at, ended_at, duration_minutes, note, created_at
`

type StartTaskTimerParams struct {
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) StartTaskTimer(ctx context.Context, arg StartTaskTimerParams) (TaskTimeEntry, error) {
	row := q.db.QueryRow(ctx, startTaskTimer, arg.TaskID, arg.UserID, arg.StartedAt)
	var i TaskTimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const stopTaskTimer = `-- name: StopTaskTimer :one
UPDATE task_time_entries SET
    ended_at = $3,
    duration_minutes = CEIL(EXTRACT(EPOCH FROM ($3 - started_at)) / 60)::INT
WHERE id = $1 AND user_id = $2 AND ended_at IS NULL
RETURNING id, task_id, user_id, started_at, ended_at, duration_minutes, note, created_at
`

type StopTaskTimerParams struct {
	ID      uuid.UUID          `db:"id" json:"id"`
	UserID  uuid.UUID          `db:"user_id" json:"user_id"`
	EndedAt pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

func (q *Queries) StopTaskTimer(ctx context.Context, arg StopTaskTimerParams) (TaskTimeEntry, error) {
	row := q.db.QueryRow(ctx, stopTaskTimer, arg.ID, arg.UserID, arg.EndedAt)
	var i TaskTimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    type = $3, title = $4, description = $5, contact_id = $6,
    project_id = $7, priority = $8, due_date = $9, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, type, title, description, contact_id, project_id, assignee_id, reporter_id, origin, status, priority, due_date, parent_id, is_recurring, recurrence_rule, resolved_at, closed_at, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	CompanyID   uuid.UUID   `db:"company_id" json:"company_id"`
	Type        string      `db:"type" json:"type"`
	Title       string      `db:"title" json:"title"`
	Description *string     `db:"description" json:"description"`
	ContactID   pgtype.UUID `db:"contact_id" json:"contact_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	Priority    string      `db:"priority" json:"priority"`
	DueDate     pgtype.Date `db:"due_date" json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.CompanyID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.ContactID,
		arg.ProjectID,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ContactID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Origin,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.ParentID,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET
    status = $1::text, assignee_id = $2,
    resolved_at = CASE WHEN $1::text = 'resolved' AND resolved_at IS NULL THEN now() ELSE resolved_at END,
    closed_at   = CASE WHEN $1::text = 'closed'   AND closed_at   IS NULL THEN now() ELSE closed_at   END,
    updated_at  = now()
WHERE id = $3 AND company_id = $4 AND deleted_at IS NULL
RETURNING id, company_id, type, title, description, contact_id, project_id, assignee_id, reporter_id, origin, status, priority, due_date, parent_id, is_recurring, recurrence_rule, resolved_at, closed_at, created_at, updated_at, deleted_at
`

type UpdateTaskStatusParams struct {
	NewStatus  string      `db:"new_status" json:"new_status"`
	AssigneeID pgtype.UUID `db:"assignee_id" json:"assignee_id"`
	ID         uuid.UUID   `db:"id" json:"id"`
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.NewStatus,
		arg.AssigneeID,
		arg.ID,
		arg.CompanyID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ContactID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Origin,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.ParentID,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
