// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entry.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (
    company_id, user_id, date, started_at, ended_at, duration_minutes,
    description, task_id, project_id, contact_id, is_billable, hourly_rate, currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, company_id, user_id, date, started_at, ended_at, duration_minutes, description, task_id, project_id, contact_id, is_billable, hourly_rate, currency, invoice_line_id, created_at
`

type CreateTimeEntryParams struct {
	CompanyID       uuid.UUID          `db:"company_id" json:"company_id"`
	UserID          uuid.UUID          `db:"user_id" json:"user_id"`
	Date            pgtype.Date        `db:"date" json:"date"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DurationMinutes int32              `db:"duration_minutes" json:"duration_minutes"`
	Description     *string            `db:"description" json:"description"`
	TaskID          pgtype.UUID        `db:"task_id" json:"task_id"`
	ProjectID       pgtype.UUID        `db:"project_id" json:"project_id"`
	ContactID       pgtype.UUID        `db:"contact_id" json:"contact_id"`
	IsBillable      bool               `db:"is_billable" json:"is_billable"`
	HourlyRate      pgtype.Numeric     `db:"hourly_rate" json:"hourly_rate"`
	Currency        *string            `db:"currency" json:"currency"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.CompanyID,
		arg.UserID,
		arg.Date,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMinutes,
		arg.Description,
		arg.TaskID,
		arg.ProjectID,
		arg.ContactID,
		arg.IsBillable,
		arg.HourlyRate,
		arg.Currency,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Description,
		&i.TaskID,
		&i.ProjectID,
		&i.ContactID,
		&i.IsBillable,
		&i.HourlyRate,
		&i.Currency,
		&i.InvoiceLineID,
		&i.CreatedAt,
	)
	return i, err
}

const getTimeEntryByID = `-- name: GetTimeEntryByID :one
SELECT id, company_id, user_id, date, started_at, ended_at, duration_minutes, description, task_id, project_id, contact_id, is_billable, hourly_rate, currency, invoice_line_id, created_at FROM time_entries WHERE id = $1 AND company_id = $2
`

type GetTimeEntryByIDParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetTimeEntryByID(ctx context.Context, arg GetTimeEntryByIDParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, getTimeEntryByID, arg.ID, arg.CompanyID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.Description,
		&i.TaskID,
		&i.ProjectID,
		&i.ContactID,
		&i.IsBillable,
		&i.HourlyRate,
		&i.Currency,
		&i.InvoiceLineID,
		&i.CreatedAt,
	)
	return i, err
}

const getTimesheetWeek = `-- name: GetTimesheetWeek :many
SELECT id, company_id, user_id, date, started_at, ended_at, duration_minutes, description, task_id, project_id, contact_id, is_billable, hourly_rate, currency, invoice_line_id, created_at FROM time_entries
WHERE user_id = $1
  AND date >= $2 AND date < $2 + INTERVAL '7 days'
ORDER BY date, created_at
`

type GetTimesheetWeekParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetTimesheetWeek(ctx context.Context, arg GetTimesheetWeekParams) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, getTimesheetWeek, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Date,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
			&i.Description,
			&i.TaskID,
			&i.ProjectID,
			&i.ContactID,
			&i.IsBillable,
			&i.HourlyRate,
			&i.Currency,
			&i.InvoiceLineID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUtilizationStats = `-- name: GetUtilizationStats :one
SELECT
    COALESCE(SUM(duration_minutes), 0)::bigint AS total_minutes,
    COALESCE(SUM(CASE WHEN is_billable THEN duration_minutes ELSE 0 END), 0)::bigint AS billable_minutes
FROM time_entries
WHERE user_id = $1
  AND date >= $2 AND date <= $3
  AND company_id = $4
`

type GetUtilizationStatsParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	Date      pgtype.Date `db:"date" json:"date"`
	Date_2    pgtype.Date `db:"date_2" json:"date_2"`
	CompanyID uuid.UUID   `db:"company_id" json:"company_id"`
}

type GetUtilizationStatsRow struct {
	TotalMinutes    int64 `db:"total_minutes" json:"total_minutes"`
	BillableMinutes int64 `db:"billable_minutes" json:"billable_minutes"`
}

func (q *Queries) GetUtilizationStats(ctx context.Context, arg GetUtilizationStatsParams) (GetUtilizationStatsRow, error) {
	row := q.db.QueryRow(ctx, getUtilizationStats,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.CompanyID,
	)
	var i GetUtilizationStatsRow
	err := row.Scan(&i.TotalMinutes, &i.BillableMinutes)
	return i, err
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, company_id, user_id, date, started_at, ended_at, duration_minutes, description, task_id, project_id, contact_id, is_billable, hourly_rate, currency, invoice_line_id, created_at FROM time_entries
WHERE company_id = $1
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::uuid IS NULL OR project_id = $3)
  AND ($4::uuid IS NULL OR task_id = $4)
  AND ($5::date IS NULL OR date >= $5)
  AND ($6::date IS NULL OR date <= $6)
  AND ($7::boolean IS NULL OR is_billable = $7)
ORDER BY date DESC, created_at DESC
`

type ListTimeEntriesParams struct {
	CompanyID  uuid.UUID   `db:"company_id" json:"company_id"`
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	ProjectID  pgtype.UUID `db:"project_id" json:"project_id"`
	TaskID     pgtype.UUID `db:"task_id" json:"task_id"`
	FromDate   pgtype.Date `db:"from_date" json:"from_date"`
	ToDate     pgtype.Date `db:"to_date" json:"to_date"`
	IsBillable *bool       `db:"is_billable" json:"is_billable"`
}

func (q *Queries) ListTimeEntries(ctx context.Context, arg ListTimeEntriesParams) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listTimeEntries,
		arg.CompanyID,
		arg.UserID,
		arg.ProjectID,
		arg.TaskID,
		arg.FromDate,
		arg.ToDate,
		arg.IsBillable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Date,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
			&i.Description,
			&i.TaskID,
			&i.ProjectID,
			&i.ContactID,
			&i.IsBillable,
			&i.HourlyRate,
			&i.Currency,
			&i.InvoiceLineID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
