// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createVaultEntry = `-- name: CreateVaultEntry :one
INSERT INTO vault_entries (company_id, created_by, category, label, username, secret, url, notes, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, created_by, category, label, username, secret, url, notes, tags, created_at, updated_at, deleted_at
`

type CreateVaultEntryParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	CreatedBy uuid.UUID `db:"created_by" json:"created_by"`
	Category  string    `db:"category" json:"category"`
	Label     string    `db:"label" json:"label"`
	Username  *string   `db:"username" json:"username"`
	Secret    []byte    `db:"secret" json:"secret"`
	Url       *string   `db:"url" json:"url"`
	Notes     *string   `db:"notes" json:"notes"`
	Tags      []string  `db:"tags" json:"tags"`
}

func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, createVaultEntry,
		arg.CompanyID,
		arg.CreatedBy,
		arg.Category,
		arg.Label,
		arg.Username,
		arg.Secret,
		arg.Url,
		arg.Notes,
		arg.Tags,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Category,
		&i.Label,
		&i.Username,
		&i.Secret,
		&i.Url,
		&i.Notes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVaultEntry = `-- name: GetVaultEntry :one
SELECT id, company_id, created_by, category, label, username, secret, url, notes, tags, created_at, updated_at, deleted_at FROM vault_entries
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetVaultEntryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) GetVaultEntry(ctx context.Context, arg GetVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, getVaultEntry, arg.ID, arg.CompanyID)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Category,
		&i.Label,
		&i.Username,
		&i.Secret,
		&i.Url,
		&i.Notes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVaultEntries = `-- name: ListVaultEntries :many
SELECT id, company_id, created_by, category, label, username, secret, url, notes, tags, created_at, updated_at, deleted_at FROM vault_entries
WHERE company_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR category = $2)
ORDER BY category, label
`

type ListVaultEntriesParams struct {
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Category  *string   `db:"category" json:"category"`
}

func (q *Queries) ListVaultEntries(ctx context.Context, arg ListVaultEntriesParams) ([]VaultEntry, error) {
	rows, err := q.db.Query(ctx, listVaultEntries, arg.CompanyID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultEntry{}
	for rows.Next() {
		var i VaultEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CreatedBy,
			&i.Category,
			&i.Label,
			&i.Username,
			&i.Secret,
			&i.Url,
			&i.Notes,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVaultEntry = `-- name: SoftDeleteVaultEntry :exec
UPDATE vault_entries SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteVaultEntryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
}

func (q *Queries) SoftDeleteVaultEntry(ctx context.Context, arg SoftDeleteVaultEntryParams) error {
	_, err := q.db.Exec(ctx, softDeleteVaultEntry, arg.ID, arg.CompanyID)
	return err
}

const updateVaultEntry = `-- name: UpdateVaultEntry :one
UPDATE vault_entries
SET category = $3, label = $4, username = $5, secret = $6, url = $7, notes = $8, tags = $9, updated_at = now()
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
RETURNING id, company_id, created_by, category, label, username, secret, url, notes, tags, created_at, updated_at, deleted_at
`

type UpdateVaultEntryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	CompanyID uuid.UUID `db:"company_id" json:"company_id"`
	Category  string    `db:"category" json:"category"`
	Label     string    `db:"label" json:"label"`
	Username  *string   `db:"username" json:"username"`
	Secret    []byte    `db:"secret" json:"secret"`
	Url       *string   `db:"url" json:"url"`
	Notes     *string   `db:"notes" json:"notes"`
	Tags      []string  `db:"tags" json:"tags"`
}

func (q *Queries) UpdateVaultEntry(ctx context.Context, arg UpdateVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, updateVaultEntry,
		arg.ID,
		arg.CompanyID,
		arg.Category,
		arg.Label,
		arg.Username,
		arg.Secret,
		arg.Url,
		arg.Notes,
		arg.Tags,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Category,
		&i.Label,
		&i.Username,
		&i.Secret,
		&i.Url,
		&i.Notes,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
